#11381 ability to manually set max column width added
dbeaver/dbeaver pull request #12052
Opened 2021-04-08 21:12 UTC by LonwoLonwo

![2021-04-09 00_02_12-DBeaver Enterprise 21 0 3 - film](https://user-images.githubusercontent.com/45152336/114097075-3bdaac80-98c8-11eb-81e4-3adb3edcdb1b.png)

2021-04-08 22:35 UTC, ShadelessFox approved these changes

2021-04-09 07:45 UTC, akilovich approved these changes

2021-04-09 16:30 UTC, serge-rider commented
1. Let's calculate width in percent.
2. Change label to "Maximum auto-sized column with"

2021-04-09 22:26 UTC, ShadelessFox requested changes

2021-04-09 22:26 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/lightgrid/LightGrid.java
> +                            int newFatWidth = (freeSpacePercent > maxColumnDefWidth ? freeSpace : (int) (1.0 * maxColumnDefWidth / 100 * clientWidth));
Confusing multiplication by `1.0`, consider casting `maxColumnDefWidth` to `double` or replacing `100` with `100.0`

2021-04-12 08:30 UTC, ShadelessFox approved these changes

2021-04-13 16:38 UTC, serge-rider commented
Add min/max value validation > 0 & <=100

2021-04-13 20:54 UTC, ShadelessFox requested changes

2021-04-13 20:54 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/editors/data/preferences/PrefPageResultSetPresentationGrid.java
> +    private Spinner maxDefColumnWidth;
Please avoid using spinner, it looks goofy on Linux OSes. (see also 547b2909f201aef24e7b095592297edd7973845a)

You can use custom `VerifyListener` applied on the `Text` widget using `addVerifyListener` that will check the bounds.

2021-04-14 02:10 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/editors/data/preferences/PrefPageResultSetPresentationGrid.java
> +    private Spinner maxDefColumnWidth;
Perhaps it may be OK to use `Spinner` here.

2021-04-14 02:10 UTC, ShadelessFox approved these changes

2021-04-14 08:33 UTC, closed without merging