#10731 check if font monospaced by measuring chars width in range [0x21; 0x7F)
dbeaver/dbeaver pull request #12516
Opened 2021-05-18 10:15 UTC by akilovich

2021-05-18 11:26 UTC, ShadelessFox requested changes

2021-05-18 11:26 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.hex/src/org/jkiss/dbeaver/ui/editors/binary/pref/HexPreferencesManager.java
> +        char ch = ' ';
Can you please extract these obscure characters (`' '` and `'\u007F'`) to a class constants?

2021-05-18 11:26 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.hex/src/org/jkiss/dbeaver/ui/editors/binary/pref/HexPreferencesManager.java
>          if (!fontsRejected.contains(fontData.getName())) {
What about filtering-out Windows-specific fonts that start with `@`? They're vertically aligned, so they can't be used as a monospace font in this situation.

https://devblogs.microsoft.com/oldnewthing/20120719-00/?p=7093

2021-05-18 12:11 UTC, ShadelessFox approved these changes

2021-05-18 12:54 UTC, LonwoLonwo approved these changes

2021-05-19 11:44 UTC, ShadelessFox approved these changes
That's way better :^)

2021-05-20 08:57 UTC, merged