#12141 highlight selected row by hand
dbeaver/dbeaver pull request #12702
Opened 2021-06-02 10:59 UTC by akilovich

2021-06-02 15:26 UTC, LonwoLonwo approved these changes

2021-06-03 08:37 UTC, ShadelessFox requested changes

2021-06-03 08:37 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/data/editors/ReferenceValueEditor.java
> +                    item.setBackground(null); }
Please fix code style.

2021-06-03 08:48 UTC, ShadelessFox approved these changes

2021-06-03 09:47 UTC, merged