Fix for Redshift Data Editor-Editing of Date/Timestamp column
dbeaver/dbeaver pull request #13605
Opened 2021-08-21 17:42 UTC by deepaksenthilkumar

https://github.com/dbeaver/dbeaver/issues/13544

The Date/Timestamp columns are fixed now. Redshift doesn't know about Types.OTHER, it has to be Types.VARCHAR.

The 1.x Redshift JDBC driver doesn't work fine for timestamp with timezone, time, timetz columns edits from data editor

2021-08-21 21:06 UTC, ShadelessFox requested changes

2021-08-21 21:06 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/data/PostgreDateTimeValueHandler.java
> +	}
Please reformat indentation using spaces instead of tabs and then squash these commits into just one

2021-08-21 22:09 UTC, ShadelessFox approved these changes

2021-08-21 22:11 UTC, ShadelessFox approved these changes
Didn't notice this one :)

2021-08-22 06:59 UTC, serge-rider commented
We use Types.OTHER i nmany other PostgreSQL value handlers.
Also I don't like `instanceof` checks in base PG code.

Probably we need some more general solution. E.g. add add `bindObjectParameter` function in PostgreServerExtension.

2021-08-23 19:50 UTC, deepaksenthilkumar commented
@serge-rider Agree with you. I just copied the same pattern in [PostgreValueHandlerProvider
](https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/data/PostgreValueHandlerProvider.java)

Can you elaborate further on the approach, can we have Redshift specific Value handler?

2021-08-26 12:30 UTC, serge-rider commented
I've add extra API in ServerExtension.

Fix pushed in https://github.com/dbeaver/dbeaver/commit/8f4b7c3f6f5240652a4e71b57a5e4a25fe1886ec

2021-08-26 12:30 UTC, closed without merging