Header font name added to XLSX exporter
dbeaver/dbeaver pull request #14049
Opened 2021-09-29 12:27 UTC by PavelVasiliev

2021-09-29 12:36 UTC, PavelVasiliev commented
XLSX config screen - https://cloud.mail.ru/public/dNsD/r4MAmQBoM

2021-09-30 09:43 UTC, ShadelessFox requested changes
Thanks for the contribution!

2021-09-30 09:43 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_de.properties
> +dataTransfer.processor.xlsx.propertyGroup.general.label          = Allgemein
Please fix formatting to avoid having 100% deletions and additions of the file.

2021-09-30 09:43 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_ja.properties
> +dataTransfer.processor.xlsx.property.headerFontName.description=\u6700\u521d\u306e\u884c\u306e\u30d5\u30a9\u30f3\u30c8\u540d
Until you're sure that you know that language, such translations are useless and tend to contain grammatical errors.

2021-09-30 09:43 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_ko.properties
> +dataTransfer.processor.xlsx.property.headerFontName.description=\uccab \ubc88\uc9f8 \ud589 \uae00\uaf34 \uc774\ub984
Until you're sure that you know that language, such translations are useless and tend to contain grammatical errors.

2021-09-30 09:43 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_pt_BR.properties
> +dataTransfer.processor.xlsx.property.headerFont.name=Fonte da linha do cabe�alho
Please fix encoding problems.

2021-09-30 09:43 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_pt_BR.properties
> +dataTransfer.processor.xlsx.property.dateFormat.description=Formato de excel e datas (e.x. m/d/yy hh:mm) vo�e pode mudar no excel.
Please fix encoding problems.

2021-09-30 09:43 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_tw.properties
> +dataTransfer.processor.xlsx.property.headerFontName.description=\u7b2c\u4e00\u884c\u5b57\u9ad4\u540d\u7a31
Until you're sure that you know that language, such translations are useless and tend to contain grammatical errors.

2021-09-30 09:43 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_zh.properties
> +dataTransfer.processor.xlsx.property.headerFontName.description=\u7b2c\u4e00\u884c\u5b57\u4f53\u540d\u79f0
Until you're sure that you know that language, such translations are useless and tend to contain grammatical errors.

2021-09-30 09:43 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.office/src/org/jkiss/dbeaver/data/office/export/DataExporterXLSX.java
> +        fontBold.setFontName(fontName);
What happens if you specify inexistent font? Don't you need to specify a fallback font in such cases?

It's rather a question than change request.

2021-09-30 11:56 UTC, closed without merging

2021-09-30 12:13 UTC, serge-rider commented
Wrong repository