#14599 fix NullPointerException when typing while reconnecting
dbeaver/dbeaver pull request #14649
Opened 2021-11-23 07:37 UTC by Destrolaric

2021-11-23 08:33 UTC, ShadelessFox requested changes

2021-11-23 08:33 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/DBUtils.java
> +    public static DBSObject getSelectedObject(DBCExecutionContext context)
Where did the annotation go? If it is nullable indeed, wouldn't it be better to locate the source of `null` instead of fixing the receiver?

2021-11-23 08:33 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/DBUtils.java
> +    {
Please fix formatting.

2021-11-24 08:18 UTC, LonwoLonwo approved these changes

2021-11-24 09:16 UTC, merged