#13909 add escaping support for Oracle
dbeaver/dbeaver pull request #14648
Opened 2021-11-23 05:59 UTC by Destrolaric

2021-11-23 07:01 UTC, Destrolaric commented
#13689 probably fixes this too.

2021-11-23 08:40 UTC, ShadelessFox requested changes

2021-11-23 08:40 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/model/SQLServerDataSource.java
> +                JDBCUtils.appendFilterClause(sql, databaseFilters, "name", true, new SQLServerDialect(), '\\');
There's literally a `getSQLDialect` method in the data source class.

2021-11-23 08:40 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/model/SQLServerDatabase.java
> +                JDBCUtils.appendFilterClause(sql, schemaFilters, "s.name", true, new SQLServerDialect() , '\\');
There's literally a `getSQLDialect` method in the data source class.

2021-11-23 08:40 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.mysql/src/org/jkiss/dbeaver/ext/mysql/model/MySQLDataSource.java
> +                JDBCUtils.appendFilterClause(catalogQuery, catalogFilters, MySQLConstants.COL_DATABASE_NAME, true, new MySQLDialect(), '\\');
There's literally a `getSQLDialect` method in the data source class.

2021-11-23 08:40 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.oceanbase/src/org/jkiss/dbeaver/ext/oceanbase/mysql/model/OceanbaseMySQLDataSource.java
> +                JDBCUtils.appendFilterClause(catalogQuery, catalogFilters, MySQLConstants.COL_DATABASE_NAME, true, new GenericSQLDialect(), '\\');
There's literally a `getSQLDialect` method in the data source class.

2021-11-23 08:40 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/model/OracleDataSource.java
> +                JDBCUtils.appendFilterClause(schemasQuery, schemaFilters, "U.USERNAME", false, new OracleSQLDialect(), '\\');
There's literally a `getSQLDialect` method in the data source class.

2021-11-23 08:40 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/sql/SQLDialect.java
> +
Please add proper javadocs describing what these methods do.

2021-11-23 08:40 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/sql/AbstractSQLDialect.java
> +            if (negative) sql.append(" NOT");
Please fix formatting by surrounding statement with braces.

2021-11-23 08:40 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/sql/AbstractSQLDialect.java
> +import static org.jkiss.dbeaver.model.sql.SQLUtils.makeSQLLike;
We don't use static imports. Please qualify this import.

2021-11-23 08:40 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/JDBCUtils.java
> +    public static void appendFilterClause(StringBuilder sql, DBSObjectFilter filter, String columnAlias, boolean firstClause, SQLDialect dialect, char escapedChar)
I'd suggest making `dialect` the first parameter of this method because I think it would be more logical.

2021-11-23 08:40 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreDataSource.java
> +                JDBCUtils.appendFilterClause(catalogQuery, catalogFilters, "datname", false, new PostgreDialect(), '\\');
There's literally a `getSQLDialect` method in the data source class.

2021-11-23 08:40 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreDatabase.java
> +                JDBCUtils.appendFilterClause(catalogQuery, catalogFilters, "nspname", true, new PostgreDialect(), '\\' );
There's literally a `getSQLDialect` method in the data source class.

2021-11-23 08:40 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/model/OracleSQLDialect.java
> +    }
No point in this override - method can be deleted.

2021-11-23 08:40 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/sql/AbstractSQLDialect.java
> +            sql.append(negative ? "<> ?": "=?");
I don't like the way these quote marks just appear here without telling the user about it. Let's pass a `String value` parameter to this method (no escaping required).

2021-11-23 13:41 UTC, ShadelessFox requested changes

2021-11-23 13:41 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/sql/AbstractSQLDialect.java
> +            sql.append(negative ? "<> ?": "=?");
`?` is still hardcoded (`value` should be used instead)

2021-11-24 10:46 UTC, ShadelessFox approved these changes

2021-11-26 08:34 UTC, merged