dbeaver/dbeaver-ee#1213 json document recognition improvement
dbeaver/dbeaver pull request #14923
Opened 2021-12-15 20:56 UTC by LonwoLonwo

JSON document recognition improvement

2021-12-15 21:55 UTC, ShadelessFox requested changes

2021-12-15 21:55 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/exporter/DataExporterJSON.java
> +        DBPDataKind dataKind = columns[0].getDataKind();
`columns` may be empty.

2021-12-16 07:54 UTC, ShadelessFox requested changes

2021-12-16 07:54 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/exporter/DataExporterJSON.java
> +        if (!ArrayUtils.isEmpty(columns)) {
Maybe it would be enough to extract `columns.length == 1` check here? It's marked as non-null anyway.

2021-12-16 08:18 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/exporter/DataExporterJSON.java
> +        if (!ArrayUtils.isEmpty(columns)) {
:face_with_rolling_eyes:

2021-12-16 08:22 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/exporter/DataExporterJSON.java
> +        if (!ArrayUtils.isEmpty(columns)) {
There's no point in that extra check `¯\_(ツ)_/¯`

2021-12-16 08:22 UTC, merged