#15224 add warning if failed to parse Date
dbeaver/dbeaver pull request #15232
Opened 2022-01-20 11:31 UTC by Destrolaric

2022-01-24 19:36 UTC, serge-rider commented
1. Do not use exlamation marks in messages
2. Show wrong date/tiem literal in the error message

2022-01-26 08:51 UTC, ShadelessFox requested changes

2022-01-26 08:51 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/internal/ResultSetMessages.properties
> +dialog_value_view_error_parsing_date_message = Calendar is not able to parse this value!
```suggestion
dialog_value_view_error_parsing_date_message = Calendar is not able to parse this value
```

2022-01-26 08:51 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/internal/ResultSetMessages.properties
> +dialog_value_view_error_parsing_date_message = Calendar is not able to parse this value {0}
```suggestion
dialog_value_view_error_parsing_date_message = Unable to parse value {0}
```

2022-01-26 08:51 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/data/editors/DateTimeInlineEditor.java
> +                if (!(value instanceof Date)){
```suggestion
                if (!(value instanceof Date)) {
```

2022-01-26 08:51 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/data/editors/DateTimeInlineEditor.java
> +                    UIUtils.asyncExec(() -> DBWorkbench.getPlatformUI().showWarningMessageBox(ResultSetMessages.dialog_value_view_error_parsing_date_title, NLS.bind(ResultSetMessages.dialog_value_vie
This should be an error, not a warning. See https://github.com/dbeaver/dbeaver/pull/15232#issuecomment-1020470245

2022-01-27 10:03 UTC, merged