#13691 errors to top workbench window
dbeaver/dbeaver pull request #15284
Opened 2022-01-25 14:19 UTC by Destrolaric

2022-01-25 14:28 UTC, ShadelessFox requested changes

2022-01-25 14:28 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/UIUtils.java
> +    public static Shell getTopActiveWorkbenchShell(){
```suggestion
    public static Shell getTopActiveWorkbenchShell() {
```

2022-01-25 14:28 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/UIUtils.java
> +        Shell shell = workbench.getActiveWorkbenchWindow().getShell();
Method `getActiveWorkbenchWindow` may return `null`

2022-01-25 14:28 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/UIUtils.java
> +        while (shell.getShells() != null){
```suggestion
        while (shell.getShells() != null) {
```

2022-01-25 14:28 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/UIUtils.java
> +                if (child.isVisible()){
```suggestion
                if (child.isVisible()) {
```

2022-01-25 14:28 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/UIUtils.java
> +            if (parent == shell){
```suggestion
            if (parent == shell) {
```

2022-01-25 14:28 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/UIUtils.java
> +     * see #13691
Don't describe the reason _why_ this method exists. Describe what it does instead.

2022-01-25 14:44 UTC, ShadelessFox approved these changes

2022-01-25 15:14 UTC, akilovich commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/UIUtils.java
> +    public static Shell getTopActiveWorkbenchShell() {
I'm not sure if it's a good decision to put this method here. It currently has only one usage, and UIUtils is already quite bloated.

2022-01-26 14:35 UTC, serge-rider commented
Strange behavior. It searhces for the first visible shell, not the topmost one.

2022-02-11 08:30 UTC, serge-rider commented
Let's do it differently. We need current asctive shell, not the deepest one

2022-02-11 08:30 UTC, closed without merging