#15467 fix unchecked GenericDataSourceInfo cast
dbeaver/dbeaver pull request #15478
Opened 2022-02-13 12:13 UTC by Destrolaric

2022-02-13 13:45 UTC, ShadelessFox requested changes
Please use the early return instead of surrounding the entire code block with the `if` check.

2022-02-14 07:36 UTC, LonwoLonwo approved these changes

2022-02-14 07:36 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.generic/src/org/jkiss/dbeaver/ext/generic/model/GenericExecutionContext.java
> +        if (dataSource.getInfo() instanceof GenericDataSourceInfo) {
Wrong Line! The cast is on the line above.

2022-02-14 07:38 UTC, Destrolaric commented on plugins/org.jkiss.dbeaver.ext.generic/src/org/jkiss/dbeaver/ext/generic/model/GenericExecutionContext.java
> +        if (dataSource.getInfo() instanceof GenericDataSourceInfo) {
already fixed, in last comment

2022-02-14 07:48 UTC, merged