#15167 ability to recreate table in the data transfer process added
dbeaver/dbeaver pull request #15496
Opened 2022-02-15 12:06 UTC by LonwoLonwo

![Sbawi1iUws](https://user-images.githubusercontent.com/45152336/154058981-6406761d-fbfc-4648-b6b0-8a8fd477deab.gif)

![35xatnOQHE](https://user-images.githubusercontent.com/45152336/154059012-3cff6a81-7b43-4e0c-b05a-2614306978c9.gif)

2022-02-15 12:07 UTC, LonwoLonwo commented
- [ ] Warnings
- [ ] extra columns issue

2022-02-15 20:37 UTC, LonwoLonwo commented
![2022-02-15 23_32_17-Data Transfer](https://user-images.githubusercontent.com/45152336/154145042-5ef691b9-fa40-41b0-95bb-635930447a93.png)

2022-02-16 11:00 UTC, ShadelessFox requested changes

2022-02-16 11:00 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/DTUtils.java
> +            if (DBUtils.isHiddenObject(attr)) {
What about pseudo attributes?

2022-02-16 11:00 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/DTUtils.java
> +            }
Actually, you can use `TreeSet` with a custom case-insensitive comparator `DBUtils#nameComparatorIgnoreCase` to avoid checking it manually.

2022-02-16 11:00 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseMappingAttribute.java
> +                        if (recreate) {
You can use `parent.getMappingType() == DatabaseMappingType.recreate` to avoid having this variable.

2022-02-16 11:00 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseTransferUtils.java
> +        sql.append(DBUtils.getQuotedIdentifier(dataSource, tableName));
Can we use `DBUtils#getFullQualifiedName(DBPDataSource, DBPNamedObject...)` here?

2022-02-16 12:06 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/DTUtils.java
> +            if (DBUtils.isHiddenObject(attr)) {
This is copy from method DTUtils.getAttributes(). Actually, you wrote it. You can check the importance of checking on pseudo attributes by yourself :)

2022-02-16 12:17 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/DTUtils.java
> +            if (DBUtils.isHiddenObject(attr)) {
A funny coincidence, okay.

2022-02-16 14:02 UTC, merged