dbeaver/dbeaver#15175 add new option to commandLine & add config
dbeaver/dbeaver pull request #15681
Opened 2022-03-01 13:24 UTC by Destrolaric

2022-03-01 14:12 UTC, ShadelessFox requested changes

2022-03-01 14:12 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverCommandLine.java
> +                    InputStream stream = new FileInputStream(file);
You're leaking a resource handle.

2022-03-01 14:12 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverCommandLine.java
> +                System.out.println(SystemVariablesResolver.INSTANCE.get("password"));
It shouldn't be there.

2022-03-01 14:12 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverCommandLine.java
> +                    log.error("Error parsing command line: " + e.getMessage());
Just pass the exception as a separate parameter instead of concatenating its message into a log message.

2022-03-01 14:12 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverCommandLine.java
> +    public static final String PARAM_CONFIGURATION_FILE = "D";
Why `D`? It's a reserved prefix for passing properties via CLI.

2022-03-01 14:12 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverCommandLine.java
> +        .addOption(PARAM_CONFIGURATION_FILE, "configuration-file", true, "Use configuration file")
I think that `configuration-file` is too mouthful. Can we use something shorter?

Also, the description does not describe what this option does.

2022-03-01 14:12 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/utils/SystemVariablesResolver.java
> +        INSTANCE = this;
What's the point of this assignment? The `INSTANCE` should be `final`, by the way.

Also, a private constructor would be nice to have to ensure the user will use the singleton.

2022-03-01 14:12 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/utils/SystemVariablesResolver.java
> +    public void setConfigurationFilePath(Properties configurationFile) {
We're operating over properties, not paths. Please rename both field and method to something more meaningful.

2022-03-01 15:36 UTC, ShadelessFox requested changes

2022-03-01 15:36 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/utils/SystemVariablesResolver.java
> +    }
Please fix the formatting.

2022-03-01 15:36 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/utils/SystemVariablesResolver.java
> +    private Properties configurationFile = null;
It's not a file thus it shouldn't contain a `file` in it.

2022-03-01 15:36 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/utils/SystemVariablesResolver.java
> +    public void setConfigurationFile(Properties configurationFile) {
Same as the previous comment.

2022-03-01 15:36 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverCommandLine.java
> +                try (InputStream stream = new FileInputStream(file)){
Please fix the formatting.

2022-03-01 15:36 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverCommandLine.java
> +                Properties properties = new Properties();
This variable could be placed inside the `try` block.

2022-03-01 15:36 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/controls/autorefresh/AutoRefreshControl.java
> +
Unrelated change.

2022-03-01 15:36 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/controls/autorefresh/AutoRefreshControl.java
> +    public synchronized boolean isAutoRefreshEnabled() {
Unrelated change.

2022-03-01 15:36 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/controls/autorefresh/AutoRefreshControl.java
> +        autoRefreshJob.schedule(    (long)settings.getRefreshInterval() * 1000);
Unrelated change.

2022-03-01 15:36 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverCommandLine.java
> +                    log.error("Error parsing command line: ", e);
Redundant `: ` in the message.

2022-03-01 15:36 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverCommandLine.java
> +    public static final String PARAM_CONFIGURATION_FILE = "conf";
It's a bad abbreviation either. Take a look at other applications that support a similar feature.

2022-03-01 15:36 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverCommandLine.java
> +        .addOption(PARAM_CONFIGURATION_FILE, "configuration", true, "Use configuration file for variable resolving")
This message still doesn't suggest what value it expects.

2022-03-01 15:37 UTC, ShadelessFox requested changes

2022-03-01 15:37 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/utils/SystemVariablesResolver.java
> +                }
I believe the variables from this property file have higher priority than the other variables.

2022-03-01 16:25 UTC, ShadelessFox reviewed
During the initial discussion, we've decided to use a -`Ddbeaver.secure.properties` VM variable. Why you've decided to use a CLI option instead?

2022-03-03 08:17 UTC, serge-rider commented
It can't be singleton

2022-03-03 08:17 UTC, closed without merging