#1529 Add eula confirmation dialog
dbeaver/dbeaver pull request #16063
Opened 2022-04-04 09:46 UTC by Destrolaric

On first DBeaver launch the dialog will be shown with End-user agreement. When accepted it will not be shown again. If cancelled DBeaver will be closed.

2022-04-04 12:44 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.ui.eula/META-INF/MANIFEST.MF
> +Bundle-Version: 1.0.84.qualifier
This is the first version of this bundle, so 1.0.0, not 1.0.84

2022-04-04 12:46 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.ui.eula/META-INF/MANIFEST.MF
> +Bundle-Release-Date: 20220321
I think, that release date of 22.0.3 will be better.

2022-04-04 12:47 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.ui.eula/pom.xml
> +  <version>1.0.84-SNAPSHOT</version>
Also must be 1.0.0

2022-04-04 12:53 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULAHandler.java
> +    private static void showEulaConfirmationDialog(IWorkbenchWindow window, String eula) {
You can annotations here.

2022-04-04 12:54 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULAHandler.java
> +    private static void showEulaInfoDialog(IWorkbenchWindow window, String eula) {
You can add annotations here.

2022-04-04 12:54 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULAInitializer.java
> +    @Override
\n

2022-04-04 13:24 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULAUtils.java
> +            log.error(e);
Some messages can be helpful here.

2022-04-06 08:53 UTC, ShadelessFox requested changes

2022-04-06 08:53 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULABaseDialog.java
> +    public String getEula() {
Please specify `@NotNull`/`@Nullable` annotations for the method.

2022-04-06 08:53 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULABaseDialog.java
> +    public String getEula() {
Class methods should come after constructors.

2022-04-06 08:53 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULAConfirmationDialog.java
> +    }
Can we also tweak the shell's style, so it will not show the "red cross" button?

2022-04-06 08:53 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULAConfirmationDialog.java
> +                preferences.put(DBEAVER_EULA, EULAUtils.getEulaVersion());
Consider using `DBWorkbench.getPlatform().getPreferenceStore()` instead of Java Preferences API.

2022-04-06 08:53 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULAHandler.java
> +    public static void showEula(@NotNull IWorkbenchWindow window, boolean needsConfirmation) {
Let's propagate an instance of `Shell` instead of `IWorkbenchWindow`.

2022-04-06 08:53 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULAInitializer.java
> +        if (!DBWorkbench.getPlatform().getApplication().isStandalone() || !isEulaDialogNeeded() || window.getWorkbench().getWorkbenchWindowCount() > 1) {
I believe the check for application standalone-ish is not required because you haven't enabled this plugin for the IDE product.

2022-04-06 08:53 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULAInitializer.java
> +            preferences.remove(DBEAVER_EULA);
Consider using `DBWorkbench.getPlatform().getPreferenceStore()` instead of Java Preferences API.

2022-04-06 08:53 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULAUtils.java
> +    private static final String eulaVersion = "1.0";
This can be specified in the application's descriptor.

2022-04-06 08:53 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULAUtils.java
> +    private static final String EULA_PATH = SystemVariablesResolver.getInstallPath() + File.separator + "licenses" + File.separator + "dbeaver_license.txt";
This looks dirty and error-prone. Can we specify it in the application descriptor too?

2022-04-06 08:53 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULAUtils.java
> +    public static String getEulaVersion() {
Please specify `@NotNull`/`@Nullable` annotations for the method.

2022-04-06 08:53 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.ui.eula/src/org/jkiss/dbeaver/ext/ui/eula/EULAUtils.java
> +    }
You can use `IOUtils#readToString` instead.

2022-04-07 12:03 UTC, merged