#15244 fix error notifications for script tasks
dbeaver/dbeaver pull request #16118
Opened 2022-04-07 15:29 UTC by Destrolaric

The only way to determine if that type of task had any error is to look for stderr.

2022-04-07 16:16 UTC, ShadelessFox requested changes

2022-04-07 16:16 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.tasks.native/src/org/jkiss/dbeaver/tasks/nativetool/AbstractNativeToolHandler.java
>                      }
Store the instance of the exception in this job instead.

2022-04-07 16:16 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.tasks.native/src/org/jkiss/dbeaver/tasks/nativetool/AbstractNativeToolHandler.java
> +                        error = new DBCException("Task failed, reason: " + task.getProperties().get("Error Message"));
See previous note.

2022-04-08 06:36 UTC, serge-rider commented
- Use constants but weird hardcoded "Error Message" strings.
- You can't put error message in properties. It has to be placed in a separate variable in tool handler.
- Why `Object errorMessage`? And then cast it to string 👎

2022-04-08 16:08 UTC, merged