#15950 Fix the behavior of toggle line comment
dbeaver/dbeaver pull request #16232
Opened 2022-04-19 05:31 UTC by arvillion

Fix issue #15950 

No idea how to write and where to put test cases. So I write some possible test scenarios.
Note that in case 1, the comment string(`--`) on the first line is not selected. This is the same as what VSCode will do.

1. Comment, and then the first comment string should not be selected
2. Uncomment with the first line fully selected
3. Uncomment with the first line partially selected and include the first comment string
4. Uncomment with the first line partially selected and exclude the first comment string
5. Uncomment with some intervening blank lines

2022-04-19 11:54 UTC, ShadelessFox requested changes
Thanks for the contribution!

Have you verified that the block selection mode works just fine as a regular selection?

You can enable it using the <kbd>Ctrl+Shift+A</kbd> shortcut or find it under the <kbd>Edit</kbd> menu.

2022-04-19 11:54 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.base/src/org/jkiss/dbeaver/ui/editors/text/handlers/ToggleSingleLineCommentHandler.java
> +                }
Please fix the formatting. We don't use tabs for indentation, and there's a missing space after the `if` keyword.

2022-04-19 11:54 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.base/src/org/jkiss/dbeaver/ui/editors/text/handlers/ToggleSingleLineCommentHandler.java
> +                    	}
Same as the previous comment.

2022-04-19 11:54 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.base/src/org/jkiss/dbeaver/ui/editors/text/handlers/ToggleSingleLineCommentHandler.java
> +
This extra line should not be there.

2022-04-19 15:21 UTC, arvillion commented
> Thanks for the contribution!
> 
> Have you verified that the block selection mode works just fine as a regular selection?
> 
> You can enable it using the Ctrl+Shift+A shortcut or find it under the Edit menu.

The block selection works correctly.

https://user-images.githubusercontent.com/3462292/164038339-0e0bc455-0096-4cb5-86a3-ba0757773c2a.mp4

2022-04-19 15:29 UTC, ShadelessFox approved these changes
👍🏻

2022-04-20 09:10 UTC, bianyun1981 commented
@arvillion Great work!  Thanks for your contribution.

2022-04-20 10:15 UTC, ShadelessFox commented
The pull request was removed from the milestone because its state is tracked via the linked issue.

2022-04-22 15:58 UTC, DariaMarkaryan commented
The strange behavior of the selection is still observed. Perhaps the same as you had before, I can’t watch the video attached to the PR

https://user-images.githubusercontent.com/43252954/164750911-4ec8d77a-9737-4e6f-87f1-a5f58ceb59d3.mp4

2022-04-23 00:51 UTC, arvillion commented
@DariaMarkaryan 

Well, I tried out the same selection with the same text as yours. And it just works fine.

2022-04-23 00:57 UTC, arvillion commented
@DariaMarkaryan 

Well, I tried out the same selection with the same text as yours and it just works fine. Do you mean that this problem still exist in current devel branch?

2022-04-25 13:44 UTC, Matvey16 commented
Multiple presses of Ctrl+/ will move the selecteon until it's at the end

![dbeaver_dNPklYNdQ3](https://user-images.githubusercontent.com/82543000/165101600-d8e79f78-11d3-4a4a-973a-36cba64a1929.gif)

2022-04-25 15:16 UTC, arvillion commented
@Matvey16
![8589z-cdt7s](https://user-images.githubusercontent.com/3462292/165119477-fb07bcfb-31fe-4913-a390-eaf1f83b6851.gif)

2022-04-26 10:08 UTC, ShadelessFox commented
Hello @arvillion,

I have verified that your fix is working just fine.

I believe there are some problems with our CI, especially with external PRs. We'll look into that.

2022-04-27 13:33 UTC, Matvey16 commented
Verified

2022-04-27 14:50 UTC, merged