#15322 Fix saved custom where filter reading
dbeaver/dbeaver pull request #16315
Opened 2022-04-26 12:14 UTC by E1izabeth

2022-04-26 13:03 UTC, ShadelessFox requested changes

2022-04-26 13:03 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/DataFilterRegistry.java
> +                    curSavedDataFilter.where = atts.getValue("where");
```suggestion
                    curSavedDataFilter.order = atts.getValue("order");
                    curSavedDataFilter.where = atts.getValue("where");
```

2022-04-26 13:17 UTC, ShadelessFox approved these changes

2022-04-27 09:29 UTC, uslss commented
verified

2022-04-27 10:56 UTC, merged