#16204 Append exported data to existing .sql files
dbeaver/dbeaver pull request #16310
Opened 2022-04-25 20:02 UTC by CalmaKarma

Make appending to existing files and exporting to a single file available for SQL file exporting to SQL files.
Fixed a bug [#16009](https://github.com/dbeaver/dbeaver/issues/16009), so that appending files are correctly starting new lines instead of appended to the last SQL statement of the previous files.

2022-04-26 09:56 UTC, ShadelessFox requested changes

2022-04-26 09:56 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/exporter/DataExporterSQL.java
> +        	if (rowCount > 0) {
Let's merge nested `if` into a single `else if` :^)

2022-04-26 09:56 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/exporter/DataExporterSQL.java
> +public class DataExporterSQL extends StreamExporterAbstract implements IAppendableDataExporter{
Gotha, please include space before `{`.

2022-04-26 16:27 UTC, CalmaKarma commented
I changed the whole if-else structure since there is a common `if` statement in all previous `if` branches.
That changed line of comment is by mistake. I will change it back with a commit.

2022-04-26 16:56 UTC, ShadelessFox approved these changes
👍🏻

2022-04-27 12:39 UTC, Matvey16 commented
Verified

2022-04-27 12:52 UTC, merged