Implement SQLScriptDataReceiver to enable result logging in script task
dbeaver/dbeaver pull request #16331
Opened 2022-04-27 11:45 UTC by avandorp

Currently a DB script task has a disabled option called "Dump query results to log file" (originally created for issue #3605). This commit implements SQLScriptDataReceiver in a very straightforward way to make that option working. Just scratching a personal itch, a DBeaver developer definitely should check that code.

2022-04-27 12:01 UTC, serge-rider commented
Thank you for the contribution.
Code looks ok, we will test it before merge.

Codestyle: please use spaces but tabs (1 tab = 4 spaces).

2022-04-27 12:19 UTC, ShadelessFox requested changes
Thanks for the contribution!

According to our style guide, we use four spaces instead of tabulation for indentation.

Can you please fix the formatting?

2022-04-27 12:51 UTC, avandorp commented
> According to our style guide, we use four spaces instead of tabulation for indentation.

Thanks. Applied new formatting. Would be nice if setting the formatting was part of the workspace setup at https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse. You could provide an eclipse settings file or the like.

2022-04-27 14:51 UTC, ShadelessFox approved these changes

2022-05-04 11:23 UTC, avandorp commented
Is there anything from my side needed to get this landed?

2022-05-04 12:31 UTC, ShadelessFox commented
Nope, it's pending for QA. :)

2022-05-17 14:27 UTC, merged