English GB Translation
dbeaver/dbeaver pull request #16418
Opened 2022-05-05 09:26 UTC by nzchris73

Translation of standard English US files into British English

2022-05-18 12:10 UTC, Destrolaric requested changes

2022-05-18 12:10 UTC, Destrolaric commented on product/debug/DBeaver.product.launch
> -    <setAttribute key="deselected_workspace_bundles"/>
Accidental deletion of Dbeaver.product

2022-05-18 12:15 UTC, Destrolaric requested changes

2022-05-18 12:15 UTC, Destrolaric commented on .gitignore
> -#################
And .gitignore

2022-05-25 15:24 UTC, LonwoLonwo commented
Hello @nzchris73 

Please, tell me - what's the point of this PR? Why does DBeaver need extra British translation? 
It duplicates most of our standard English translations.

2022-08-20 00:43 UTC, merged