#11291 add scroll ability to ssh dialog
dbeaver/dbeaver pull request #16638
Opened 2022-05-30 16:01 UTC by Destrolaric

2022-05-30 20:52 UTC, ShadelessFox requested changes
Please attach screenshots showing visual changes.

2022-05-30 20:52 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.net.ssh.ui/src/org/jkiss/dbeaver/ui/net/ssh/SSHTunnelConfiguratorUI.java
> +                    scrolledComposite.setMinSize(parent.computeSize(SWT.DEFAULT, SWT.DEFAULT));
I believe this must be done before resizing the shell.

2022-05-30 20:52 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.net.ssh.ui/src/org/jkiss/dbeaver/ui/net/ssh/SSHTunnelConfiguratorUI.java
> +        scrolledComposite.setExpandVertical( true );
No spaces around method arguments.

2022-05-30 20:52 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.net.ssh.ui/src/org/jkiss/dbeaver/ui/net/ssh/SSHTunnelConfiguratorUI.java
> +        final Composite composite = new Composite(scrolledComposite, SWT.NONE);
Please add an extra line to visually separate declarations.

2022-05-30 20:52 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.net.ssh.ui/src/org/jkiss/dbeaver/ui/net/ssh/SSHTunnelConfiguratorUI.java
> -
It was a spacer that forced the link widget to be at the very bottom. What's the point of this change?

2022-05-31 09:56 UTC, ShadelessFox approved these changes

2022-05-31 18:21 UTC, Matvey16 commented
Scroll bar stays active and shows empty space when settings are collapsed back
![VirtualBoxVM_bXkEmw0LXD](https://user-images.githubusercontent.com/82543000/171257761-8099b667-8714-45ac-aeca-67f5b65cd718.gif)

2022-06-02 14:58 UTC, Destrolaric commented
Scrollable composite works badly with resizeShell, it can do it vertically but not horizontally, so I hardcoded shell width.

2022-06-03 08:43 UTC, Destrolaric commented
Fully shown:
![image](https://user-images.githubusercontent.com/20579256/171820455-bf0c3531-8ba8-483c-87c4-0446b3fff797.png)
Folded: 
![image](https://user-images.githubusercontent.com/20579256/171820576-45a957b6-3b78-4b4a-92df-82806e63bc84.png)

2022-06-07 03:45 UTC, Matvey16 commented
Verified

2022-06-07 06:37 UTC, merged