#13127 fix name if not changed
dbeaver/dbeaver pull request #16746
Opened 2022-06-08 13:48 UTC by Destrolaric

2022-06-08 14:54 UTC, ShadelessFox requested changes

2022-06-08 14:54 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/connection/ConnectionPageGeneral.java
> +                    ConnectionPageGeneral.this.getContainer().updateButtons();
```suggestion
                    getContainer().updateButtons();
```

2022-06-08 14:54 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/connection/ConnectionPageGeneral.java
> +        }
1. Please don't mix `if` statements with ternary operator expressions.
2. Continuation indentation must be four spaces, not 8.

2022-06-08 15:08 UTC, ShadelessFox requested changes

2022-06-08 15:08 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/connection/ConnectionPageGeneral.java
> +            generateConnectionName(getWizard().getPageSettings(), defaultValue);
🤦🏻‍♂️

```suggestion
    final String name;

    if (connectionNameChanged) {
        name = connectionNameText.getText();
    } else if (dataSourceDescriptor != null) {
        name = dataSourceDescriptor.getName();
    } else {
        name = ModelPreferences.getPreferences().getString(ModelPreferences.DEFAULT_CONNECTION_NAME_PATTERN);
    }

    dataSource.setName(generateConnectionName(getWizard().getPageSettings(), name));
```

2022-06-09 07:51 UTC, ShadelessFox approved these changes

2022-06-14 06:00 UTC, DariaMarkaryan commented
1. project.path doesn't work
2. where does the {server} value comes from
3. we can't use {day}, {month}, {year} variables, but they should be available

2022-06-14 10:10 UTC, Matvey16 commented
Verified

2022-06-14 13:46 UTC, merged