dbeaver/dbeaver#15981 InfluxDateTimeHandler & convert influx time to …
dbeaver/dbeaver pull request #16870
Opened 2022-06-23 12:44 UTC by Destrolaric

…java date

2022-06-23 13:03 UTC, ShadelessFox requested changes

2022-06-23 13:03 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/data/formatters/DateTimeDataFormatter.java
> +    public DateFormat getDateFormat() {
Please add missing `@NotNull`/`@Nullable` annotations.

2022-06-23 13:11 UTC, ShadelessFox approved these changes

2022-07-06 13:58 UTC, uslss commented
verified

2022-07-06 14:34 UTC, merged