#16499 add ability to override pgPass hostname
dbeaver/dbeaver pull request #16874
Opened 2022-06-24 10:13 UTC by Destrolaric

![java_WYkXDUj5JR](https://user-images.githubusercontent.com/20579256/175514680-17e635b6-743f-439c-98f0-5f94927378ba.png)

2022-06-24 11:59 UTC, ShadelessFox requested changes

2022-06-24 11:59 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/AuthModelPgPass.java
> +        }
```suggestion
        String conHostName = originalConfiguration.getProviderProperty(PostgreConstants.PG_PASS_HOSTNAME);
        if (CommonUtils.isEmpty(conHostName)) {
            conHostName = configuration.getHostName();
        }
```

2022-06-24 11:59 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql.ui/src/org/jkiss/dbeaver/ext/postgresql/ui/PostgreAuthPgPassConfigurator.java
> +    protected Button overrideHostname;
Why are they `protected`?

2022-06-24 11:59 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql.ui/src/org/jkiss/dbeaver/ext/postgresql/ui/PostgreAuthPgPassConfigurator.java
>          this.usernameText.setText(CommonUtils.notEmpty(dataSource.getConnectionConfiguration().getUserName()));
Please extract connection configuration to a local variable and use `if` to avoid having this mess.

2022-06-24 12:42 UTC, ShadelessFox requested changes

2022-06-24 12:42 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql.ui/src/org/jkiss/dbeaver/ext/postgresql/ui/PostgreAuthPgPassConfigurator.java
> +        hostnameLabel = UIUtils.createLabel(authPanel, "Hostname");
```suggestion
        hostnameLabel = UIUtils.createLabel(authPanel, UIConnectionMessages.dialog_connection_pgpass_hostname);
```

2022-06-24 12:42 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql.ui/src/org/jkiss/dbeaver/ext/postgresql/ui/PostgreAuthPgPassConfigurator.java
> +        authPanel.layout();
Layout will happen automatically. What's the point?

2022-06-27 08:31 UTC, ShadelessFox approved these changes

2022-06-27 14:40 UTC, serge-rider commented
Let's use SSH tunnel target host when possible

2022-06-27 14:45 UTC, serge-rider commented
Also: instead of checkbox + label + text for custom host config use checkbox + text in a single row.

2022-06-28 10:43 UTC, Destrolaric commented
![image](https://user-images.githubusercontent.com/20579256/176160171-c513be47-4a79-4838-9ab2-6264e0724701.png)

2022-06-30 14:12 UTC, Matvey16 commented
Verified

2022-07-02 08:30 UTC, serge-rider commented
Now I completely don't understand how it works.
All you needed to do is to add host name change if there is a SSH tunnel.
+ leave custom host name where it was.

2022-08-02 14:55 UTC, LonwoLonwo approved these changes

2022-08-04 08:57 UTC, Matvey16 commented
Verified

2022-08-04 09:24 UTC, merged