#17166 tables metadata reading fixed;
dbeaver/dbeaver pull request #17170
Opened 2022-07-25 14:47 UTC by LonwoLonwo

+ Ability to edit table comments added

![2022-07-25 15_58_34-DBeaver Ultimate 22 1 3 - tables](https://user-images.githubusercontent.com/45152336/180805384-6a07598b-6208-446e-b208-cda3de6d8ede.png)

![2022-07-25 17_12_53-DBeaver Ultimate 22 1 3 - table_with_comment](https://user-images.githubusercontent.com/45152336/180805387-a7833b66-4758-4fee-b15e-f507ee44f933.png)

![2022-07-25 17_22_18-NewTable_3 - Persist Changes](https://user-images.githubusercontent.com/45152336/180805390-40ea6b0a-299c-4d6c-ada9-b4cb172accd5.png)

2022-07-25 14:54 UTC, LonwoLonwo commented
https://clickhouse.com/docs/en/sql-reference/statements/alter/comment/

https://clickhouse.com/docs/en/whats-new/changelog/2021#clickhouse-release-216-2021-06-05 about version with tables comments

2022-07-26 19:07 UTC, ShadelessFox requested changes

2022-07-26 19:07 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.clickhouse/src/org/jkiss/dbeaver/ext/clickhouse/edit/ClickhouseTableManager.java
> +    {
```suggestion
        Map<String, Object> options
    ) {
```

2022-07-29 08:39 UTC, uslss commented
verified

2022-07-29 09:39 UTC, merged