dbeaver/dbeaver-ee#1696 fix incorrect selection provider & fix mikami for VQB
dbeaver/dbeaver pull request #17290
Opened 2022-08-08 12:55 UTC by Destrolaric

2022-08-08 14:06 UTC, LonwoLonwo approved these changes

2022-08-13 15:04 UTC, ShadelessFox requested changes

2022-08-13 15:04 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/part/EntityPart.java
> +    protected boolean isVQB() {
Perhaps it should be called `isHideAttributeAssociations` and the default implementation will perform checks for `ERDUIConstants.PREF_ROUTING_TYPE` and `ERDAttributeVisibility.isHideAttributeAssociations`?

I don't think the ERD should know about the VQB in that particular context.

2022-08-15 08:43 UTC, ShadelessFox approved these changes

2022-08-17 08:57 UTC, merged