#17316 fix incorrect find resources
dbeaver/dbeaver pull request #17318
Opened 2022-08-09 15:12 UTC by Destrolaric

2022-08-09 19:13 UTC, E1izabeth approved these changes

2022-08-13 14:52 UTC, ShadelessFox requested changes
I'd use labels here to `continue` the outer loop. It took me a solid minute to figure what this logic does because 🤔

2022-08-15 08:37 UTC, ShadelessFox approved these changes

2022-08-15 15:05 UTC, Matvey16 commented
Verified

2022-08-15 15:19 UTC, merged