#16684 explain parameters added
dbeaver/dbeaver pull request #17345
Opened 2022-08-12 17:13 UTC by LonwoLonwo

![2022-08-12 20_06_34-DBeaver Ultimate 22 1 4 - _postgres_ Script-34](https://user-images.githubusercontent.com/45152336/184409741-1b202cb2-80fc-40dd-839c-c5f52c79a59d.png)

2022-08-12 17:23 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/plan/PostgreExecutionPlan.java
> +                }
IMHO it's can be written easier and more straightforward

```suggestion
                if (PostgreQueryPlaner.PARAM_COSTS.equals(key) && !CommonUtils.toBoolean(entry.getValue())) {
                    explainStat.append(",COSTS FALSE");
                } else if (PostgreQueryPlaner.PARAM_TIMING.equals(key) && !CommonUtils.toBoolean(entry.getValue())) {
                    explainStat.append(",TIMING FALSE");
                } else if (CommonUtils.toBoolean(entry.getValue())) {
                    explainStat.append(",").append(key); // In other cases we can just add parameter keyword
                }
```

2022-08-12 17:39 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/plan/PostgreExecutionPlan.java
> +            explainStat.append("EXPLAIN (FORMAT XML");
In the original issue user asked:
> I also ask you to give the opportunity to see the full query plan in the form of text, the FORMAT TEXT option

Maybe we should make FORMAT parameter too with options TEXT | XML | JSON | YAML

2022-08-12 17:53 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/plan/PostgreExecutionPlan.java
> +            explainStat.append("EXPLAIN (FORMAT XML");
Another issue could be created for this.

2022-08-13 14:54 UTC, ShadelessFox requested changes
I think it would be better to introduce an enumeration containing all possible options for the `EXPLAIN` command. This way we can construct UI elements in a loop rather than manually creating each individual one.

2022-08-31 14:58 UTC, ShadelessFox approved these changes

2022-08-31 15:56 UTC, LonwoLonwo commented
![2022-08-31 18_54_12-DBeaver Ultimate 22 2 0 - _postgres 9 6_Script-175](https://user-images.githubusercontent.com/45152336/187723900-9de75ac7-61a9-4a6e-aceb-5d78b3630964.png)

Version dependencies added - this is the window for PostgreSQL 9.6

2022-08-31 16:32 UTC, uslss commented
options from higher pg versions are trying to applied
![dbeaver_FO8yEXRXc8](https://user-images.githubusercontent.com/31996417/187731159-db500bb6-cc4f-4afc-bac9-4a3f1629e954.gif)

2022-08-31 16:52 UTC, ShadelessFox approved these changes

2022-08-31 18:17 UTC, uslss commented
verified

2022-08-31 18:45 UTC, merged