#16431 resolve driver properties
dbeaver/dbeaver pull request #17374
Opened 2022-08-17 10:29 UTC by Destrolaric

2022-08-17 11:40 UTC, E1izabeth approved these changes

2022-08-17 11:54 UTC, ShadelessFox requested changes

2022-08-17 11:54 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/runtime/properties/PropertySourceCustom.java
> +            SystemVariablesResolver.INSTANCE));
I'm suspicious about converting property values from * something * into string just to replace variables.

If variable values can only be strings, then it's better to return `Map<String, String>` instead.

2022-08-17 11:54 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.connection/src/org/jkiss/dbeaver/ui/dialogs/connection/DriverPropertiesDialogPage.java
> +                        new SystemVariablesResolver()));
See previous comment

2022-08-17 11:54 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.connection/src/org/jkiss/dbeaver/ui/dialogs/connection/DriverPropertiesDialogPage.java
> +        VariablesHintLabel variablesHintLabel = new VariablesHintLabel(ph,
Redundant variable declaration

2022-08-24 15:37 UTC, Matvey16 commented
Verified

2022-08-29 12:10 UTC, closed without merging