#16208 UUID notification
dbeaver/dbeaver pull request #17417
Opened 2022-08-22 15:24 UTC by Destrolaric

2022-08-22 15:37 UTC, ShadelessFox requested changes

2022-08-22 15:37 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreMessages.java
> +
Please replace tabs with spaces at least within new additions

2022-08-22 15:37 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreResources.properties
> +notification_org_jkiss_dbeaver_ui_actions_common_uuid_copy_text = Generated UUID value copied to the clipboard
```suggestion
notification_org_jkiss_dbeaver_ui_actions_common_uuid_copy_text = Generated UUID value was copied to the clipboard
```

2022-08-22 15:40 UTC, ShadelessFox approved these changes

2022-08-22 15:57 UTC, E1izabeth approved these changes

2022-08-24 10:52 UTC, Matvey16 commented
Verified

2022-08-24 10:55 UTC, merged