#16974 check for null, if no schemas
dbeaver/dbeaver pull request #17414
Opened 2022-08-22 12:53 UTC by Destrolaric

2022-08-22 12:58 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.generic/src/org/jkiss/dbeaver/ext/generic/model/GenericDataSource.java
> +        } else if (schemas != null && !schemas.isEmpty()) {
But isEmpty argument is nullable and checks for null
```
    public static boolean isEmpty(@Nullable Collection<?> value) {
        return value == null || value.isEmpty();
    }
```

2022-08-22 13:01 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.generic/src/org/jkiss/dbeaver/ext/generic/model/GenericDataSource.java
> +        } else if (schemas != null && !schemas.isEmpty()) {
Maybe it's better to rethink isEmpty method of the AbstractObjectCache?

2022-08-22 13:02 UTC, E1izabeth approved these changes

2022-08-22 13:05 UTC, ShadelessFox requested changes

2022-08-22 13:05 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.generic/src/org/jkiss/dbeaver/ext/generic/model/GenericDataSource.java
> +        } else if (schemas != null && !schemas.isEmpty()) {
```suggestion
        } else if (!CommonUtils.isEmpty(schemas)) {
```

2022-08-22 13:07 UTC, ShadelessFox approved these changes

2022-08-22 13:19 UTC, ShadelessFox approved these changes

2022-08-24 08:58 UTC, Matvey16 commented
Verified

2022-08-24 09:07 UTC, merged