#15196 Legacy Clickhouse uuid handling
dbeaver/dbeaver pull request #17565
Opened 2022-09-05 14:59 UTC by Destrolaric

Legacy clickhouse returns an 1111 as type code so we need to manually set the handler

2022-09-05 16:25 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.clickhouse/src/org/jkiss/dbeaver/ext/clickhouse/model/data/ClickhouseValueHandlerProvider.java
> +            return JDBCObjectValueHandler.INSTANCE;
Any specific reason to not use JDBCUUIDValueHandler?

2022-09-06 10:48 UTC, LonwoLonwo approved these changes

2022-09-06 10:50 UTC, LonwoLonwo requested changes

2022-09-06 10:50 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.clickhouse/src/org/jkiss/dbeaver/ext/clickhouse/model/data/ClickhouseValueHandlerProvider.java
> +        } else if ("uuid".equalsIgnoreCase(lowerTypeName)) {
You do not need equalsIgnoreCase here, you already have lower Type Name

2022-09-06 20:04 UTC, LonwoLonwo approved these changes

2022-09-08 09:33 UTC, Matvey16 commented
Verified

2022-09-12 09:35 UTC, merged