#16626 Fix remote host identifier changed dialog for jsch
dbeaver/dbeaver pull request #17575
Opened 2022-09-06 16:40 UTC by E1izabeth

_**How to check:**_

0. Run DBeaver
1. Choose the database
2. Open some script for the chosen database and enable setting to connect to the database on script opening
3. Turn on Tip of the day
4. Shutdown DBeaver
3. Change a couple of symbols of the key for the host of the chosen database in .ssh/known_hosts file
5. Run DBeaver
6. Wait for the Tip of the day and ssh message about changed host identifier. SSH Message will grab focus.
7. After clicking on the tip of the day modal window the SSH Message window should not be hidden.

2022-09-07 04:47 UTC, ShadelessFox requested changes

2022-09-07 04:47 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.net.ssh.ui/src/org/jkiss/dbeaver/ui/net/ssh/SSHUIMessages.properties
> +}
```suggestion
```

2022-09-07 08:51 UTC, ShadelessFox approved these changes

2022-09-16 12:08 UTC, Matvey16 commented
Verified

2022-09-18 21:56 UTC, merged