#17479 add datetime64 support
dbeaver/dbeaver pull request #17645
Opened 2022-09-14 10:29 UTC by Destrolaric

2022-09-14 10:46 UTC, E1izabeth requested changes

2022-09-14 10:46 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/data/formatters/DateTimeDataFormatter.java
> +        dateTimeFormatter = DateTimeFormatter.ofPattern(java8DatePattern);
It looks like a copy paste from `init` method. Maybe it's better to use `init` instead of creating such a strange "setter".

2022-09-14 10:54 UTC, E1izabeth commented
I don't think that we need `setPattern` at all.

2022-09-14 11:11 UTC, ShadelessFox requested changes
By manually setting the pattern, you're effectively ignoring one set by the user. This is bad and we don't want to do that.

Just let the user configure the pattern of their choice.

2022-09-15 10:45 UTC, ShadelessFox approved these changes
This is better.

2022-09-15 10:45 UTC, E1izabeth approved these changes

2022-09-18 17:14 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.clickhouse/plugin.xml
> +                    <property name="@dbeaver-default-dataformat.type.timestamp.pattern" value="yyyy-MM-dd HH:mm:ss[.fffffffff]"/>
Please bring back line separator

2022-09-19 07:45 UTC, E1izabeth approved these changes

2022-09-19 07:47 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.clickhouse/plugin.xml
> +                    <property name="@dbeaver-default-dataformat.type.timestamp.pattern" value="yyyy-MM-dd HH:mm:ss[.fffffffff]"/>
Whatever

2022-09-19 07:47 UTC, ShadelessFox approved these changes

2022-09-27 14:43 UTC, Matvey16 commented
Any timestamp column is now set to NULL if you try to add or change milliseconds

![dbeaver_wHs6lb79CJ](https://user-images.githubusercontent.com/82543000/192558214-7fcb5fa7-a17d-479c-9d43-f9d6b867ca0a.gif)

2022-10-04 12:04 UTC, E1izabeth commented on bundles/org.jkiss.utils/src/org/jkiss/utils/time/ExtendedDateFormat.java
> +            index += nanoPrefix.length();
`nanoPrefix` can be null as I see

2022-10-04 12:07 UTC, Destrolaric commented on bundles/org.jkiss.utils/src/org/jkiss/utils/time/ExtendedDateFormat.java
> +            index += nanoPrefix.length();
fixed

2022-10-04 12:16 UTC, ShadelessFox submitted a review, later dismissed

2022-10-04 12:16 UTC, ShadelessFox commented on bundles/org.jkiss.utils/src/org/jkiss/utils/time/ExtendedDateFormat.java
> +                for (int k = MAX_NANO_LENGTH - i; k > 0; k--) {digit *= 10;
?

2022-10-04 12:27 UTC, Destrolaric commented on bundles/org.jkiss.utils/src/org/jkiss/utils/time/ExtendedDateFormat.java
> +                for (int k = MAX_NANO_LENGTH - i; k > 0; k--) {digit *= 10;
accidentally formatted, fixed

2022-10-04 12:32 UTC, E1izabeth approved these changes

2022-10-05 06:14 UTC, Matvey16 commented
Verified

2022-10-05 12:30 UTC, merged