#16440 Include description column when exporting as XLSX
dbeaver/dbeaver pull request #17896
Opened 2022-10-12 14:05 UTC by ShadelessFox

2022-10-12 17:17 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_pt_BR.properties
> +dataTransfer.processor.xlsx.property.headerFont.name=Fonte da linha do cabe�alho
cabeï¿½alho - it looks strange. Is it expected?

2022-10-12 19:27 UTC, E1izabeth requested changes

2022-10-12 19:27 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_pt_BR.properties
> +dataTransfer.processor.xlsx.property.dateFormat.description=Formato de excel e datas (e.x. m/d/yy hh:mm) vo�e pode mudar no excel.
This and mentioned by Asya line seems accidentally modified. Please, return it back.

2022-10-12 20:53 UTC, E1izabeth approved these changes

2022-10-13 06:35 UTC, LonwoLonwo approved these changes

2022-10-13 11:22 UTC, uslss commented
in case not all of the columns had description, but only description is chosen in export settings, columns without descriptions are incorrectly shown in excel
![image](https://user-images.githubusercontent.com/31996417/195583410-04b2047d-d036-4268-844b-77a78eb7ab4e.png)

at the same time if none header format is chosen column width is set more correctly
![image](https://user-images.githubusercontent.com/31996417/195583686-24ddbe27-f576-41d2-a87e-1eb329c39553.png)

2022-10-19 10:55 UTC, DariaMarkaryan commented
no header is added when we export with description as header and at least one of these settings checked 
![image](https://user-images.githubusercontent.com/43252954/196672021-0dfeba07-9637-4564-86ce-bcadc8e98441.png)

2022-10-22 22:37 UTC, merged