#9980 dotted frame to selected item in the tree added
dbeaver/dbeaver pull request #17931
Opened 2022-10-14 20:44 UTC by plotn

2022-10-14 21:49 UTC, ShadelessFox commented
Hello @plotn,

Thanks for the contribution. Can you please attach a screenshot showing the change?

2022-10-15 08:12 UTC, plotn commented
Yes, sure: 

![image](https://user-images.githubusercontent.com/11477081/195976615-73ea720e-ed4c-42e1-8c31-7415099c84b8.png)

2022-10-15 10:21 UTC, ShadelessFox commented
How will it behave with multi-selection?

2022-10-15 10:30 UTC, plotn commented
Like this:

![image](https://user-images.githubusercontent.com/11477081/195981670-376a0c8c-4a71-4a34-be63-f81292b6bc73.png)

2022-10-15 10:41 UTC, ShadelessFox commented
Not sure if I like the way it blends in-between, but okay. Should be tested on other platforms.

2022-10-15 10:42 UTC, ShadelessFox requested changes

2022-10-15 10:42 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/database/DefaultNavigatorNodeRenderer.java
> +                Display.getDefault().getSystemColor(SWT.COLOR_BLACK));
```suggestion
            gc.setForeground(Display.getDefault().getSystemColor(UIStyles.isDarkTheme() ? SWT.COLOR_WHITE : SWT.COLOR_BLACK))
```

2022-10-15 10:42 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/database/DefaultNavigatorNodeRenderer.java
> +            gc.drawLine(event.x - 1, event.y + event.height - 1, event.x + event.width - 1, event.y + event.height - 1);
I believe it can be replaced with a single `drawRectangle` call.

2022-10-17 08:49 UTC, ShadelessFox approved these changes

2022-10-17 11:17 UTC, E1izabeth approved these changes

2022-10-26 13:03 UTC, serge-rider commented
I'm not sure. 
Do we really need this? 
I mean selection is already highlighted. What the point in adding extra highlighting?

2022-10-26 13:21 UTC, plotn commented
> I'm not sure. Do we really need this? I mean selection is already highlighted. What the point in adding extra highlighting?

Hi! See the initial issue please. It is because of "coloured" connections, that "highlighted" too

2022-11-18 14:43 UTC, ghYura commented
Do dots can move like ants dynamically?
_By the way, **any** dynamic representation in GUI should be adjusted via customisation dynamic/static extended menu adjustments (since some one doesn't like constantly blinking in the eyes, other one - would like to have constantly self-telling item being depictured)_ 

> (**to Dev-n-test team**: 
> would you like to have separate FR for this additional abstract comprehensive dynamicVSstatic customizable menu feature, that should be liked by users? Any additional FR regarding new feature representation of any new item for its depicture mode, could be added as its dynamic-static behavior and this menu could be extended each time)
> @serge-rider 
> @ShadelessFox

2022-11-18 15:53 UTC, ShadelessFox commented
I'm unaware of any GUI application that does that (except for graphical editors, which DBeaver is not).

In general, the selection is visualized by static dotted lines.

2022-11-18 17:45 UTC, ghYura commented
> I'm unaware of any GUI application that does that (except for graphical editors, which DBeaver is not).
> 
> In general, the selection is visualized by static dotted lines.

Maybe, additional transparent non-interactive layer in drawing output, but binded with dynamic areas to corresponding underlying item(s) with constant watch of presense of corresponding element to be dynamically visualized

2022-11-18 19:42 UTC, plotn commented
>be the first one pioneer

Excel does ) so cannot be first )

2023-01-24 14:16 UTC, E1izabeth commented
We don't want to add dotted frame for selected item. It brings noise into UI.

2023-01-24 14:16 UTC, closed without merging