#9444 tree filter allow "schema.object" syntax
dbeaver/dbeaver pull request #17930
Opened 2022-10-14 18:58 UTC by plotn

2022-11-01 11:57 UTC, E1izabeth commented
I'd refactor it. Maybe we can extract some parts of code to methods. It's hard to read now and method `isElementVisible` became too long.

2022-11-03 01:28 UTC, serge-rider requested changes

2022-11-03 01:28 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/database/DatabaseNavigatorTree.java
> +        private boolean hasDotPattern = false;
hasDotPattern is redundant. We can use `dotPattern != null` instead.

2022-11-03 01:28 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/database/DatabaseNavigatorTree.java
> +            String labelText = ((ILabelProvider) ((ContentViewer) viewer).getLabelProvider()).getText(element);
I'd move the code below to a separate function.
Otherwise `isElementVisible` is super-long and hard to understand..

2022-11-03 01:28 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/database/DatabaseNavigatorTree.java
> +                    Object obj = ((DBNDatabaseItem) element).getObject();
getObject always returns DBSObject. What the point of additonal instanceof + case?

2022-11-08 22:48 UTC, serge-rider approved these changes

2022-11-10 13:54 UTC, merged