#15352 Add hint for database field on the connection page for PostgreSQL
dbeaver/dbeaver pull request #18035
Opened 2022-10-25 15:28 UTC by E1izabeth

![image](https://user-images.githubusercontent.com/28875055/197815599-4a937532-970b-47ad-9cd3-40fb87a6f941.png)

By default we set database and user name to dvdrental, so user will see this hint only if they intentionally deletes the text from this field.

2022-10-25 15:31 UTC, Destrolaric commented
If possible, it's better to show the current value of the username text box instead.

2022-10-25 15:46 UTC, E1izabeth commented
1) username field could be empty too
2) it require some refactoring: at least I need access to the username field of auth model configurator and the method to add TextListener to this field from the postgresql connection page. I find this solution cumbersome for such a task. In addition, it loses the useless if the username field is empty too.

2022-10-25 15:49 UTC, Destrolaric requested changes

2022-10-25 15:49 UTC, Destrolaric commented on plugins/org.jkiss.dbeaver.ext.postgresql.ui/src/org/jkiss/dbeaver/ext/postgresql/PostgresResources.properties
> +dialog_database_name_hint = equals to username if not specified
Probably 
`Uses username if not specified`
is better

2022-10-25 15:50 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.postgresql.ui/src/org/jkiss/dbeaver/ext/postgresql/PostgresResources.properties
> +dialog_database_name_hint = equals to username if not specified
yeah, maybe

2022-10-26 08:30 UTC, DariaMarkaryan commented
Verified

2022-10-26 08:31 UTC, Destrolaric approved these changes

2022-10-26 12:07 UTC, merged