#2316 Tab autocompletion
dbeaver/dbeaver pull request #18146
Opened 2022-11-08 09:44 UTC by E1izabeth

It's the only working hack I found.
With the current dirty hack autocompletion choice will work by both tab and enter.

2022-11-08 13:25 UTC, serge-rider requested changes

2022-11-08 13:25 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditorSourceViewer.java
> +                        if (event.character == '\t') {
Lets make it configurable

2022-11-08 16:09 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditorSourceViewer.java
> +                        if (event.character == '\t') {
![image](https://user-images.githubusercontent.com/28875055/200616529-549f7d3f-68d2-4441-9c08-49d6d0ab100e.png)

2022-11-10 10:29 UTC, uslss commented
verified

2022-11-10 13:34 UTC, serge-rider approved these changes

2022-11-10 13:35 UTC, merged