17554-Fix-for-MySQL-username-with-proper-back-quotes
dbeaver/dbeaver pull request #18228
Opened 2022-11-16 01:22 UTC by amargulaganji

Fix for MySQL username isn't with proper back quotes when dragging/copying to SQL editor #17554

[#17554](https://github.com/dbeaver/dbeaver/issues/17554)

![17554-Test](https://user-images.githubusercontent.com/38907593/202059668-847c0314-21f7-49e5-aa16-cdea9495cea6.gif)

2022-11-16 21:05 UTC, LonwoLonwo commented
Hello @amargulaganji 
Thanks for the contribution.
Yes, your fix helps with user's names.
But `quoteIdentifier` is a base method. What if `str` will be a table name? Like `R@se`? Or column name? Or catalog name? With symbol @ inside.

2022-11-17 07:46 UTC, amargulaganji commented
Hi @LonwoLonwo,
Thank you for your observation.
As you noticed, changes to `quoteIdentifier` method will affect the table and column names.
So removed changes from `quoteIdentifier`. Made changes that will make difference to the user's name only.

Test Result:
![Test-user-table-column-name](https://user-images.githubusercontent.com/38907593/202386408-f8309722-2e79-40ce-8df3-215388da7047.gif)

2022-11-17 11:09 UTC, LonwoLonwo commented
That's better.

![2022-11-17 14_04_37-DBeaver 22 2 5 - _localhost 3_ Script-22](https://user-images.githubusercontent.com/45152336/202430564-ec1e5661-7ed9-4b56-9f24-afc0f0d6984e.png)

But now the user's list looks something like this. Strange that I can't see it on your video.

2022-11-18 23:21 UTC, amargulaganji commented
@LonwoLonwo Fixed UI. Please check now.

Test Result :
![Test-username-ui](https://user-images.githubusercontent.com/38907593/202818653-4754b066-1efd-4289-a334-a345b2a75164.gif)

2022-11-21 10:33 UTC, LonwoLonwo commented
Oh, no :( You can not fix local problem on the general level

2022-12-02 16:01 UTC, ShadelessFox requested changes
We don't want to handle such a weird case on the top level.

Instead, just implement the `DBPQualifiedObject` interface for the `MySQLUser` class.

2022-12-02 20:16 UTC, amargulaganji commented
Thank you @ShadelessFox  for your suggestion. It helped me to fix the issue locally.

Please review my changes.

Test Result:
![17554-Test-Result](https://user-images.githubusercontent.com/38907593/205377994-d3619919-1e70-40c2-b4ed-766c371fe9fa.gif)

2022-12-06 10:57 UTC, ShadelessFox requested changes

2022-12-06 10:57 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.mysql/src/org/jkiss/dbeaver/ext/mysql/model/MySQLUser.java
> +        return "`" + userName + "`@`" + host + "`";
The `userName` might contain backquotes, please use `DBUtils#getQuotedIdentifier` with `quoteAlways` set to `true`

2022-12-06 15:28 UTC, ShadelessFox approved these changes

2022-12-06 15:30 UTC, E1izabeth approved these changes

2022-12-09 06:22 UTC, amargulaganji commented
Hi @LonwoLonwo , Could you please review and merge?

2022-12-09 06:34 UTC, E1izabeth commented
@amargulaganji your PR is waiting for testing.

2022-12-15 16:32 UTC, Matvey16 commented
Verified

2022-12-16 10:17 UTC, merged