#16197 add table column tip proposal info
dbeaver/dbeaver pull request #18297
Opened 2022-11-22 15:00 UTC by Destrolaric

Closes #16197  
Look acceptance at criterias

https://user-images.githubusercontent.com/20579256/203347135-9b18b299-a827-43bc-8808-3433146af84d.mp4

2022-11-22 15:21 UTC, ShadelessFox requested changes

2022-11-22 15:21 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/completion/SQLCompletionHelper.java
> +        DBPNamedObject object, final String[] keywords, final DBPKeywordType keywordType) {
Please stop wrapping like that. You have to wrap each parameter, with the closing paren `)` at the new line.

2022-11-22 15:21 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/completion/SQLCompletionProposalBase.java
> +        this.additionalProposalInfo = (DBSObject) object;
Pointless cast

2022-11-22 15:21 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/DBInfoUtils.java
> +    public static String getPropertyString(PropertyCollector collector, DBPPropertyDescriptor descriptor) {
Please specify nullability annotations for the method's parameters.

2022-11-22 15:21 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                targetObject = ((DBSObjectReference) input).resolveObject(new VoidProgressMonitor());
Is it safe to use a void monitor here? Is the reference already resolved so that it won't block?

2022-11-22 15:21 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/syntax/SQLCompletionProposal.java
> +        return this.getReplacementString();
```suggestion
        return getReplacementString();
```

2022-11-22 15:21 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +        this.boldFont = fontDescriptor.setStyle(SWT.BOLD).createFont(parent.getDisplay());
You have to dispose it when the control disposes

2022-11-22 15:21 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +            );
```suggestion
            Text valueText = new Text(placeholder, SWT.READ_ONLY);
```

2022-11-22 15:21 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +            }
Can be moved out of the `try` block

2022-11-22 15:21 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                    DBNNode[] folderChildren = child.getChildren(new VoidProgressMonitor());
Same as previous comment about void monitors

2022-11-22 15:21 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +        for (DBNNode child : node.getChildren(new VoidProgressMonitor())) {
Same as previous comment about void monitors

2022-11-22 15:22 UTC, ShadelessFox commented
Generally speaking, I really like how it turned out.

2022-11-22 15:43 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +        GridData tableGridData = new GridData(GridData.FILL_BOTH);
tableGridData == mainGridData

2022-11-22 15:45 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                log.error(e);
Please, add a message to the log.

2022-11-22 15:46 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +            log.error(e);
Please, add a message to the log.

2022-11-22 18:11 UTC, ShadelessFox requested changes

2022-11-22 18:11 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                    columnNodes = getColumnNodes(monitor, node);
```suggestion
                    Collection<DBNNode> columnNodes = getColumnNodes(monitor, node);
```

2022-11-22 18:11 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                    });
No. Add job change listener and move this code there to be executed on completion. After that, IIRC, you wouldn't even need the `asyncExec` here.

2022-11-22 18:11 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                    return Status.CANCEL_STATUS;
Please don't suppress errors. Use `GeneralUtils#makeExceptionStatus`

If you believe that we should not show the thrown exception, then at least log it and write what went wrong.

2022-11-22 18:11 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                        ItemListControl itemListControl = new ItemListControl(
It looks a bit weird. Can we create the control outside this job and populate it later once it finishes?

2022-11-24 11:07 UTC, ShadelessFox requested changes

2022-11-24 11:07 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/completion/SQLCompletionHelper.java
> +        final DBPKeywordType keywordType
I'd really like to clean up these by adding nullability annotations and removing redundant `final` modifiers.

2022-11-24 11:07 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/completion/SQLCompletionProposalBase.java
> +        if (additionalProposalInfo == null && object == null) {
Is this supposed to be `object != null` instead? You're passing this `object` later on, but it's always `null`.

2022-11-24 11:07 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/DBInfoUtils.java
> +     * Returns descriptor value as a string type, or returns NULL
```suggestion
     * Returns a string representation of the property's value or {@code null} if it has no value.
```

2022-11-24 11:07 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +        resolveObject.addJobChangeListener(new JobChangeAdapter(){
```suggestion
        resolveObject.addJobChangeListener(new JobChangeAdapter() {
```

2022-11-24 11:07 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                if (event.getResult() == Status.OK_STATUS) {
Let's invert it and make it `return` early on to avoid so much nesting going on

2022-11-24 11:07 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                        return Status.OK_STATUS;
Redundant `return` statement

2022-11-24 11:07 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                    itemListControl.appendListData((Collection<DBNNode>) columnNodes[0]);
Please at least suppress unchecked cast here

2022-11-24 11:07 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +        DBRProgressMonitor monitor, @Nullable DBNNode node
Like talking to a wall.

```suggestion
        @NotNull DBRProgressMonitor monitor,
        @Nullable DBNNode node
```

2022-11-24 11:12 UTC, Destrolaric commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/completion/SQLCompletionProposalBase.java
> +        if (additionalProposalInfo == null && object == null) {
No, it's supposed to be called only for keywords, but it still has the functionality to be called for DBSObjects(to use in different parts of DBeaver). Probably we should use `return object != null ? object : additionalProposalInfo` in the return to make it cleared.

2022-11-24 11:52 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/completion/SQLCompletionProposalBase.java
> +        if (additionalProposalInfo == null && object == null) {
Yes, please refactor it in a clearer way, if possible.

2022-11-28 15:42 UTC, ShadelessFox requested changes
The idea was to annotate properties we are interested in by setting their `Property#id` and filtering according to the set IDs.

2022-11-28 15:42 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/itemlist/ObjectListControl.java
> +    public ViewerColumnController<ObjectColumn, Object> getColumnController() {
Please specify nullability annotations for the method's return type.

2022-11-28 15:42 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                        }
What is this code supposed to do?

2022-11-28 17:29 UTC, ShadelessFox requested changes

2022-11-28 17:29 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                            itemListControl.setIsColumnVisibleById("description", true); //NON-NLS-1
Can we put them in an array and iterate over it?

2022-11-28 17:29 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                            itemListControl.dispose();
Why do we need to dispose it here? It still has visuals, such as columns, etc. Just having a blank window is not better.

2022-11-28 17:29 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/dialogs/SuggestionInformationControl.java
> +                            }
Actually, we can create a set of visible columns and iterate over all columns while checking their IDs against visible ones to determine whether we want to leave them visible or not.

2022-11-29 16:39 UTC, Matvey16 commented
Verified

2022-11-29 16:50 UTC, ShadelessFox approved these changes

2022-11-29 17:31 UTC, merged