#18205 Prevent the endless growth of dbeaver-debug.log file
dbeaver/dbeaver pull request #18389
Opened 2022-11-30 11:16 UTC by E1izabeth

2022-12-02 16:14 UTC, ShadelessFox requested changes

2022-12-02 16:14 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/preferences/PrefPageErrorLogs.java
> +            long bigScriptSize = DBWorkbench.getPlatform().getPreferenceStore().getLong(LogOutputStream.LOGS_MAX_FILE_SIZE);
Let's extract the common `DBWorkbench.getPlatform().getPreferenceStore()` part and inline these variables in other places

2022-12-02 16:14 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/preferences/PrefPageErrorLogs.java
> +        store.setValue(LogOutputStream.LOGS_MAX_FILE_SIZE, logFilesMaxSizeSpinner.getSelection() * 1024l);
```suggestion
        store.setValue(LogOutputStream.LOGS_MAX_FILE_SIZE, logFilesMaxSizeSpinner.getSelection() * 1024L);
```

2022-12-02 16:14 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/LogOutputStream.java
> +import org.jkiss.dbeaver.runtime.DBWorkbench;
These should come before Java imports

2022-12-02 16:14 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/LogOutputStream.java
> +                "Failed to initialize debug log output due to the target is not a file: " + debugLogFile.getAbsolutePath()
```suggestion
                "Failed to initialize debug log output due to the target not being a file: " + debugLogFile.getAbsolutePath()
```

2022-12-02 16:14 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/LogOutputStream.java
> +        this.prefStore = DBWorkbench.getPlatform().getPreferenceStore();
This field is not used outside the constructor. Can it be a local variable instead?

Or maybe you wanted to remove the property change listener from it in the `close` method?

2022-12-02 16:14 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverApplication.java
> +//        }
Looks redundant now, can we delete it?

2022-12-02 17:47 UTC, ShadelessFox approved these changes

2022-12-06 10:08 UTC, Destrolaric approved these changes

2022-12-08 12:57 UTC, DariaMarkaryan commented
Verified

2022-12-13 11:35 UTC, Matvey16 commented
Verified

2022-12-15 07:53 UTC, merged