dbeaver/pro#1297 Always trust `localhost` when connecting through SSH
dbeaver/dbeaver pull request #18590
Opened 2022-12-26 03:02 UTC by ShadelessFox

2022-12-26 08:32 UTC, LonwoLonwo approved these changes

2022-12-26 09:11 UTC, E1izabeth approved these changes

2022-12-28 18:50 UTC, Matvey16 commented
It is still reproducible to me for SSHJ connections

![dbeaver_KglcDRe6Fk](https://user-images.githubusercontent.com/82543000/209858794-9dac6889-3071-4bde-9754-9ae08b7b4651.png)

2022-12-28 23:40 UTC, E1izabeth requested changes
May be it is not a good idea actually, because it will be unrecognizable if local ports would be unintentionally mapped to some 3rd-party host by other applications, thus guiding our connection to the unwanted destination. The correct solution seems to be the substitution of the localhost with the target host name during the fingerprint validation, so that the fingerprint of the intended remote host would be correctly matched by the existing validation algorithm.

2022-12-29 09:29 UTC, E1izabeth commented
Also currently we verify jump server host identity, but doesn't verify ssh target host identity - we are trying to verify it's fingerprint with localhost which is not correct. Skip host key verification when the host is localhost is bad, because then we're not checking target host at all.

The correct solution is still substitution of the localhost with the target host name during the fingerprint validation. It can be done by overriding verifyKey method for sshj and setting hostAlias for jsch.

2022-12-30 19:22 UTC, E1izabeth requested changes

2022-12-30 19:22 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.net.ssh.sshj/src/org/jkiss/dbeaver/model/net/ssh/KnownHostsVerifier.java
> +        }
```suggestion
    @Override
    public boolean verify(String hostname, int port, PublicKey key) {
        if (hostname.equals(DBConstants.HOST_LOCALHOST)) {
            return super.verify(actualHostConfiguration.getHostname(), actualHostConfiguration.getPort(), key);
        } else {
            return super.verify(hostname, port, key);
        }
    }
    
    @Override
    public List<String> findExistingAlgorithms(String hostname, int port) {
        if (localEndPointTargetHostName != null && hostname.equalsIgnoreCase(DBConstants.HOST_LOCALHOST)) {
            return super.findExistingAlgorithms(actualHostConfiguration.getHostname(), actualHostConfiguration.getPort());
        } else {
            return super.findExistingAlgorithms(hostname, port);
        }
    }
        
        
```

2022-12-30 19:22 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.net.ssh.ui/src/org/jkiss/dbeaver/ui/net/ssh/jsch/JSCHUIPromptProvider.java
> +            // HACK: There's a bug in JSCH: in the message, it includes the original hostname instead of its alias
Also `showMessage(String message)` should be corrected to fix the message.

2022-12-30 19:25 UTC, E1izabeth commented
Also I've found alive jsch repository https://github.com/mwiede/jsch. Maybe we could migrate to it. (For discussion)

2022-12-30 20:03 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.net.ssh.ui/src/org/jkiss/dbeaver/ui/net/ssh/jsch/JSCHUIPromptProvider.java
> +            // HACK: There's a bug in JSCH: in the message, it includes the original hostname instead of its alias
The `showMessage` is used for debug logging. Do we really care about it? I haven't seen it popping up in my console.

2022-12-30 20:05 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.net.ssh.sshj/src/org/jkiss/dbeaver/model/net/ssh/KnownHostsVerifier.java
> +        }
And also in literally every other method of the `OpenSSHKnownHosts` class 😞

2022-12-30 20:24 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.net.ssh.ui/src/org/jkiss/dbeaver/ui/net/ssh/jsch/JSCHUIPromptProvider.java
> +            // HACK: There's a bug in JSCH: in the message, it includes the original hostname instead of its alias
I guess it could write to debug log incorrect message too.

2022-12-30 20:24 UTC, E1izabeth approved these changes

2022-12-30 21:27 UTC, ShadelessFox commented
The migration is possible, yet the fork still has the same issue regarding confirmation messages: https://github.com/mwiede/jsch/pull/257

2022-12-30 21:30 UTC, E1izabeth commented
Yeah, I see. But we could contribute here and it's supported.

2022-12-30 21:35 UTC, ShadelessFox commented
I did, in fact. It's not a blocker by any means. We can migrate at any time and eliminate the hack on our side.

2022-12-30 21:40 UTC, E1izabeth commented
I'm not sure about the host alias semantics actually. Maybe the correct fix is not to replace `host `to `chost`, but show both of them or check host alas existence first. (Just my thoughts to think about).

2023-01-04 11:09 UTC, LonwoLonwo approved these changes

2023-01-05 10:06 UTC, Matvey16 commented
Verified

2023-01-05 13:27 UTC, merged