#18737 Fix confirmation message about closing unpinned tabs
dbeaver/dbeaver pull request #18745
Opened 2023-01-11 16:45 UTC by E1izabeth

The message was fixed.

2023-01-11 20:54 UTC, ShadelessFox requested changes
Please make sure that other calls to the `confirmAction` method don't have the same mistake

2023-01-11 20:54 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditor.java
>                      tabsToClose.size(), SQLPreferenceConstants.CONFIRM_RESULT_TABS_CLOSE,
The `tabsToClose.size()` should be the icon of the confirmation dialog

2023-01-12 08:03 UTC, LonwoLonwo approved these changes

2023-01-12 08:45 UTC, ShadelessFox approved these changes

2023-01-12 12:41 UTC, Matvey16 commented
Verified

2023-01-12 13:11 UTC, merged