CB-1577-H2-driver-update
dbeaver/dbeaver pull request #19380
Opened 2023-03-15 16:12 UTC by EmYar

2023-03-15 16:20 UTC, ShadelessFox commented
AFAIK you're not supposed to bump versions of plugins that are shipped with DBeaver.

It makes sense for plugins installed separately so that Eclipse can figure out that they were updated.

2023-03-15 16:41 UTC, serge-rider requested changes

2023-03-15 16:41 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.h2/META-INF/MANIFEST.MF
> +Bundle-Version: 1.0.157.qualifier
Please don't change bundle version manually

2023-03-15 16:41 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.h2/pom.xml
> +  <version>1.0.157-SNAPSHOT</version>
The same

2023-03-20 12:09 UTC, EmYar commented on plugins/org.jkiss.dbeaver.ext.h2/META-INF/MANIFEST.MF
> +Bundle-Version: 1.0.157.qualifier
Change reverted

2023-03-20 12:09 UTC, EmYar commented on plugins/org.jkiss.dbeaver.ext.h2/pom.xml
> +  <version>1.0.157-SNAPSHOT</version>
Change reverted

2023-03-20 13:10 UTC, ShadelessFox approved these changes

2023-03-21 17:45 UTC, ShadelessFox commented on bundles/org.jkiss.utils/src/org/jkiss/utils/CommonUtils.java
> +    public static String replaceLast(@NotNull String string, @NotNull String toReplace, @NotNull String replacement) {
Why is it here? Bad merge commit?

2023-03-22 14:18 UTC, EmYar commented on bundles/org.jkiss.utils/src/org/jkiss/utils/CommonUtils.java
> +    public static String replaceLast(@NotNull String string, @NotNull String toReplace, @NotNull String replacement) {
This is a utility method for String used by the H2 migrator. Is this not the right place for it?

2023-03-22 14:20 UTC, ShadelessFox commented on bundles/org.jkiss.utils/src/org/jkiss/utils/CommonUtils.java
> +    public static String replaceLast(@NotNull String string, @NotNull String toReplace, @NotNull String replacement) {
Yes, since it's not used anywhere in this PR.

2023-04-04 11:37 UTC, serge-rider approved these changes

2023-04-04 11:44 UTC, merged