#19418 ability to drop generic triggers via UI added
dbeaver/dbeaver pull request #19448
Opened 2023-03-22 11:09 UTC by LonwoLonwo

DROP statement is already implemented in SQLTriggerManager

![2023-03-22 13_24_40-Window](https://user-images.githubusercontent.com/45152336/226885475-344b2345-6f4b-4d81-b078-2c4c612b2319.png)

Please check the following:

- [ ] trigger can be deleted in
- [x] SQLite
- [x] Firebird (database and table triggers)
- [x] HSQL
- [x] Informix/HANA
- [x] trigger can not be created in Generic databases

in EE

- [x] ability to drop trigger in Teradata
- [x] ability to rename trigger in Teradata
- [x] ability to add comment to trigger in Teradata

2023-03-22 11:56 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.firebird/src/org/jkiss/dbeaver/ext/firebird/model/FireBirdDatabaseTrigger.java
> +            this);
```suggestion
        return DBUtils.getFullQualifiedName(getDataSource(), this);
```

2023-03-22 11:56 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.firebird/src/org/jkiss/dbeaver/ext/firebird/model/FireBirdTableTrigger.java
> +            this);
```suggestion
        return DBUtils.getFullQualifiedName(getDataSource(), this);
```

2023-03-22 11:56 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.generic/src/org/jkiss/dbeaver/ext/generic/model/GenericContainerTrigger.java
> +            this);
```suggestion
        return DBUtils.getFullQualifiedName(getDataSource(), getParentObject(), this);
```

2023-03-22 11:56 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.generic/src/org/jkiss/dbeaver/ext/generic/model/GenericTableTrigger.java
> +            this);
```suggestion
        return DBUtils.getFullQualifiedName(getDataSource(), getTable().getCatalog(), getTable().getSchema(), this);
```

2023-03-22 12:18 UTC, serge-rider requested changes

2023-03-22 12:18 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.generic/src/org/jkiss/dbeaver/ext/generic/edit/GenericTriggerManager.java
> +    ) throws DBException {
Whu IllegalState instead of DBException?

2023-03-22 12:18 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.generic/src/org/jkiss/dbeaver/ext/generic/edit/GenericTriggerManager.java
> +    ) {
Why no error?

2023-03-22 12:18 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.generic/src/org/jkiss/dbeaver/ext/generic/edit/GenericTriggerManager.java
> +public class GenericTriggerManager extends SQLTriggerManager<GenericTrigger, GenericTableBase> {
I think we need to extend existing generic trigger managers from this one.

2023-03-28 10:11 UTC, uslss commented
verified

2023-03-28 11:50 UTC, merged