#17635 store functions SQL words in the original case
dbeaver/dbeaver pull request #19609
Opened 2023-04-05 09:14 UTC by LonwoLonwo

![2023-04-05 12_04_10-DBeaver Ultimate 23 0 2 - _default_ Script-71](https://user-images.githubusercontent.com/45152336/230036301-1c28f151-7760-497b-9cd4-76e85a6e2742.png)

Please check different-case databases. Clickhouse - as mixed case, PostgreSQL as lower case, Oracle as upper case. Or other.
With Hippie Engine and without. With default case autocomplete and with upper/lower.

2023-04-05 11:06 UTC, ShadelessFox reviewed
This is a performance regression, for sure. Need to think of another solution.

2023-04-05 11:06 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/sql/AbstractSQLDialect.java
> +        return null;
This can slow things down, including formatting, autocompletion, and syntax highlighting.

2023-04-05 11:06 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/sql/AbstractSQLDialect.java
> +            if (keyword.toUpperCase(Locale.ENGLISH).startsWith(word)) {
Same here

2023-04-05 11:30 UTC, serge-rider requested changes

2023-04-05 11:30 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/format/SQLFormatterConfiguration.java
> +        Set<String> functions = syntaxManager.getDialect().getFunctions();
It is very slow. We should keep caqche in upper case. 
We may keep original value too

2023-04-11 08:38 UTC, serge-rider commented
Let's keep originalo case for all keywords (not just functions) and all dialects (not just Clickhouse).
Turn TreeSet into TreeMap and hold original case in value.

2023-04-14 13:01 UTC, serge-rider commented
Please move CH-related changes to https://github.com/dbeaver/dbeaver/pull/19706

2023-04-14 13:01 UTC, closed without merging