#19694 Add missing string truncate to txt export
dbeaver/dbeaver pull request #19705
Opened 2023-04-14 12:52 UTC by E1izabeth

2023-04-14 13:10 UTC, serge-rider requested changes

2023-04-14 13:10 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/exporter/DataExporterTXT.java
> +                String cell;
Let's avoid code duplication. Move only CommonUtils.truncateString() inside if

2023-04-14 13:18 UTC, serge-rider approved these changes

2023-04-16 18:56 UTC, MashaKorax commented
verified

2023-04-17 08:48 UTC, merged