dbeaver/dbeaver#19101 add handling for datetimeoffset
dbeaver/dbeaver pull request #19852
Opened 2023-05-02 12:56 UTC by Destrolaric

Closes dbeaver/dbeaver#19101
Now `datetimeoffset` should be handled as timestamp value

2023-05-02 21:56 UTC, Matvey16 commented
Changing data in this type with data formatting enabled now secretly changes the stored timezone


https://user-images.githubusercontent.com/82543000/235794597-6f673315-a04e-4839-8ca8-191e99f28047.mp4

2023-05-03 13:30 UTC, serge-rider requested changes

2023-05-03 13:30 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/model/data/SQLServerDateTimeOffsetHandler.java
> +                    throw new DBCException("Extracted timestamp is null");
Maybe it is better to write debug log and return NULL here

2023-05-03 13:30 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/model/data/SQLServerDateTimeOffsetHandler.java
> +                log.warn("error extracting datetimeoffset timestamp", e);
Use log.debug

2023-05-03 13:30 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/model/data/SQLServerDateTimeOffsetHandler.java
> +        super.bindValueObject(session, statement, type, index, value);
Did you test value write?

2023-05-03 14:31 UTC, Destrolaric commented on plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/model/data/SQLServerDateTimeOffsetHandler.java
> +        super.bindValueObject(session, statement, type, index, value);
Yes, I did test it.

2023-05-03 14:58 UTC, LonwoLonwo approved these changes

2023-05-03 15:29 UTC, E1izabeth approved these changes

2023-05-03 16:29 UTC, Matvey16 commented
I don't think that's expected behavior

As you can see, I am changing the date in a timestamp, but this leads to the time change in the timestamp, the timezone changes

Also I can't understand why the timezone changes to +00:00 even though query manager shows that it was set to +03:00 (which is still incorrect)

https://user-images.githubusercontent.com/82543000/235980061-d2c6eee9-3469-490d-aab4-b2caf0a76666.mp4

2023-05-03 17:09 UTC, Matvey16 commented
Verified

2023-05-11 08:23 UTC, LonwoLonwo approved these changes

2023-05-11 08:47 UTC, E1izabeth approved these changes

2023-05-11 10:59 UTC, Matvey16 commented
Verified

2023-05-11 11:25 UTC, merged