dbeaver#19890 Add information about current Project to the tab tooltip
dbeaver/dbeaver pull request #19964
Opened 2023-05-15 06:39 UTC by isyizhang

2023-05-15 07:16 UTC, E1izabeth commented
Thank you for the contribution.
The information about project should be added not only to SQL editor tabs. We also have at least Data editor and Entity editors. Their tooltips should also be modified.

2023-05-15 12:10 UTC, ShadelessFox requested changes
Please remove unrelated changes.

2023-05-15 12:13 UTC, ShadelessFox requested changes

2023-05-15 12:13 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditor.java
> +            .append("\n").append(NLS.bind(SQLEditorMessages.sql_sql_editor_title_tooltip_project, dataSourceContainer.getFolder().getName()));
A data source folder is not the same as a project it's contained in.

Use `DBPDataSourceContainer#getProject`

2023-05-15 12:27 UTC, serge-rider requested changes

2023-05-15 12:27 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditor.java
> +            .append("\n").append(NLS.bind(SQLEditorMessages.sql_sql_editor_title_tooltip_project, dataSourceContainer.getFolder().getName()));
dataSourceContainer.getFolder() may be null.

2023-05-16 12:21 UTC, LonwoLonwo commented
We are still waiting for other changes.

2023-06-21 13:25 UTC, ShadelessFox commented
There were no updates for a long time. I'm closing this PR as it doesn't fix the requested changes.

2023-06-21 13:25 UTC, closed without merging