dbeaver/dbeaver#18770 save previous user dialog size
dbeaver/dbeaver pull request #19983
Opened 2023-05-16 10:30 UTC by Destrolaric

Closes dbeaver/dbeaver#18770

2023-05-16 11:22 UTC, ShadelessFox requested changes
1. Override `Dialog#getInitialSize` instead.
2. You don't need extra props nor listeners. Just `Math.max` of the desired size and saved size.

2023-05-16 12:22 UTC, ShadelessFox requested changes

2023-05-16 12:22 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/connection/EditConnectionDialog.java
> +        Point proposedSize = new Point(minSize.x, minSize.y);
Redundant copy; you can use the returned value of `super.getInitialSize()`

2023-05-16 12:22 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/connection/EditConnectionDialog.java
> +        }
```suggestion
        } catch (NumberFormatException ignored) {
        }

```

2023-05-16 12:22 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/connection/EditConnectionDialog.java
> +            int width = settings.getInt("DIALOG_WIDTH");
I understand that these constants are defined in the `Dialog` class, but can you please make constants for these?

2023-05-16 12:22 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/connection/EditConnectionDialog.java
> +    private static final String PROP_DIALOG_RECOMMENDED_SIZE_WIDTH = "dialog.preferredSize.width";
These are not used anymore

2023-05-16 15:43 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/connection/EditConnectionDialog.java
> +        }
```suggestion
        } catch (NumberFormatException ignored) {
        }

```

2023-05-17 11:02 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/connection/EditConnectionDialog.java
> +        }
```suggestion
        } catch (NumberFormatException ignored) {
        }

```

2023-05-17 11:13 UTC, E1izabeth approved these changes

2023-05-17 11:19 UTC, ShadelessFox approved these changes

2023-05-17 15:43 UTC, Matvey16 commented
Verified

2023-05-25 09:40 UTC, serge-rider commented
Let's avoid hac with internal Eclipse prefs reading.

2023-05-25 11:20 UTC, E1izabeth approved these changes

2023-05-25 11:57 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/dialogs/MultiPageWizardDialog.java
> +        return new Point(Math.max(minSize.x, suggestedSize.x), Math.max(minSize.y, suggestedSize.y));
There are two unnecessary allocations.

```suggestion
        Point size = super.getInitialSize();
        size.x = Math.min(size.x, 700);
        size.y = Math.min(size.y, 500);
        return size;
```

2023-05-25 11:57 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/connection/EditConnectionDialog.java
> +        Control contents = super.createContents(parent);;
Please remove unrelated changes (in other places too).

2023-05-25 16:47 UTC, Matvey16 commented
Verified

2023-05-25 17:29 UTC, merged