#11405 fix tablespace statistics refreshing
dbeaver/dbeaver pull request #20159
Opened 2023-05-31 15:17 UTC by LonwoLonwo

Please check refreshing of the properties folder and refreshing of one tablespace element

2023-05-31 15:47 UTC, ShadelessFox approved these changes

2023-05-31 16:39 UTC, E1izabeth approved these changes

2023-06-06 11:26 UTC, uslss commented
verified

2023-06-06 13:50 UTC, serge-rider requested changes

2023-06-06 13:50 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/model/OracleTablespace.java
> +        loadSizes(monitor);
Just nullify cached sizes. Otherwise refresh of multiple tablespaces may take a lof of time

2023-06-12 10:03 UTC, uslss commented
verified

2023-06-12 11:46 UTC, serge-rider approved these changes

2023-06-12 11:46 UTC, merged