dbeaver/dbeaver#20187 add quotation rules for snowflake identifiers
dbeaver/dbeaver pull request #20189
Opened 2023-06-02 19:25 UTC by n5a5

2023-06-02 22:15 UTC, E1izabeth approved these changes

2023-06-03 17:50 UTC, serge-rider requested changes

2023-06-03 17:50 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.snowflake.core/src/org/jkiss/dbeaver/ext/snowflake/model/SnowflakeSQLDialect.java
> +        for (int i = 1; i < str.codePointCount(0, str.length()); i++) {
Please variable for `str.codePointCount(0, str.length())` otherwise it calculates it for every loop.

2023-06-03 17:50 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.snowflake.core/src/org/jkiss/dbeaver/ext/snowflake/model/SnowflakeSQLDialect.java
> +    private static boolean isLatinLetter(int codePoint) {
Perhaps we should move it to SQLUtils.

2023-06-06 09:34 UTC, LonwoLonwo commented
Perhaps tests also can be created for this case, like ClickhouseDialectTest.

2023-06-06 11:21 UTC, n5a5 commented
Good point @LonwoLonwo. For some reason, I thought it is impossible to test a dialect without a database connection :|

2023-06-07 11:08 UTC, n5a5 commented
Unit tests added

2023-06-08 07:50 UTC, LonwoLonwo approved these changes

2023-06-12 13:04 UTC, E1izabeth approved these changes

2023-06-14 11:46 UTC, Matvey16 commented
Verified

2023-06-14 12:45 UTC, merged