CB-3498 database transfer use entity id instead of node path
dbeaver/dbeaver pull request #20253
Opened 2023-06-09 14:22 UTC by yagudin10

2023-06-16 09:30 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseConsumerSettings.java
> +    @Deprecated
need a comment that these fields exist for backwards compatibility, otherwise someone will delete them in the future

2023-06-21 14:50 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseTransferConsumerSerializer.java
> +        var entityId = CommonUtils.toString(state.get("entityId"));
move to constant

2023-06-21 14:51 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseTransferConsumerSerializer.java
> +        String projectId = CommonUtils.toString(state.get("projectId"));
move to constant or use already existing one

2023-06-21 15:45 UTC, serge-rider requested changes

2023-06-21 15:45 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseTransferUtils.java
> +        var navigatorModel = DBWorkbench.getPlatform().getNavigatorModel();
Why refresh navigator model? The idea is to use database model instead of it.

2023-06-21 15:45 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseTransferConsumerSerializer.java
> +        DBSObjectContainer container = object.getContainer();
Does it supports backward compatibility?
Task saved in previous DBeaver version must work in new one

2023-06-21 15:48 UTC, yagudin10 commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseTransferConsumerSerializer.java
> +        DBSObjectContainer container = object.getContainer();
Yes, it does (checked with old tasks).

2023-06-21 15:52 UTC, yagudin10 commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseTransferUtils.java
> +        var navigatorModel = DBWorkbench.getPlatform().getNavigatorModel();
Tried not to change current behavior with container node.

2023-06-29 11:40 UTC, merged