#11179 add more metadata info about packages for Oracle; use constants
dbeaver/dbeaver pull request #20290
Opened 2023-06-14 15:35 UTC by LonwoLonwo

![2023-06-14 18_29_59-Window](https://github.com/dbeaver/dbeaver/assets/45152336/d511097d-aa6e-4e12-a6f2-7decccefe98e)

https://docs.oracle.com/cd/B14117_01/server.101/b10755/statviews_1102.htm

2023-06-15 10:00 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.oracle/OSGI-INF/l10n/bundle.properties
> +meta.org.jkiss.dbeaver.ext.oracle.model.OraclePackage.temporary.description=Whether the object is temporary (the current session can see only data that it placed in this object itself)
Do you mean this?
```suggestion
meta.org.jkiss.dbeaver.ext.oracle.model.OraclePackage.temporary.description=Whether the object is temporary (the current session can see only data that is placed in this object itself)
```

2023-06-15 10:00 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.oracle/OSGI-INF/l10n/bundle.properties
> +meta.org.jkiss.dbeaver.ext.oracle.model.OraclePackage.lastDDLTime.description=Timestamp for the last modification of the object resulting from a DDL statement (including grants and revokes)
I don't like `resulting`. For me, it makes sentence unclear. Maybe `due to` or `as a result` fits better.

2023-06-16 12:02 UTC, E1izabeth requested changes
Please, fix typo and message formulation..

2023-06-19 09:18 UTC, uslss commented
verified

2023-06-19 12:02 UTC, merged