Update bundle_ko.properties
dbeaver/dbeaver pull request #20433
Opened 2023-06-29 15:43 UTC by iraidaa

dbeaver/dbeaver#20432 One of our users reported a typo in File -> Refresh in Korean version. I changed it to the correct spelling.

2023-06-29 21:23 UTC, E1izabeth approved these changes

2023-06-30 12:59 UTC, serge-rider requested changes

2023-06-30 12:59 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.app.standalone/OSGI-INF/l10n/bundle_ko.properties
> +bindingcontext.name.bindingView      = In Binding View
It doesn't make sense to keep English string in localizations. Just delete them

2023-07-04 11:19 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.app.standalone/OSGI-INF/l10n/bundle_ko.properties
> +activity.hideE4Activity.name = Menu And Toolbar Hiding Activity
```suggestion

```

2023-07-04 11:19 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.app.standalone/OSGI-INF/l10n/bundle_ko.properties
>  #command.org.jkiss.dbeaver.core.navigator.forwardHistory.name         = Forward History
```suggestion

```

2023-07-04 11:19 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.app.standalone/OSGI-INF/l10n/bundle_ko.properties
>  #command.org.jkiss.dbeaver.core.navigator.backwardHistory.name        = Backward History
```suggestion

```

2023-07-04 11:19 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.app.standalone/OSGI-INF/l10n/bundle_ko.properties
> +#trimmedwindow.label.dbeaver = DBeaver
```suggestion

```

2023-07-04 13:39 UTC, E1izabeth approved these changes

2023-07-05 10:28 UTC, MashaKorax commented
verified

2023-07-05 10:31 UTC, merged