Fixed DE translation für 'Insertion case'
dbeaver/dbeaver pull request #20458
Opened 2023-07-03 15:29 UTC by fjf2002

2023-07-03 16:10 UTC, E1izabeth approved these changes

2023-07-04 06:53 UTC, LonwoLonwo approved these changes

2023-07-04 14:52 UTC, MashaKorax commented
In the app interface, it looks like  this. Would you kindly make a fix?
![dbeaver_B5cryjfogM](https://github.com/dbeaver/dbeaver/assets/84867187/7949c832-75c3-4498-9908-3006b8f1406d)

2023-07-04 14:59 UTC, E1izabeth requested changes
I suppose it should be like this.
Native characters doesn't fit into ascii encoding.

2023-07-04 14:59 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages_de.properties
> +pref_page_sql_completion_label_insert_case = Groß-/Kleinschreibung beim Einfügen
```suggestion
pref_page_sql_completion_label_insert_case = Gro\u00df-/Kleinschreibung beim Einf\u00fcgen
```

2023-07-10 13:32 UTC, E1izabeth approved these changes

2023-07-10 14:04 UTC, MashaKorax commented
verified

2023-07-10 15:17 UTC, merged