dbeaver/dbeaver#20528 Initial commit for my case insensitive feature.
dbeaver/dbeaver pull request #20614
Opened 2023-07-19 20:14 UTC by vijayap20

Order case insensitive as an option at the Client Side #20528[](url)

2023-07-26 10:50 UTC, E1izabeth commented
Thank you for contribution.
We don't want to add such option. Let's just change the behaviour of the existing `Always on client` setting. The sorting should always be case-insensitive.

Also only strings should be compared in such a way - it doesn't make sense to do it for numbers.
And pay attention on different locales. It should correctly work with non-latin languages.

2023-08-02 11:42 UTC, E1izabeth commented
Please delete all changes that are no longer in use

2023-08-07 08:46 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetModel.java
> +                    result = DBUtils.compareDataValues((Object) cell1.toString().toLowerCase(), (Object) cell2.toString().toLowerCase());
Please do such comparison only for string types. It makes no sense to do it for numbers or binary objects.

2023-08-10 19:06 UTC, E1izabeth approved these changes

2023-08-10 20:11 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetModel.java
> +                    if(cell1 instanceof String && cell2 instanceof String) {
```suggestion
                    if (cell1 instanceof String && cell2 instanceof String) {
```

2023-08-10 20:11 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetModel.java
> +                    }else {
```suggestion
                    } else {
```

2023-08-10 20:57 UTC, vijayap20 commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetModel.java
> +                    }else {
resolved

2023-08-10 22:00 UTC, ShadelessFox approved these changes

2023-08-14 19:56 UTC, E1izabeth commented
Passed to QA team.

2023-08-29 11:49 UTC, Matvey16 commented
Verified

2023-08-29 12:26 UTC, serge-rider requested changes

2023-08-29 12:26 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetModel.java
> +                    if (cell1 instanceof String && cell2 instanceof String) {
WE can use simple compareToIgnoreCase here.

2023-09-05 04:16 UTC, E1izabeth commented
@vijayap20 would you made the requested changes?

2023-09-06 08:30 UTC, E1izabeth approved these changes

2023-09-06 08:48 UTC, LonwoLonwo approved these changes

2023-09-13 09:59 UTC, Matvey16 commented
Verified

2023-09-13 13:04 UTC, serge-rider approved these changes

2023-09-13 13:04 UTC, merged