#20725 support YellowBrick procedures recognition
dbeaver/dbeaver pull request #20764
Opened 2023-08-02 08:24 UTC by LonwoLonwo

![2023-08-02 09_22_37-Delete script](https://github.com/dbeaver/dbeaver/assets/45152336/bd025dcb-c975-4898-8b52-77594567f944)

You can check only YellowBrick. No impact on other forks.

2023-08-02 08:25 UTC, E1izabeth approved these changes

2023-08-02 11:39 UTC, ShadelessFox approved these changes

2023-08-02 16:43 UTC, Matvey16 commented
Verified

2023-08-02 19:49 UTC, serge-rider requested changes

2023-08-02 19:49 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreServerExtension.java
> +    boolean supportsProSPColumn();
Lets not add yet another functin to ServerType. We can determine column presence in loadInfo (lookup in resultset metadata)

2023-08-03 15:59 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreProcedure.java
> +                    // Slip then. This column only persist in special cases
```suggestion
                } catch (SQLException ignored) {
                    // Skip then. This column only persist in special cases
```

2023-08-07 08:38 UTC, Matvey16 commented
Verified

2023-08-07 08:56 UTC, merged