#20765 use <undefined> name for nullable data types
dbeaver/dbeaver pull request #20766
Opened 2023-08-02 09:01 UTC by LonwoLonwo

![2023-08-02 11_57_15-DBeaver Ultimate 23 1 3 - _demo_ Script-37](https://github.com/dbeaver/dbeaver/assets/45152336/0f0293e8-43ff-4f46-b30f-0b7549ae9c10)

You can suggest another name instead of `<undefined>`

For tester: ask me about the database to check

2023-08-02 09:07 UTC, E1izabeth commented
<undefined> tells nothing about what is undefined. I'd prefer I little bit longer, but clearer: unknown type

2023-08-02 09:22 UTC, E1izabeth approved these changes

2023-08-02 11:38 UTC, ShadelessFox approved these changes

2023-08-02 16:14 UTC, Matvey16 commented
Verified

2023-08-02 19:50 UTC, serge-rider requested changes

2023-08-02 19:50 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/DBUtils.java
> +            return "<unknown type>";
Please add it into i18n messages

2023-08-07 08:27 UTC, Matvey16 commented
Verified

2023-08-07 08:55 UTC, merged