dbeaver/pro#1768 High-contrast theme
dbeaver/dbeaver pull request #20874
Opened 2023-08-11 10:45 UTC by E1izabeth

2023-08-15 19:17 UTC, E1izabeth commented
Win 11 Desert theme

![image](https://github.com/dbeaver/dbeaver/assets/28875055/0bd4d605-f2a7-46d1-9b24-53562da09e5e)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/4e9b7f38-09c7-4073-a9da-54d2f6c558c8)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/c7beff3e-7d21-45b7-94ca-f5d9f3af6c59)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/2bcdf58d-f4c1-41ee-937f-35399a3067ac)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/8695e1e7-3537-4106-bf3c-9f5c5e85f957)

Win 11 Nigh sky theme
![image](https://github.com/dbeaver/dbeaver/assets/28875055/f4cdcb61-b433-4120-8943-c8db9d0b754f)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/f2efc1f5-cefe-44a5-ad75-1a171e9d21a9)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/1037c5c2-7752-4678-a7d1-6d578160aef1)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/a39891a7-a51e-48cb-b8e0-03806f99cb5a)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/8067262c-3e0a-412b-8f64-975848bbd751)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/21c9382f-154b-4b23-a132-d8151489413b)

2023-08-15 19:50 UTC, serge-rider requested changes

2023-08-15 19:50 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/syntax/SQLTokenAdapter.java
> +                color = new Color(255 - color.getRed(), 255 - color.getGreen(), 255 - color.getBlue());
Let's move to some UIStyles util function  (e.g. invert color)

2023-08-15 19:50 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/spreadsheet/SpreadsheetPresentation.java
> +                if (normalColor == null || normalColor == backgroundNormal || UIStyles.isHighContrastTheme()) {
This function is called thousands of times for big resultset rendering.
high contrast theme detection is a relatively slow function (it queries for thme service which crowls deeply in Eclipse API).
Lets cache this flag in the presention (along with other cache flags - they are refreshed in refreshData function)

2023-08-15 20:45 UTC, serge-rider requested changes

2023-08-15 20:45 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/syntax/SQLTokenAdapter.java
> +                    colorKey = SQLConstants.CONFIG_COLOR_KEYWORD; style = scanner.getKeywordStyle(); break;
It may be too redundant but let's use codestlye rules here and below

2023-08-15 23:31 UTC, E1izabeth commented
Also breadcrumbs, vertical tabs, tabbed folder list, references panel were fixed
![image](https://github.com/dbeaver/dbeaver/assets/28875055/6d6e9be3-c0cb-43fd-b6e1-da3da7529f83)

![image](https://github.com/dbeaver/dbeaver/assets/28875055/7be6e9d0-a15e-4b91-9295-d2d2e0ac8155)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/7931a18f-a318-4d35-b7d0-3c5f4005a9a6)

2023-08-16 14:19 UTC, serge-rider approved these changes

2023-08-16 15:51 UTC, MashaKorax commented
verified

2023-08-16 15:52 UTC, merged