CB-3449. Fixed formatting sql script at macOs/linux.
dbeaver/dbeaver pull request #20929
Opened 2023-08-18 14:12 UTC by DenisSinelnikov

2023-08-18 14:39 UTC, ShadelessFox reviewed
Can you please explain why is this needed?

2023-08-18 14:49 UTC, DenisSinelnikov commented
> Can you please explain why is this needed?

Sure, 
It is necessary for correct formatting, on Windows it defaults values for the end of the line \r\n , but if you do it on unix systems they default line ends with a different value, so you have to manually substitute here
https://stackoverflow.com/questions/426397/do-line-endings-differ-between-windows-and-linux

2023-08-18 15:25 UTC, alexander-skoblikov requested changes
we should pass correct indent into SQLFormatterConfiguration from CloudBeaver side, do not change core format logic

2023-08-23 10:12 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/format/SQLFormatUtils.java
> +        return formatSQL(dataSource, syntaxManager, query, null);
You can call the overloaded method here. It's better than duplicating code.

```java
return formatSQL(dataSource, query, null);
```

2023-08-23 10:12 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/format/SQLFormatUtils.java
> +                                   @Nullable String indent) {
Quite a weird formatting. Also, please use nullability annotations whenever possible.

```suggestion
    @NotNull
    public static String formatSQL(
        @Nullable DBPDataSource dataSource,
        @NotNull SQLSyntaxManager syntaxManager,
        @NotNull String query,
        @Nullable String indent
    ) {
```

2023-08-23 10:12 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/translate/SQLQueryTranslator.java
> +                    null);
You don't need to call the overloaded method here. It will be called anyways because the original method calls the overloaded.

2023-08-23 11:39 UTC, ShadelessFox approved these changes

2023-08-24 13:43 UTC, merged