Add select all and deselect all buttons when exporting data
dbeaver/dbeaver pull request #20941
Opened 2023-08-21 17:52 UTC by niushuai1991

#18774 

![printscreen 2023-08-22 014959](https://github.com/dbeaver/dbeaver/assets/6659062/206a8d95-177f-4496-8bad-c9e7cff986e1)

2023-08-21 18:14 UTC, niushuai1991 commented
I only added English and Chinese, because I am not familiar with others.

2023-08-22 08:12 UTC, LonwoLonwo commented
Hello @niushuai1991 

Thanks for your contribution.

You helped me to find a bug. In your code and our code, the "Cancel" button will be ignored after clicking. It also works as the "Ok" button.
So, You need to think about the temporary state of actions list.

2023-08-23 14:16 UTC, niushuai1991 commented
@LonwoLonwo hi, After some tries, I changed the mappings to member variables and it's already working fine.

2023-09-02 13:40 UTC, niushuai1991 commented
> Hello @niushuai1991
> 
> Thanks for your contribution.
> 
> You helped me to find a bug. In your code and our code, the "Cancel" button will be ignored after clicking. It also works as the "Ok" button. So, You need to think about the temporary state of actions list.

I fixed this bug

2023-09-02 13:41 UTC, niushuai1991 commented
> Hello @niushuai1991
> 
> Thanks for your contribution.
> 
> You helped me to find a bug. In your code and our code, the "Cancel" button will be ignored after clicking. It also works as the "Ok" button. So, You need to think about the temporary state of actions list.

@LonwoLonwo OK, I fixed this bug.

2023-11-01 02:44 UTC, ElPettego approved these changes
clean

2023-11-02 13:35 UTC, ShadelessFox requested changes
There are too many changes IMO.

You can use the `refreshMappings` to acquire a copy of all mappings that you'll operate over in the dialog. After pressing the OK button, you can simply replace old mappings with new mappings.

2023-11-02 13:35 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/pages/stream/StreamConsumerPageSettings.java
> +            Button selectAllButton = new Button(panel, SWT.NONE);
Please consider using `UIUtils.createDialogButton` instead. They have padding and generally look better.

2023-12-18 15:11 UTC, niushuai1991 commented
@ShadelessFox hello,Your suggestion is very helpful. I have optimized my code, please review it again.

2023-12-20 14:48 UTC, ShadelessFox approved these changes

2023-12-22 14:40 UTC, E1izabeth approved these changes

2024-01-02 16:35 UTC, DariaMarkaryan commented
Verified

2024-01-10 16:40 UTC, closed without merging

2024-01-10 16:40 UTC, ShadelessFox commented
We decided that we wanted to allow changing mappings directly from the tree. Thanks for the contribution, regardless. https://github.com/dbeaver/dbeaver/pull/22409