dbeaver/cloudbeaver#1951 Handle parsing errors
dbeaver/dbeaver pull request #20993
Opened 2023-08-24 14:25 UTC by ShadelessFox

2023-08-24 14:26 UTC, E1izabeth approved these changes

2023-08-24 14:56 UTC, serge-rider requested changes

2023-08-24 14:56 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.clickhouse/src/org/jkiss/dbeaver/ext/clickhouse/ClickhouseTypeParser.java
> +            return null;
Let's add some debug logging here (no stacktrace, only message)

2023-08-25 12:23 UTC, uslss commented
verified

2023-08-25 12:29 UTC, serge-rider approved these changes

2023-08-25 12:29 UTC, merged