#18892 Use select if the function is not a procedure for debugging
dbeaver/dbeaver pull request #21008
Opened 2023-08-25 11:33 UTC by E1izabeth

You might check PostgreSQL 12` dvdrental.public.film_in_stock` fucntion and `dvdrental.public.display_message` procedure. Both should work now (`film_in_stock` didn't work as we tried to use `CALL `with function instead of `SELECT`).

2023-08-25 12:22 UTC, serge-rider requested changes

2023-08-25 12:22 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.postgresql.debug.core/src/org/jkiss/dbeaver/ext/postgresql/debug/internal/impl/PostgreDebugSession.java
> +                        if (function.getKind().equals(PostgreProcedureKind.p)) {
Can we test using getProcedureType()?

2023-08-25 12:27 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.postgresql.debug.core/src/org/jkiss/dbeaver/ext/postgresql/debug/internal/impl/PostgreDebugSession.java
> +                        if (function.getKind().equals(PostgreProcedureKind.p)) {
Yes

2023-08-25 14:18 UTC, LonwoLonwo approved these changes

2023-08-28 12:50 UTC, MashaKorax commented
verified

2023-08-28 13:01 UTC, merged