dbeaver/pro#1640 update error message
dbeaver/dbeaver pull request #21006
Opened 2023-08-25 10:03 UTC by Destrolaric

Closes dbeaver/pro#1640

2023-08-25 12:24 UTC, serge-rider requested changes

2023-08-25 12:24 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.registry/src/org/jkiss/dbeaver/registry/driver/MissingDataSourceProvider.java
> +        throw new DBException("Error: Invalid Datasource Configuration\n"
Let's not use mixed case in error messages.

2023-08-29 07:59 UTC, LonwoLonwo approved these changes

2023-08-29 08:50 UTC, MashaKorax commented
Please, add the period to separate these sentences

![dbeaver_Z4aKPp839H](https://github.com/dbeaver/dbeaver/assets/84867187/1c0af820-8483-4220-8444-803f99e0f3e4)

2023-08-29 11:16 UTC, E1izabeth commented
Do we really need to repeat `Error: invalid datasource configuration` as it's already presented in the final message of the dialog?

2023-08-29 13:12 UTC, MashaKorax commented
verified

2023-08-29 13:54 UTC, merged