#16693 Reset settings on startup
dbeaver/dbeaver pull request #21017
Opened 2023-08-28 09:19 UTC by ShadelessFox

Acceptance criteria:
- Works on Windows
- Works on Linux
- Works on macOS

2023-08-28 09:56 UTC, serge-rider commented
Did you try to use IStartup instead of our custom hooks?

2023-08-28 10:17 UTC, ShadelessFox commented
We need to register these hooks only when we want to.

2023-08-29 12:09 UTC, serge-rider requested changes

2023-08-29 12:09 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/startup/StartupHook.java
> +    void handle(@NotNull Map<String, Object> data) throws Exception;
Please add javadocs

2023-08-29 12:09 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverApplication.java
> +    private static final Path STARTUP_HOOKS_FILE = Path.of("dbeaver-startup-hooks.json");
Why it is static and in unknown location?
Let's keep it in workspace metadata folder and resolve on demand.

2023-08-29 12:09 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverApplication.java
> +
Let's not use gson parser. Simple properties files is enough.

2023-08-29 12:13 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverApplication.java
> +
Not enough for the payload. It may contain arbitrary data.

2023-08-29 12:15 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverApplication.java
> +    private static final Path STARTUP_HOOKS_FILE = Path.of("dbeaver-startup-hooks.json");
It doesn't point to any particular path. It's just a file name. Maybe it would be clearer if it was `String`, not `Path`.

It's located here because that file's load/store logic is handled in that enclosing class, nowhere else.

I still think that exposing implementation-specific details is a bad idea.

2023-08-31 15:21 UTC, E1izabeth approved these changes

2023-08-31 15:28 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverApplication.java
> +        loadStartupActions();
Please test with non-default workspace. `-data path`

2023-09-05 11:43 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverApplication.java
> +        final Path path = Path.of(instanceLoc.getDataArea("").toURI());
You probably don't want to use toURI(), but I'm not 100% sure. @Destrolaric is an expert in this now.

2023-09-05 12:22 UTC, E1izabeth approved these changes

2023-09-29 11:31 UTC, Matvey16 commented
Verified

2023-09-29 12:10 UTC, serge-rider approved these changes

2023-09-29 12:11 UTC, merged