Devel zh thenext
dbeaver/dbeaver pull request #21058
Opened 2023-08-31 02:52 UTC by thenext600

* mssql Chinesization

2023-08-31 02:52 UTC, thenext600 commented
* mssql Chinesization

2023-09-01 13:25 UTC, E1izabeth requested changes

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.cmp.simple/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver\u6a21\u5f0f\u6bd4\u8f83(\u7b80\u5355)
Please, don't add it. I believe it shouldn't be translated. Please remove this changes everywhere

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.cmp.simple.ui/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver\u6a21\u5f0f\u6bd4\u8f83UI(\u7b80\u5355)
```suggestion

```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.cmp.simple/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver\u6a21\u5f0f\u6bd4\u8f83(\u7b80\u5355)
```suggestion

```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.data.gis.view/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver Data GIS - View
```suggestion

```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.data.gis/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Vendor	=	JKISS
```suggestion

```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver Office\u652f\u6301
```suggestion

```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.erd.model/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver ERD\u6a21\u578b
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.debug.ui/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver Debug UI
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.athena.ui/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver Athena UI
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.athena/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver AWS Athena\u6269\u5c55
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.bigquery.ui/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver Google BigQuery UI
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.bigquery/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver\u8c37\u6b4cBigQuery\u6269\u5c55
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.clickhouse/OSGI-INF/l10n/bundle_zh.properties
> +#Bundle-Name = DBeaver Clickhouse Support
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.databricks/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver Azure Databricks\u652f\u6301
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.datavirtuality/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver\u6570\u636e\u865a\u62df\u6269\u5c55\u6838\u5fc3
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.db2/OSGI-INF/l10n/bundle_zh.properties
> +#Bundle-Name = DBeaver DB2\u652f\u6301
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.db2/OSGI-INF/l10n/bundle_zh.properties
> +# Copyright (C) 2013-2016 Denis Forveille titou10.titou10@gmail.com
It looks like a new file. Do we need this copyright here?

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.mssql.ui/OSGI-INF/l10n/bundle_tw.properties
> +editor.session_manager.name =會話
There should be ascii codes. You shouldn't write hanzi in properties file

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.debug.core/OSGI-INF/l10n/bundle_zh.properties
> +#Bundle-Name = DBeaver Debug Core
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.mssql.ui/OSGI-INF/l10n/bundle_tw.properties
> +editor.session_manager.name =會話
There should be no hanzi in this files. Only ASCII codes are allowed.

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.mysql/OSGI-INF/l10n/bundle_zh.properties
> +dashboard.mysql.sessions.description = 按命令分组显示会话
This whole file contains non-ascii characters. It will not work.

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.tidb.ui/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver TiDB UI
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.vertica/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver Vertica Support
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.wmi/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver WMI Support
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.team.git.ui/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver Git\u96c6\u6210UI
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.team.git/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver Git\u96c6\u6210
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.app.eclipse/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name=DBeaver IDE
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.app.standalone/OSGI-INF/l10n/bundle_zh.properties
> +extension.standalone.name = DBeaver \u72ec\u7acb\u7248
It should not be translated. So please remove this changes.

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.charts/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = \u6570\u636e\u5e93\u56fe\u8868 UI
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.editors.hex/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver UI Editors - Hex
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.search/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaverSearchUI
```suggestion
```

2023-09-01 13:25 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui/OSGI-INF/l10n/bundle_zh.properties
> +Bundle-Name = DBeaver UI
```suggestion
```

2023-09-01 13:52 UTC, E1izabeth commented
Also I see that changes in this PR relies on the another your PR with has unresolved requested changes. Please, address them first or rebase your commit about mssql to another branch - the way the changes from that pull request should not be included in this one.

2023-09-02 00:34 UTC, closed without merging