#21086 avoid NPE in the SQL Editor
dbeaver/dbeaver pull request #21087
Opened 2023-09-01 07:20 UTC by LonwoLonwo

Maybe `toolItem != null` is better, but I'm not sure

2023-09-01 08:48 UTC, E1izabeth requested changes

2023-09-01 08:48 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditor.java
> +                    if (toolItem == null || !toolItem.getSelection()) {
```suggestion
                    if (toolItem != null || !toolItem.getSelection()) {
```

2023-09-01 13:41 UTC, E1izabeth approved these changes

2023-09-11 10:06 UTC, Matvey16 commented
Verified

2023-09-11 10:38 UTC, merged