#21286 supports Spanner FKs reading for schema with empty name
dbeaver/dbeaver pull request #21315
Opened 2023-09-25 15:24 UTC by LonwoLonwo

![2023-09-25 18_16_07-DBeaver Ultimate 23 2 1 - DEFAULT](https://github.com/dbeaver/dbeaver/assets/45152336/6d21bb3b-c560-4748-9f26-89e350c5d1b9)

2023-09-25 15:54 UTC, serge-rider requested changes

2023-09-25 15:54 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.generic/src/org/jkiss/dbeaver/ext/generic/model/GenericDataSource.java
> +        } else if (container == null && getMetaModel().supportsNullSchemas() && !CommonUtils.isEmpty(schemas.getCachedObjects())) {
Let's move it to spanned module

2023-09-26 11:38 UTC, E1izabeth approved these changes

2023-09-26 11:38 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.spanner/src/org/jkiss/dbeaver/ext/spanner/model/SpannerMetaModel.java
> +            return "INFORMATION_SCHEMA".equals(schema.getName()) || "SPANNER_SYS".equals(schema.getName());
I'd make an array of these constants called SYSTEM_SCHEMA_NAMES

2023-09-27 11:24 UTC, uslss commented
verified

2023-09-27 11:51 UTC, merged