dbeaver/pro#1818 Allow changing task output format
dbeaver/dbeaver pull request #21325
Opened 2023-09-26 12:52 UTC by ShadelessFox

2023-10-02 09:11 UTC, E1izabeth approved these changes

2023-10-04 14:11 UTC, LonwoLonwo approved these changes

2023-11-01 08:50 UTC, serge-rider requested changes

2023-11-01 08:50 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/wizard/DataTransferWizard.java
> -        if (ArrayUtils.isEmpty(settings.getInitConsumers())) {
You delete initConsumers usage at all. It affects all direct exports (when consumers specified explicitly). It may break direct data import tasks.

In any case if you delete its usage you have to delete initConsumers variable along with all related init logic.

2023-11-01 11:56 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/wizard/DataTransferWizard.java
> -        if (ArrayUtils.isEmpty(settings.getInitConsumers())) {
No, it's still used when setting up pipes.

2023-11-07 10:23 UTC, MashaKorax commented
Import settings lost pages 'Tables mappng' and 'Data load settings'. (screen 1 - old version, screen 2 - new version ). 
STR:
![dbeaver_NIYiYmQJSU](https://github.com/dbeaver/dbeaver/assets/84867187/68e77033-dffd-4df0-ad17-b54042deadf0)

-import csv file to database without task
![dbeaver_Y4B9gPZS3s](https://github.com/dbeaver/dbeaver/assets/84867187/e1f52f40-c68a-40af-be1f-fe989142ec30)

2023-11-14 14:45 UTC, MashaKorax commented
1. Create import task
2. Edit imp task - click on import source - than change input file
3. Save task
4. try to perform task  - check that source file is NOT mported in target table
```
java.lang.NullPointerException: Cannot invoke "org.jkiss.dbeaver.tools.transfer.stream.StreamEntityMapping.getInputFile()" because "mapping" is null
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer$ObjectSerializer.serializeObject(StreamTransferProducer.java:182)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferProducer$ObjectSerializer.serializeObject(StreamTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.DTUtils.serializeObject(DTUtils.java:269)
	at org.jkiss.dbeaver.tools.transfer.DataTransferSettings.saveNodesLocation(DataTransferSettings.java:712)
	at org.jkiss.dbeaver.tools.transfer.ui.wizard.DataTransferWizard.saveTaskState(DataTransferWizard.java:487)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.saveConfigurationToTask(TaskConfigurationWizard.java:320)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard.saveTask(TaskConfigurationWizard.java:315)
	at org.jkiss.dbeaver.tasks.ui.wizard.TaskConfigurationWizard$2.widgetSelected(TaskConfigurationWizard.java:372)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.jkiss.dbeaver.tasks.ui.view.TaskHandlerEdit.execute(TaskHandlerEdit.java:56)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:300)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:785)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:762)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.jkiss.dbeaver.ui.app.standalone.DBeaverApplication.start(DBeaverApplication.java:280)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```

https://github.com/dbeaver/dbeaver/assets/84867187/d0bf5726-73ab-4f09-9609-eff8eed9c9da

2023-11-14 14:50 UTC, ShadelessFox commented
Caused by #21452

2023-11-16 17:33 UTC, serge-rider approved these changes

2023-11-22 10:06 UTC, MashaKorax commented
Impossible to specify target database if try to change export task  from file format to **Database**

https://github.com/dbeaver/dbeaver/assets/84867187/724c4e2f-d842-4cf8-816d-9f8a3bce6761

2023-11-22 10:21 UTC, ShadelessFox commented
Weird. You're not even supposed to see the database option if the task was previously configured to export to a file. I'll take a look

2023-12-12 10:23 UTC, MashaKorax commented
verified

2023-12-12 10:45 UTC, merged