dbeaver/dbeaver#21312 Set row color for result set
dbeaver/dbeaver pull request #21351
Opened 2023-09-27 15:53 UTC by serjiokov

Creating new Shell object from the parent shell leds to "Unhandled Loop Exception",
in order to avoid it the shell for color chooser dialog created from default display.

2023-09-27 15:54 UTC, serjiokov commented
![image](https://github.com/dbeaver/dbeaver/assets/32031248/8985de3b-abd8-4c14-868f-f1babe3eac34)

2023-09-27 17:05 UTC, serge-rider requested changes

2023-09-27 17:05 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/handler/ResultSetHandlerMain.java
> +                            ColorDialog dialog = new ColorDialog(UIUtils.createCenteredShell(activeShell));
Why create new shell at all?
We can use ResultSetViewer's shell.

2023-09-28 08:28 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/handler/ResultSetHandlerMain.java
> +                            ColorDialog dialog = new ColorDialog(UIUtils.createCenteredShell(activeShell));
The Shell object require to centralize dialog on Display.
The shell object taken from control, viewer or HandlerUtils is the same bcs it is a global shell.
In other words we should create a new shell object specifically for dialog location, shell be disposed as dialog closed,
no manual methods require for it.  
The call of ui operations have to be coverd by Display->asyncExec(...)

2023-09-28 08:31 UTC, serjiokov commented
Two places in code that invokes ColorDialog wors fine now:
1. 
![image](https://github.com/dbeaver/dbeaver/assets/32031248/a2ffb73b-6b6e-40b6-9388-36560ebc0f3b)
2.  
![Screenshot 2023-09-28 101051](https://github.com/dbeaver/dbeaver/assets/32031248/e9235847-ba30-4050-bb92-4e66e7bd86ee)

2023-10-03 09:28 UTC, MashaKorax commented
verified

2023-10-03 11:58 UTC, serge-rider approved these changes

2023-10-03 12:12 UTC, merged