dbeaver/dbeaver#21467 fix no datasource update
dbeaver/dbeaver pull request #21541
Opened 2023-10-16 12:57 UTC by Destrolaric

Closes dbeaver/dbeaver#21467

2023-10-16 13:02 UTC, E1izabeth requested changes

2023-10-16 13:02 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/actions/NavigatorHandlerAssociateScript.java
> +                    project = DBPPlatformDesktop.getInstance().getWorkspace().getProject(script.getProject());
`project` can be null here

2023-10-16 13:05 UTC, E1izabeth approved these changes

2023-10-16 16:23 UTC, LonwoLonwo approved these changes

2023-10-17 16:57 UTC, MashaKorax commented
verified

2023-10-17 17:19 UTC, merged