Add support for Apache Flink
dbeaver/dbeaver pull request #21842
Opened 2023-11-13 16:30 UTC by rmoff

In the latest version of Apache Flink (1.18) [a JDBC driver
was added](https://cwiki.apache.org/confluence/display/FLINK/FLIP-293%3A+Introduce+Flink+Jdbc+Driver+For+Sql+Gateway) for Flink's SQL Gateway. 

This PR adds direct support for this driver to Dbeaver.

2023-11-14 08:34 UTC, LonwoLonwo commented
Thanks for your contribution.

If you have a logo, you can also add it like this:

```xml
icon="icons/flink_icon.png"
iconBig="icons/flink_icon_big.png"
logoImage="icons/flink_logo.png"
```

2023-11-14 09:30 UTC, rmoff commented
Hi @LonwoLonwo, I already have `icon` and `iconBig` defined. None of the other generic providers use `logoImage` and looking at the code it default to using `icon` so I think this should be ok? 

icon shows up correctly in the UI: 

![image](https://github.com/dbeaver/dbeaver/assets/3671582/db656c13-7f65-4e4c-a374-3270fae05076)

![CleanShot 2023-11-14 at 09 28 07](https://github.com/dbeaver/dbeaver/assets/3671582/1796d52e-ae5e-474b-a0d3-f7b0d9206433)

![image](https://github.com/dbeaver/dbeaver/assets/3671582/6e501ffa-7f95-49a1-82eb-940aa04d1e67)

2023-11-14 09:36 UTC, LonwoLonwo commented
Ok, no problem. It can be just a big icon on the Connection Page.

2023-11-15 12:27 UTC, LonwoLonwo commented
And please take a look at my review comments.

2023-11-16 08:17 UTC, rmoff commented
> And please take a look at my review comments.

Hi, I don't see any review comments?

2023-11-16 08:39 UTC, LonwoLonwo requested changes

2023-11-16 08:39 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.generic/plugin.xml
> +                    <file type="jar" path="maven:/org.apache.flink:flink-sql-jdbc-driver-bundle:RELEASE" bundle="!drivers.apache_flink"/>
```suggestion
                    <file type="jar" path="maven:/org.apache.flink:flink-sql-jdbc-driver-bundle:RELEASE"/>
```

2023-11-16 08:39 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.generic/plugin.xml
> +                    <file type="license" path="https://www.apache.org/licenses/LICENSE-2.0.txt" bundle="!drivers.apache_flink"/>
```suggestion
                    <file type="license" path="https://www.apache.org/licenses/LICENSE-2.0.txt"/>
```

2023-11-16 08:39 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.generic/plugin.xml
> +                    <file type="jar" path="drivers/apache_flink" bundle="drivers.apache_flink"/>
```suggestion
```

2023-11-16 08:39 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.generic/plugin.xml
> +                    <file type="jar" path="drivers/apache_flink" bundle="drivers.apache_flink"/>
We do not have the Flink driver for now, so there is no need for this code. We will add it in the future if it will be the reason.

2023-11-16 08:40 UTC, LonwoLonwo commented
> Hi, I don't see any review comments?

Sorry, they were probably stuck somehow.

2023-11-16 10:11 UTC, LonwoLonwo approved these changes

2023-11-16 10:12 UTC, LonwoLonwo commented
Ok. Now we are waiting for one more review and then the QA Team.

2023-11-16 10:27 UTC, rmoff commented
Great, thank you @LonwoLonwo !

2023-11-16 12:42 UTC, E1izabeth approved these changes

2023-11-28 15:31 UTC, rmoff commented
@LonwoLonwo do I need to do anything else here? What's the usual leadtime on the next step? thanks!

2023-11-28 15:35 UTC, LonwoLonwo commented
We are waiting for a test database instance from our dev-ops team now. Also, we have big release now, so, it all can be not so fast.

2023-12-14 11:42 UTC, LonwoLonwo commented
Hello @rmoff 

I checked your PR with a test environment.

And I see here:

```
java.lang.UnsupportedOperationException
	at org.apache.flink.table.jdbc.FlinkDatabaseMetaData.getTables(FlinkDatabaseMetaData.java:139)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getTables(JDBCDatabaseMetaDataImpl.java:1116)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.prepareTableLoadStatement(GenericMetaModel.java:586)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:66)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.prepareLookupStatement(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructLookupCache.reloadObject(JDBCStructLookupCache.java:113)
```

So I can't see my tables. And I can't create a table via UI. 
The only I can do is `SELECT 1`.

So, what is the workflow for this database and DBeaver? Why do we want to add a new driver?

2024-01-15 14:34 UTC, LonwoLonwo commented
Hello again @rmoff 

I hope you are doing well.

Please take a look at my questions: https://github.com/dbeaver/dbeaver/pull/21842#issuecomment-1855694962.

2024-01-29 10:56 UTC, LonwoLonwo commented
Ok. I'm closing this PR. 
For now. 
You can create a new one when you are ready.

2024-01-29 10:56 UTC, closed without merging