#21955 Increase delay before rollback countdown is shown
dbeaver/dbeaver pull request #21976
Opened 2023-11-23 19:16 UTC by ShadelessFox

2023-11-23 19:30 UTC, E1izabeth approved these changes

2023-11-23 20:47 UTC, LonwoLonwo approved these changes

2023-11-24 12:43 UTC, Matvey16 commented
Verified

2023-11-24 13:07 UTC, serge-rider requested changes

2023-11-24 13:07 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditor.java
> -        if (elapsedSeconds < 1) {
Let's make it 300 seconds or configurable.

2023-11-24 13:11 UTC, serge-rider approved these changes

2023-11-24 13:11 UTC, merged