dbeaver/pro#2134 Rendering improvements
dbeaver/dbeaver pull request #21972
Opened 2023-11-23 15:46 UTC by ShadelessFox

2023-11-24 06:45 UTC, E1izabeth approved these changes

2023-11-24 08:35 UTC, serge-rider commented
Not compiling

2023-11-24 15:31 UTC, serge-rider requested changes

2023-11-24 15:31 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/e4/DBeaverStackRenderer.java
> +                final Object element = event.getProperty(UIEvents.EventTags.ELEMENT);
Let's protect it with try/catch throwable.
I am afraid that old Eclipse version or some other thing may cause an unexpected error and may break entire app.

2023-11-27 10:15 UTC, uslss commented
verified

2023-11-27 10:43 UTC, serge-rider approved these changes

2023-11-27 10:43 UTC, merged

2026-01-05 22:27 UTC, pzygielo commented
- Seems that this _improvement_ caused #22275 which was observed almost immediately, but this feature for kids is still there, enabled by default.