CB-4216. Implemented new identity provider - JWT Token.
dbeaver/dbeaver pull request #22122
Opened 2023-12-07 11:31 UTC by DenisSinelnikov

2023-12-07 16:21 UTC, ShadelessFox reviewed
What's up with icons? They look stretched and compressed like they are from 00s.

2023-12-07 17:25 UTC, ShadelessFox approved these changes

2023-12-14 12:48 UTC, alexander-skoblikov requested changes
these icons should not be in this repository

2023-12-14 14:20 UTC, DenisSinelnikov commented
> these icons should not be in this repository

moved

2023-12-29 11:18 UTC, closed without merging