dbeaver/pro#2136 Quoted identifiers highlighting
dbeaver/dbeaver pull request #22201
Opened 2023-12-18 17:06 UTC by E1izabeth

- Quoted identifiers are recognized according to dialect parameters now!
- MS SQL and SQLite -specific identifiers quotation parametrized with plugin.xml, that should have been like that by design.
- Now dialect-specific keywords are highlighted as keywords, where they were treated as identifiers before.

1. When validation by metadata is turned off:

![image](https://github.com/dbeaver/dbeaver/assets/28875055/11e512d8-46af-45e8-8d45-6dcee6c57b3b)

then we see this (note that these databases has different quotes set for identifiers quotation): 

![image](https://github.com/dbeaver/dbeaver/assets/28875055/fdd14a3b-bdfe-4408-9a72-746de06a5579)

![image](https://github.com/dbeaver/dbeaver/assets/28875055/32c22fc8-3d48-42a4-9623-84e450dd5c9a)

![image](https://github.com/dbeaver/dbeaver/assets/28875055/0a267f81-2f6d-44b6-a9ba-22480fac23f9)

2. When validation by metadata is turned on:

![image](https://github.com/dbeaver/dbeaver/assets/28875055/49399f28-7313-4293-9c2b-db3e1c6abcb2)

![image](https://github.com/dbeaver/dbeaver/assets/28875055/d1de5881-35eb-440e-be2b-eedd48b89ef1)

![image](https://github.com/dbeaver/dbeaver/assets/28875055/7ff6a9d8-45f0-4a93-98d4-45011d5c7fa5)

Note that if quotes are wrong for the identifier for some dialect - the thing in some quotes cannot be a quoted identifier, we fallback to our regular highlighting with blue and green for the light theme.

To be tested:
- Quoted columns should be highlighted as a regular columns.
- Quoted tables should be highlighted as a regular tables.
- Test for [ ], " ". ` ` and ' ' quotes for SQLite (all of them can quote identifier), and MS SQL (some of them can quote identifier).

2023-12-18 17:44 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.model.lsm/src/org/jkiss/dbeaver/model/lsm/sql/dialect/LSMDialectRegistry.java
> +                "Failed to resolve LSMAnalyzer for " + dialect.getDialectName() + " dialect. Illegal database driver configuation."
```suggestion
                "Failed to resolve LSMAnalyzer for " + dialect.getDialectName() + " dialect. Illegal database driver configuration."
```

2023-12-18 17:49 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.model.lsm/src/org/jkiss/dbeaver/model/lsm/sql/dialect/LSMDialectRegistry.java
> +                "Failed to resolve LSMAnalyzer for " + dialect.getDialectName() + " dialect. Illegal database driver configuation."
Thanks!

2023-12-19 13:43 UTC, serge-rider requested changes, later dismissed

2023-12-19 13:43 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.generic/plugin.xml
>                      <parameter name="supports-truncate" value="false"/>
Doesn't look like a good idea. We have many SQL Server drivers, we don't want't to copy-paste it everywhere.
Let's use Java level function for that (we already have one in SQLDialect)

2023-12-19 13:43 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.postgresql/.settings/org.eclipse.jdt.core.prefs
> -org.eclipse.jdt.core.compiler.codegen.inlineJsrBytecode=enabled
Let's delete this file from Git

2023-12-20 16:31 UTC, Matvey16 commented
Incorrect highlighting for fully qualified name in postgres

![dbeaver_Tdq9bmncqH](https://github.com/dbeaver/dbeaver/assets/82543000/919a2f7a-660e-4832-804e-43680779b1fa)

2023-12-20 16:52 UTC, Matvey16 commented
https://github.com/dbeaver/dbeaver/assets/82543000/b7226f38-b93e-4f49-b07e-32af0a0599ae

2023-12-22 09:24 UTC, LonwoLonwo approved these changes

2023-12-27 10:08 UTC, Matvey16 commented
Verified

2023-12-28 13:12 UTC, merged