dbeaver/pro#2151 Most of the items in context menu of file explorer are
dbeaver/dbeaver pull request #22221
Opened 2023-12-20 14:30 UTC by serjiokov

not needed

Fixed unrelated menu items for navigator

2023-12-20 14:30 UTC, serjiokov commented
![image](https://github.com/dbeaver/dbeaver/assets/32031248/3b6bef9c-3501-4441-85e7-751b4afc9c2f)

2023-12-20 19:27 UTC, serge-rider requested changes

2023-12-20 19:27 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/NavigatorUtils.java
> +                }
This logic breaks incapsulation. dbvfs resources internals has nothing to do with navigator.
Let's use instanceof DBNNodeWithResource. And add new function isRemoteResource there.
All dbfs resources are from DBNPathBase

2023-12-21 13:19 UTC, serge-rider requested changes, later dismissed

2023-12-21 13:19 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNResource.java
> +    public boolean isRemoteResource() {
It is always local

2023-12-21 13:19 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/fs/DBNPathBase.java
> +    public boolean isRemoteResource() {
It is always remote

2023-12-21 13:28 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/fs/DBNPathBase.java
> +    public boolean isRemoteResource() {
fixed

2023-12-21 16:19 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNResource.java
> +    public boolean isRemoteResource() {
fixed

2023-12-25 15:40 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/NavigatorUtils.java
> +                if (resource instanceof IFolder &&
```java
if ((resource instanceof IFolder) || (node instanceof DBNNodeWithResource nRes && nRes.isRemoteResource()) && 
 id.startsWith("compareWithMenu") || // $NON-NLS-0$
id.startsWith("replaceWithMenu")) { // $NON-NLS-0$
```

I think you can merge the conditions here.

2023-12-25 15:41 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/NavigatorUtils.java
> +                if (resource instanceof IFolder &&
Because it looks like code duplicating.

2023-12-25 19:02 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/NavigatorUtils.java
> +                if (resource instanceof IFolder &&
I think the better to split out on local-remote resource adaptation branches,
DBNNodeWithResource resource = Adapters.adapt(node, DBNNodeWithResource .class);
if(resouce.isRemoteResource()) {
 // logic for remote
}
else {
 // logic for local
}

2023-12-25 19:02 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/NavigatorUtils.java
> +                }
Done

2023-12-25 19:40 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/NavigatorUtils.java
> +                if (resource instanceof IFolder &&
ok

2023-12-25 19:40 UTC, LonwoLonwo approved these changes

2023-12-26 07:24 UTC, E1izabeth approved these changes

2023-12-26 16:30 UTC, Matvey16 commented
Verified

2023-12-28 12:23 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/NavigatorUtils.java
> +                        id.startsWith("replaceWithMenu")) { // $NON-NLS-0$
Did you mean to wrap these two checks in parentheses?

2023-12-28 12:23 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/NavigatorUtils.java
> +                        id.startsWith("addFromHistoryAction")) { // $NON-NLS-0$
We use 4-space continuation indentation. Please configure in `File | Settings | Editor | Code Style | Java`

2023-12-28 13:04 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/NavigatorUtils.java
> +                        id.startsWith("addFromHistoryAction")) { // $NON-NLS-0$
Fixed

2023-12-28 13:04 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/NavigatorUtils.java
> +                        id.startsWith("replaceWithMenu")) { // $NON-NLS-0$
done

2023-12-28 13:15 UTC, ShadelessFox commented
Please test again against the desktop product and team edition

2023-12-28 14:00 UTC, merged