#22341 Don't add statistics to export
dbeaver/dbeaver pull request #22373
Opened 2024-01-08 10:04 UTC by E1izabeth

Statistics should not be added to the exported data anymore.

2024-01-09 08:06 UTC, LonwoLonwo approved these changes

2024-01-09 12:47 UTC, serge-rider requested changes

2024-01-09 12:47 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/StreamTransferConsumer.java
> +            if (!(resultSet instanceof StatResultSet)) {
Just omit rows export? I think we shoul;dnb't perform export for entire resultset.

2024-01-10 13:07 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/StreamTransferConsumer.java
> +import org.jkiss.dbeaver.model.impl.local.StatResultSet;
Do we need this import here?

2024-01-10 13:09 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/StreamTransferConsumer.java
> +import org.jkiss.dbeaver.model.impl.local.StatResultSet;
No, thanks

2024-01-10 15:23 UTC, ShadelessFox approved these changes

2024-01-11 10:57 UTC, MashaKorax commented
verified

2024-01-11 16:59 UTC, serge-rider approved these changes

2024-01-11 17:00 UTC, merged