dbeaver/pro#2309 bug in query validation by metadata for some specific case
dbeaver/dbeaver pull request #22403
Opened 2024-01-10 12:46 UTC by E1izabeth

2024-01-10 16:35 UTC, serge-rider requested changes

2024-01-10 16:35 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/sql/SQLDialect.java
> +    default EnumSet<ProjectionAliasVisibilityScope> getProjectionAliasVisibilityScope() {
Why EnumSet? Can use good old java array instead?

2024-01-15 09:09 UTC, uslss commented
verified

2024-01-15 09:20 UTC, serge-rider approved these changes

2024-01-15 09:20 UTC, merged