#22368 Fix identifiers case sensivity in semantical validation
dbeaver/dbeaver pull request #22443
Opened 2024-01-12 12:52 UTC by E1izabeth

Please check case sensitivity for identifiers (including quoted identifiers) in various databases (DB2, Snowflake, SQL Server, PostgreSQL, SQLite, MySQL, Oracle, Clickhouse)

2024-01-12 17:19 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/semantics/SQLSemanticsUtils.java
> +    public static String identifierToCanonicalForm(SQLDialect dialect, String rawIdentifierString, boolean forceUnquotted) {
Please add NotNull annotations

2024-01-14 12:04 UTC, serge-rider requested changes

2024-01-14 12:04 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/semantics/SQLSemanticsUtils.java
> +public class SQLSemanticsUtils {
Why adding new utility class?
We have SQLUtils and SQLSemanticProcessor.
Maybe we need to refactor some utils but adding new utils with just 1 function looks odd.

2024-01-15 12:48 UTC, LonwoLonwo approved these changes

2024-01-16 10:44 UTC, Matvey16 commented
Now correct column names in quotes are highlighted as incorrect

https://github.com/dbeaver/dbeaver/assets/82543000/e9dafb6d-fd9d-43c6-bf0d-9ce405ed618a

2024-01-17 09:25 UTC, serge-rider requested changes

2024-01-17 09:25 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/sql/SQLUtils.java
> +      String actualIdentifierString;
Indentation

2024-01-17 13:53 UTC, Matvey16 commented
Verified

2024-01-17 14:12 UTC, serge-rider approved these changes

2024-01-17 14:13 UTC, merged