dbeaver/pro#2301 support Oracle new table partitioning
dbeaver/dbeaver pull request #22463
Opened 2024-01-15 17:58 UTC by LonwoLonwo

![2024-01-15 17_13_04-DBeaver Ultimate 23 3 3 - NEWTABLE_11](https://github.com/dbeaver/dbeaver/assets/45152336/7610face-1fa8-4a5d-a648-c9f94b0e9580)

2024-01-16 12:55 UTC, serge-rider requested changes

2024-01-16 12:55 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/edit/OracleTableManager.java
> +                        log.warn("Can't create partitioning without partitions. Create partitions first.");
Why warning? throw an exception

2024-01-16 12:55 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/edit/OracleTableManager.java
> +        String partitionedBy = table.getPartitionedBy(monitor);
Maybe move this into separate function

2024-01-16 12:55 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/model/OracleTablePhysical.java
> -    private PartitionCache partitionCache;
Let's create optional inner caches on demand (as a general rule)

2024-01-16 12:55 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/edit/OracleTableManager.java
> +        String partitionedBy = table.getPartitionedBy(monitor);
Maybe it is a feature for PRO?

2024-01-16 17:45 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/edit/OracleTableManager.java
> +                        log.warn("Can't create partitioning without partitions. Create partitions first.");
Ok, changed.

2024-01-17 08:13 UTC, E1izabeth approved these changes

2024-01-17 11:38 UTC, uslss commented
cannot create a table from schema context menu

https://github.com/dbeaver/dbeaver/assets/31996417/37c8b574-1d79-4344-a8ab-f195659ed35e

2024-01-17 16:57 UTC, uslss commented
still reproducible 
![image](https://github.com/dbeaver/dbeaver/assets/31996417/7c374c4c-6712-4fdb-9825-a0d993651076)

also cannot drop partition and create subpartition - error message is similar

https://github.com/dbeaver/dbeaver/assets/31996417/0ac7d069-e8de-481b-a7fe-5d3e5131731b

2024-01-17 17:48 UTC, uslss commented
![image](https://github.com/dbeaver/dbeaver/assets/31996417/357b5073-44c6-4a14-b641-e100ccba09b8)

2024-01-22 11:53 UTC, uslss commented
error still appears

https://github.com/dbeaver/dbeaver/assets/31996417/1a02127b-27ad-4719-a5c6-5810c87413f1

2024-01-24 18:11 UTC, LonwoLonwo commented
Fixed

2024-01-25 12:32 UTC, uslss commented
verified

2024-01-25 12:52 UTC, merged