dbeaver/dbeaver#2256 splash screen fixed for mac sonoma
dbeaver/dbeaver pull request #22472
Opened 2024-01-16 12:13 UTC by serjiokov

Splash screen fixed for mac sonoma

2024-01-16 12:56 UTC, serge-rider requested changes

2024-01-16 12:56 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverSplashHandler.java
> +         */
1. Check that it is MacOS.
2. Return splash screen in MacOS (see previous PR)

2024-01-16 12:56 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverSplashHandler.java
> +         */
And why use absolute coordinates? What are these numbers and why they are hardcoded?

2024-01-16 13:23 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverSplashHandler.java
> +         */
1. done
2. done
3. This is a property value for product in general all specified in abs coords
```
      <property name="startupMessageRect" value="323,270,242,25"/>
      <property name="startupProgressRect" value="323,255,242,10"/>
```

2024-01-16 13:28 UTC, serge-rider requested changes

2024-01-16 13:28 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverSplashHandler.java
> +         */
These coordinates may change at any moment.
You can create new properties like startupMessageRectMacOS

2024-01-16 14:07 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverSplashHandler.java
> +         */
Not sure if I get it right, these approach of "man on the middle", properties are modified specifically for Mac OS after general reading procedure line:81, initially properties specified in plugin.xml.

2024-01-17 09:17 UTC, serjiokov commented
@serge-rider  one more thing, the splash image in bmp format looks little bit accurate, would we replace the current (.png) ?

2024-01-18 18:08 UTC, closed without merging