dbeaver/pro#2377 App becomes unresponsive when switching router on a certain schema
dbeaver/dbeaver pull request #22559
Opened 2024-01-23 10:51 UTC by serjiokov

Fixed circling graph, enhanced layout
![image](https://github.com/dbeaver/dbeaver/assets/32031248/574e4cb2-098e-4891-84a3-a6abb4ea1e46)

2024-01-23 14:37 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/layout/algorithm/direct/OrthoDirectedGraphLayout.java
> +            List<Node> nextLevelNodes = graph.get(String.valueOf(idx+1));
Please fix the code style.

Also, could you tell me why you're using integers converted to strings as keys? Is there a particular reason for that? It requires more computations than just boxing that integer.

2024-01-23 14:37 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/layout/algorithm/direct/OrthoDirectedGraphLayout.java
> +                            if ((idx - childIndex) > DISTANCE_BTW_LEVELS) {
I'm not sure how it works, but will it handle when there are two tables that point to each other?

2024-01-23 14:55 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/layout/algorithm/direct/OrthoDirectedGraphLayout.java
> +            List<Node> nextLevelNodes = graph.get(String.valueOf(idx+1));
Generally yes it is not needed, I think all enhancement will be done in another ticket.

2024-01-23 14:55 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/layout/algorithm/direct/OrthoDirectedGraphLayout.java
> +                            if ((idx - childIndex) > DISTANCE_BTW_LEVELS) {
If two or more tables will point to each other tables will be on the same level.  This part just handle distance btw entities.

2024-01-23 18:51 UTC, serge-rider requested changes

2024-01-23 18:51 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/layout/algorithm/direct/OrthoDirectedGraphLayout.java
> +            List<Node> nextLevelNodes = graph.get(String.valueOf(idx+1));
Let's fix code style though. 

And generally changing String to Integer is easy, why not do it right here?

2024-01-24 11:45 UTC, ShadelessFox approved these changes

2024-01-26 11:44 UTC, uslss commented
verified

2024-01-26 13:00 UTC, merged