dbeaver/dbeaver#22103 replace autosave focus listener with dispose & tabbing support for datetime
dbeaver/dbeaver pull request #22788
Opened 2024-02-12 12:17 UTC by Destrolaric

Closes dbeaver/dbeaver#22103
*Needs to be tested on MacOS and Linux*
Focus listener is unfortunately not viable for supporting traverse inside the multi control composites, so it was replaced with dispose listener.

Test that all values save properly after inline editing

2024-02-13 14:02 UTC, MashaKorax commented
Mac issue
if the cell is in edit mode and open any application or editor over the app, it becomes full screen
if the cell is in edit mode and go to the value panel, make changes there - nothing happens when you press the apply button, but only when the focus changes 

https://github.com/dbeaver/dbeaver/assets/84867187/ce556226-41e8-4d0c-a0ea-216afed2b311

2024-03-26 09:37 UTC, MashaKorax commented
value panel is not refreshed
https://github.com/dbeaver/dbeaver/assets/84867187/aa0220f1-89d7-4140-8769-7e01e472177f

2024-03-26 18:40 UTC, MashaKorax commented
This case is broken again https://github.com/dbeaver/dbeaver/issues/10561

2024-03-28 08:53 UTC, MashaKorax commented
https://github.com/dbeaver/dbeaver/issues/10561 broken on linux

2024-03-29 14:14 UTC, MashaKorax commented
verified

2024-04-01 06:49 UTC, serge-rider requested changes

2024-04-01 06:49 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/spreadsheet/Spreadsheet.java
> +                System.out.println("Spreadsheet.handleEvent()");
Please remove

2024-04-01 07:31 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/spreadsheet/Spreadsheet.java
> +                System.out.println("Spreadsheet.handleEvent()");
fixed

2024-07-18 08:18 UTC, closed without merging