#22916 [CUBRID] Add Query Plan Feature for the CUBRID plugin
dbeaver/dbeaver pull request #22982
Opened 2024-02-28 05:01 UTC by rathana-pvs

- Display query cost plan as table view
- Show raw query plan in property

2024-02-28 08:50 UTC, LonwoLonwo commented
Hello @rathana-pvs 

Thanks for your contribution.
We will look at it.

2024-02-28 15:14 UTC, ShadelessFox reviewed
Please format your code according to our code style rules:
- Place `{` at the same line where the method is declared
- Use `@NotNull`/`@Nullable` annotations for method arguments and return type

2024-02-28 15:14 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/plan/CubridPlanNode.java
> +        }
Switch expression can be used instead:

```suggestion
        return switch (method) {
            case "iscan" -> "Index Scan";
            case "sscan" -> "Full Scan";
            case "temp(group by)" -> "Group by Temp";
            case "temp(order by)" -> "Order by Temp";
            case "nl-join (inner join)" -> "Nested Loop - Inner Join";
            case "nl-join (cross join)" -> "Nested Loop - Cross Join";
            case "idx-join (inner join)" -> "Index Join - Inner Join";
            case "m-join (inner join)" -> "Merged - Inner Join";
            case "temp" -> "Temp";
            case "follow" -> "Follow";
            default -> method;
        };
```

2024-02-28 15:14 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/plan/CubridPlanNode.java
> +        parseNode();
Can delegate to the overloaded constructor

2024-02-28 15:14 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/plan/CubridPlanNode.java
> +    public String getMethodTitle(String method)
Can be `private`

2024-02-28 15:14 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/plan/CubridPlanNode.java
> +    private void parseObject(List<String> segments)
Please place all private methods at the bottom of the class

2024-02-28 15:14 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/plan/CubridStatementProxy.java
> +    }
Please use `org.jkiss.utils.BeanUtils#invokeObjectMethod(java.lang.Object, java.lang.String)` instead

2024-02-28 15:14 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/plan/CubridStatementProxy.java
> +public class CubridStatementProxy
There is no need to create a wrapper to call a function on the underlying object. Make a static method instead.

2024-02-28 16:26 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.cubrid/OSGI-INF/l10n/bundle.properties
> +meta.org.jkiss.dbeaver.ext.cubrid.model.plan.CubridPlanNode.fullText.name=FullText
```suggestion
meta.org.jkiss.dbeaver.ext.cubrid.model.plan.CubridPlanNode.fullText.name=Full Text

```

2024-02-29 05:19 UTC, rathana-pvs commented
> Please format your code according to our code style rules:
> 
> * Place `{` at the same line where the method is declared
> * Use `@NotNull`/`@Nullable` annotations for method arguments and return type

Will it apply to the entire Cubrid plugin?

2024-03-01 09:26 UTC, LonwoLonwo commented
> Will it apply to the entire Cubrid plugin?

Hello @rathana-pvs 

This advice is only for your code.

2024-03-01 17:20 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/plan/CubridPlanNode.java
> +            String[] removes = segments.remove(0).split(":");
Could you please move all hardcoded strings with duplicates into constants?
Like the:
`private static final String OPTIONS_SEPARATOR = ":";`

2024-03-04 14:22 UTC, Destrolaric requested changes

2024-03-04 14:22 UTC, Destrolaric commented on plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/plan/CubridPlanNode.java
> +                        "[\\n\\r]node\\[....\\s*([^\\n\\r]*)|[\\n\\r].*Query plan:\\s*([^\\n\\r]*)|[\\n\\r].*subplan:\\s*([^\\n\\r]*)|[\\n\\r].*cost:\\s*([^\\n\\r]*)|inner:\\s*([^\\n\\r]*)|outer:\\s*
I am not sure about this regex, I tested it, and it is recognized pretty badly. Can it be separated into simpler regexes?

2024-03-05 11:23 UTC, ShadelessFox approved these changes

2024-03-05 12:12 UTC, Destrolaric approved these changes

2024-03-22 02:09 UTC, rathana-pvs commented
What else do I need to do to get this PR merged into devel?

2024-03-22 04:00 UTC, ShadelessFox commented
Hello @rathana-pvs,

It awaits our QA team. Once it passes the QA, it will be merged.

2024-03-25 12:28 UTC, uslss commented
verified

2024-03-26 14:51 UTC, merged