dbeaver/pro#2493 Change query to read Sybase procedures
dbeaver/dbeaver pull request #23096
Opened 2024-03-08 15:34 UTC by LonwoLonwo

Please check both Sybase instances (12 and 16) with the big script
And any Azure database (that procedures DDLs are still readable)

2024-03-11 10:45 UTC, serge-rider requested changes

2024-03-11 10:45 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/model/generic/SQLServerMetaModel.java
> +                try (JDBCPreparedStatement dbStat = session.prepareStatement(
Code style above + case in select. Why lowercase?

2024-03-13 10:43 UTC, ShadelessFox approved these changes

2024-03-15 12:27 UTC, uslss commented
verified

2024-03-15 12:44 UTC, merged