dbeaver/pro#2484 Google BQ: show the bytes processed or bytes billed
dbeaver/dbeaver pull request #23131
Opened 2024-03-14 11:25 UTC by serjiokov

Facades (factory, result set, session)for BigQuery

2024-03-14 16:09 UTC, ShadelessFox requested changes

2024-03-14 16:09 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.bigquery/src/org/jkiss/dbeaver/ext/bigquery/model/data/BigQueryTrace.java
> +            Object mQueryResponse = BeanUtils.getInheritedFieldValue(mBqResults, "m_queryResponse"); //$NON-NLS-1$
This feels really unsafe. Are there no public getters available so we can at least assume these wouldn't change in the next minor release?

2024-03-14 16:09 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.bigquery/src/org/jkiss/dbeaver/ext/bigquery/model/data/BigQueryTrace.java
> +    private Map<String, String> resultDetails;
See my comment in the other repo.

2024-03-15 15:12 UTC, serjiokov commented
![image](https://github.com/dbeaver/dbeaver/assets/32031248/fcb82ad7-f43f-45e4-bbdd-e4cb3d685aff)

2024-03-15 18:13 UTC, serjiokov commented
![image](https://github.com/dbeaver/dbeaver/assets/32031248/ccbfbcfb-b28b-41b2-8b2d-68b46b3247c1)

2024-03-18 07:57 UTC, serge-rider requested changes

2024-03-18 07:57 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.bigquery/src/org/jkiss/dbeaver/ext/bigquery/model/data/BigQueryTrace.java
> +/*
Move thus feature into com.dbeaver.db.bigquery

2024-03-18 15:14 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.ext.bigquery/src/org/jkiss/dbeaver/ext/bigquery/model/data/BigQueryTrace.java
> +    private Map<String, String> resultDetails;
Fixed

2024-03-18 15:14 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.ext.bigquery/src/org/jkiss/dbeaver/ext/bigquery/model/data/BigQueryTrace.java
> +/*
Fixed

2024-03-18 15:14 UTC, serjiokov commented
![image](https://github.com/dbeaver/dbeaver/assets/32031248/f5802c87-eca3-426a-ba5e-86df21f47c7b)

2024-03-19 16:24 UTC, merged