dbeaver/pro#2555 Get driver lists for different DBeaver Editions
dbeaver/dbeaver pull request #23191
Opened 2024-03-20 17:43 UTC by serjiokov

Specific service provided to export drivers (databases) list to JSON file.

2024-03-20 17:44 UTC, serjiokov commented
Flag requires to use: -`databaseLog`

2024-03-20 18:13 UTC, serjiokov commented
[supported.databases.json](https://github.com/dbeaver/dbeaver/files/14670877/supported.databases.json)

2024-03-21 08:28 UTC, daelynum approved these changes

2024-03-21 10:05 UTC, serjiokov commented
Uasge: -databaseList D:\Path\To\Folder

2024-03-21 10:07 UTC, serjiokov commented
List of databases in JSON format
[database.drivers.json](https://github.com/dbeaver/dbeaver/files/14693375/database.drivers.json)

2024-03-21 10:15 UTC, serge-rider requested changes

2024-03-21 10:15 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.app.standalone/plugin.xml
> +    <extension point="org.jkiss.dbeaver.commandLine">
Why duplicate <extension point="org.jkiss.dbeaver.commandLine"> ?

2024-03-21 10:15 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverCommandLine.java
> +        .addOption(PARAM_DB_LIST, "database-driver-list", true, "Store list of supported database drivers in json format")
Show list of supported dtabase drivers.

2024-03-21 10:18 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverCommandLine.java
> +        .addOption(PARAM_DB_LIST, "database-driver-list", true, "Store list of supported database drivers in json format")
Done

2024-03-21 13:45 UTC, serjiokov commented
List of drivers in JSON format
[database.drivers.json](https://github.com/dbeaver/dbeaver/files/14696043/database.drivers.json)

2024-03-21 19:04 UTC, LonwoLonwo approved these changes

2024-03-28 13:34 UTC, Matvey16 commented
Verified

2024-03-28 16:16 UTC, merged