Cb 3330 data import
dbeaver/dbeaver pull request #23276
Opened 2024-03-29 10:22 UTC by DenisSinelnikov

2024-03-29 14:22 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/importer/DataImporterCSV.java
> +                        if (line.length <= targetAttrSize) {
Why? It doesn't make sense when `line.length == targetAttrSize`

2024-03-29 14:22 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseTransferConsumer.java
> +    }
Please specify `@NotNull` / `@Nullable` annotations.

2024-04-01 09:23 UTC, DenisSinelnikov commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/importer/DataImporterCSV.java
> +                        if (line.length <= targetAttrSize) {
Added for testing, forget to remove.

2024-04-01 10:00 UTC, ShadelessFox approved these changes

2024-04-01 12:28 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseTransferConsumer.java
> +    public void setSettings(@Nullable DatabaseConsumerSettings settings) {
why isn't 'initTransfer' being used?

2024-04-01 12:28 UTC, alexander-skoblikov requested changes

2024-04-01 12:28 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseTransferConsumer.java
> +    public void setSettings(@Nullable DatabaseConsumerSettings settings) {
why isn't 'initTransfer' being used?

2024-04-02 16:50 UTC, alexander-skoblikov approved these changes

2024-04-02 16:51 UTC, merged