Cb 4631 backup database
dbeaver/dbeaver pull request #23325
Opened 2024-04-05 10:35 UTC by DenisSinelnikov

2024-04-08 10:21 UTC, alexander-skoblikov requested changes

2024-04-08 10:21 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/schema/SQLSchemaManager.java
> +                    BackupRegistry.getInstance().getSettings().forEach(p -> p.getInstance().doBackup(dbCon, currentSchemaVersion));
do backup only if schema was changed

2024-04-08 10:21 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/backup/PostgresDatabaseBackup.java
> +                String backupCommand = "pg_dump -h localhost -f " + backupFile + " postgres";
you should use host from db configuration

2024-04-08 10:21 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/backup/PostgresDatabaseBackup.java
> +            Path workspace = DBWorkbench.getPlatform().getWorkspace().getAbsolutePath().resolve("backup");
create a constant for db backup folder

2024-04-08 10:21 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/backup/BackupRegistry.java
> +    public List<BackupSettingDescriptor> getSettings() {
rename method

2024-04-08 10:21 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/schema/SQLSchemaManager.java
> +                    BackupRegistry.getInstance().getSettings().forEach(p -> p.getInstance().doBackup(dbCon, currentSchemaVersion));
why forEach?

2024-04-08 10:21 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.ext.h2/src/org/jkiss/dbeaver/ext/h2/backup/H2DatabaseBackup.java
> +                connection.createStatement().execute(backupCommand);
try with resources

2024-04-08 10:21 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/schema/SQLSchemaManager.java
> +                    BackupRegistry.getInstance().getSettings().forEach(p -> p.getInstance().doBackup(dbCon, currentSchemaVersion));
only one should be used if it is suitable for the current driver/dialect/other reasons

2024-04-08 10:26 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.ext.h2/src/org/jkiss/dbeaver/ext/h2/backup/H2DatabaseBackup.java
> +            log.error("Create backup is failed: " + e.getMessage());
throw backup error and stop migration process

2024-04-08 13:16 UTC, ShadelessFox reviewed
Nullability annotations :saddestcat:

2024-04-10 10:42 UTC, DenisSinelnikov commented
> Nullability annotations :saddestcat:

done

2024-04-11 10:13 UTC, alexander-skoblikov requested changes

2024-04-11 10:13 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.ext.h2/plugin.xml
> +        <backup id="backupH2" class="org.jkiss.dbeaver.ext.h2.backup.H2DatabaseBackup" dialectClass="org.jkiss.dbeaver.ext.h2.model.H2SQLDialect"
use dialect id instead of class

2024-04-11 10:13 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/backup/PostgresDatabaseBackup.java
> +                String backupCommand = String.format("pg_dump -h %s -p %d -U %s -F c -b -v -f %s --schema=%s %s",
password?

2024-04-11 10:13 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/backup/BackupSettingDescriptor.java
> +public class BackupSettingDescriptor extends AbstractDescriptor {
why it's named  `setting`?

2024-04-11 10:13 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/backup/BackupSettingDescriptor.java
> +public class BackupSettingDescriptor extends AbstractDescriptor {
add nullable annotations

2024-04-11 10:13 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/backup/BackupConstant.java
> +public class BackupConstant {
`Backup` prefix sounds strange 🤔🤔🤔

2024-04-11 10:13 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/schema/SQLSchemaManager.java
> +        InternalDatabaseConfig databaseConfig
notnull

2024-04-11 10:16 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/backup/PostgresDatabaseBackup.java
> +                String backupCommand = String.format("pg_dump -h %s -p %d -U %s -F c -b -v -f %s --schema=%s %s",
Why are you formatting this? This is highly insecure if you're accepting user-specified parameters. Just use the variadic `exec` method and pass each argument separately.

2024-04-11 10:16 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/backup/PostgresDatabaseBackup.java
> +                int exitCode = process.waitFor();
It might block indefinitely

2024-04-11 10:28 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.ext.h2/src/org/jkiss/dbeaver/ext/h2/backup/H2DatabaseBackup.java
> +                if (statement != null) {
try with resources

2024-04-11 12:06 UTC, serge-rider requested changes

2024-04-11 12:06 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/backup/BackupConstant.java
> +public class BackupConstant {
SQLBackupCinstants

2024-04-11 12:06 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/backup/BackupDatabase.java
> +public interface BackupDatabase {
JDBCDatabaseBackupHandler

2024-04-11 12:06 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/backup/BackupDatabase.java
> +public interface BackupDatabase {
And other classes also should have prefix JDBCDatabase

2024-04-11 12:06 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/schema/SQLSchemaManager.java
> +                            descriptor.getInstance().doBackup(dbCon, currentSchemaVersion, databaseConfig);
Surround it with try/catch and re-throw  error like "Internal database backup has failed"

2024-04-11 13:56 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.ext.h2/src/org/jkiss/dbeaver/ext/h2/backup/JDBCDatabaseH2DatabaseBackupHandler.java
> +public class JDBCDatabaseH2DatabaseBackupHandler implements JDBCDatabaseBackupHandler {
JDBCDatabaseH2BackupHandler or JDBCH2DatabaseBackupHandler ?

2024-04-11 14:01 UTC, DenisSinelnikov commented on plugins/org.jkiss.dbeaver.ext.h2/src/org/jkiss/dbeaver/ext/h2/backup/JDBCDatabaseH2DatabaseBackupHandler.java
> +public class JDBCDatabaseH2DatabaseBackupHandler implements JDBCDatabaseBackupHandler {
JDBCDatabaseH2BackupHandler

2024-04-16 18:08 UTC, merged