Cb 4268 force logout
dbeaver/dbeaver pull request #23425
Opened 2024-04-14 20:32 UTC by DenisSinelnikov

2024-04-19 10:24 UTC, alexander-skoblikov requested changes

2024-04-19 10:24 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sm/src/org/jkiss/dbeaver/model/auth/SMAuthInfo.java
> +public class SMAuthInfo { //create flag
remove comment

2024-04-19 10:24 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sm/src/org/jkiss/dbeaver/model/security/exception/SMExceptionTooManySessions.java
> +public class SMExceptionTooManySessions extends SMException {
```suggestion
public class SMTooManySessionsException extends SMException {
```

2024-04-19 10:24 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.event/src/org/jkiss/dbeaver/model/websocket/event/WSUserEvent.java
> +public class WSUserEvent extends WSAbstractEvent {
Create separate event for force closed sessions, do not mix it with user delete event

2024-04-19 10:27 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sm/src/org/jkiss/dbeaver/model/security/exception/SMExceptionTooManySessions.java
> +    public SMExceptionTooManySessions(String message, String errorType) {
do we really need `errorType` as parameter? 
it not a general error, and it seems we can just hardcode `tooManySessions` here

2024-04-22 11:27 UTC, alexander-skoblikov requested changes

2024-04-22 11:27 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.event/src/org/jkiss/dbeaver/model/websocket/event/WSUserEvent.java
> +    private final List<String> ids;
```suggestion
    private final List<String> sessionIds;
```

2024-04-22 11:27 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.event/src/org/jkiss/dbeaver/model/websocket/event/WSUserEvent.java
> +    private final List<String> ids;
move this fied to WsUserCloseSessionsEvent

2024-04-22 11:27 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sm/src/org/jkiss/dbeaver/model/auth/SMAuthInfo.java
> +    private final String errorCode;
nullable annotation

2024-04-22 11:27 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sm/src/org/jkiss/dbeaver/model/security/exception/SMTooManySessionsException.java
> +    public String getErrorType() {
nullable annotation

2024-04-22 11:28 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.model.sm/src/org/jkiss/dbeaver/model/auth/SMAuthenticationManager.java
> +    SMAuthInfo finishAuthentication(@NotNull String authId, boolean forceSessionsLogout) throws DBException;
```suggestion
    SMAuthInfo finishAuthentication(@NotNull String authId) throws DBException;
```

2024-04-23 14:29 UTC, yagudin10 commented on plugins/org.jkiss.dbeaver.model.sm/src/org/jkiss/dbeaver/model/auth/SMAuthInfo.java
> +        public Builder serForceSessionsLogout(boolean forceSessionsLogout) {
```suggestion
        public Builder setForceSessionsLogout(boolean forceSessionsLogout) {
```

2024-04-25 13:20 UTC, alexander-skoblikov approved these changes

2024-04-25 13:20 UTC, merged