dbeaver/pro#2795 Editors for objects under a path with special symbols don't get restored
dbeaver/dbeaver pull request #29993
Opened 2024-05-08 12:34 UTC by serjiokov

The node path with spec symbol converted for comparison.

2024-05-08 14:06 UTC, ShadelessFox requested changes

2024-05-08 14:06 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNModel.java
> +            }
Move outside the loop

2024-05-08 14:07 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNModel.java
> +            }
To be honest, I believe this should be done somewhere else. Please take a look where the path gets deserialized.

2024-05-08 14:07 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNModel.java
> +            }
Maybe @alexander-skoblikov has concerns about this change as well

2024-05-08 14:15 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNModel.java
> +            }
Generally, the editor "expectedName" has a node path like "%2F...%2F" in other places node path convertation from %2F to / leads to a wrong segment identifiaction.

2024-05-08 15:21 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNModel.java
> +            }
The methods `normalize/denormalize` were extracted to Utils.

2024-05-09 10:01 UTC, ShadelessFox reviewed
`normailizeNodePath` -> `escapeNodeId`
`unNormailizeNodePath` -> `unescapeNodeId`
What do you think?

2024-05-09 18:05 UTC, serge-rider requested changes

2024-05-09 18:05 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNUtils.java
> +        if (!nodePath.toString().contains(DBNModel.PATTERN_ESCAPE_TOKEN)) {
nodePath.toString() is also expensive.

Do not check NodePAth, check `path` String variable.

2024-05-10 09:27 UTC, Matvey16 commented
We have another error if schema name contains `%`
Maybe it can be fixed in this PR too?

2024-05-10 13:25 UTC, ShadelessFox requested changes

2024-05-10 13:25 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNModel.java
> +    public static final String PATTERN_ESCAPE_TOKEN = "%"; //$NON-NLS-1$
Please remove it.

2024-05-10 13:25 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNModel.java
> +        if (path.contains(DBNModel.PATTERN_ESCAPE_TOKEN)) {
It's used here and assumes _something_ about how paths are escaped. Check this within the `decodeNodePath` method and don't introduce new constants - it introduces unnecessary noise.

2024-05-10 13:26 UTC, ShadelessFox requested changes

2024-05-10 13:26 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNDatabaseNode.java
> -            pathName.insert(0, node.getNodeDisplayName().replace("/", DBNModel.SLASH_ESCAPE_TOKEN));
Forget to escape here

2024-05-10 13:26 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNUtils.java
> +     * The method encode symbols('/', ect)
etc?

2024-05-10 13:26 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNUtils.java
> +            return URLEncoder.encode(path, StandardCharsets.UTF_8);
You **must** escape if there are `%` symbols as well.

2024-05-10 15:29 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNDatabaseNode.java
> -            pathName.insert(0, node.getNodeDisplayName().replace("/", DBNModel.SLASH_ESCAPE_TOKEN));
+

2024-05-10 15:29 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNUtils.java
> +            return URLEncoder.encode(path, StandardCharsets.UTF_8);
+

2024-05-10 16:38 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNUtils.java
> +import java.nio.charset.StandardCharsets;
Redundant imports

2024-05-10 16:38 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNUtils.java
> +import org.jkiss.dbeaver.model.navigator.DBNModel.NodePath;
Redundant import

2024-05-10 16:38 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNModel.java
> +
Redundant change

2024-05-10 16:38 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNLegacyUtils.java
> +            //String item = pathItems.get(i).replace(DBNModel.SLASH_ESCAPE_TOKEN, "/");
Commented-out code

2024-05-13 09:08 UTC, Matvey16 commented
Verified

2024-05-13 10:52 UTC, merged