#29999 Fix race condition when loading navigator nodes
dbeaver/dbeaver pull request #33259
Opened 2024-05-20 16:20 UTC by ShadelessFox

2024-05-21 08:42 UTC, E1izabeth approved these changes

2024-05-21 10:02 UTC, Destrolaric approved these changes

2024-05-21 15:13 UTC, Matvey16 commented
Verified

2024-05-21 15:33 UTC, serge-rider requested changes

2024-05-21 15:33 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNResource.java
> +            synchronized (this) {
I don't think that we can use sync here. It may lead to deadlocks because readChildNodes may interact with UI.

2024-05-23 12:19 UTC, Matvey16 commented
Verified

2024-05-23 12:40 UTC, merged