Dbeaver/pro#2676 fix fqn view postgres
dbeaver/dbeaver pull request #34295
Opened 2024-06-07 10:08 UTC by HocKu7

2024-06-07 10:41 UTC, E1izabeth approved these changes

2024-06-10 06:58 UTC, serge-rider requested changes

2024-06-10 06:58 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/struct/DBStructUtils.java
> +            options.put("needRefreshView", true);
No need to add new constant. 
Use DBPScriptObject.OPTION_REFRESH

2024-06-10 06:58 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreViewBase.java
> +            needRefresh = Optional.ofNullable((Boolean) options.get("needRefreshView")).orElse(false);
Use CommonUtils.toBoolean instead

2024-06-10 10:22 UTC, HocKu7 commented
For those who gonna test it - need to test that case as well https://github.com/dbeaver/dbeaver/issues/34267

2024-06-10 12:39 UTC, ShadelessFox approved these changes

2024-06-10 12:39 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/struct/DBStructUtils.java
> +            options.put("needRefresh", true);
Why can't you use `DBPScriptObject#OPTION_REFRESH` for that?

2024-06-10 12:39 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreViewBase.java
> +            needRefresh = Optional.ofNullable((Boolean) options.get("needRefresh")).orElse(false);
```suggestion
            needRefresh = CommonUtils.getOption(options, "needRefresh");
```

2024-06-10 12:39 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreViewBase.java
> +        if (options != null) {
It can't be `null`

2024-06-11 10:39 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/PostgreUtils.java
> +import org.jkiss.dbeaver.model.exec.DBCSession;
Eh? We use `*` import after 5 imports from the same package. Please update your formatter settings.

2024-06-11 12:11 UTC, HocKu7 commented
For test team - need to test "Show permission" checkbox on objects in Postgres as well

2024-06-17 15:08 UTC, DariaMarkaryan commented
Verified

2024-06-18 16:19 UTC, merged