dbeaver/pro#2711 Amazon Redshift: fix user and permission display
dbeaver/dbeaver pull request #34330
Opened 2024-06-11 16:40 UTC by serjiokov

Introduced API for item disable

2024-06-11 16:45 UTC, serge-rider requested changes

2024-06-11 16:45 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.registry/src/org/jkiss/dbeaver/registry/DataSourceProviderDescriptor.java
> +                System.out.println("changeFolderType " + changeFolderType);
!

2024-06-11 16:53 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.registry/src/org/jkiss/dbeaver/registry/DataSourceProviderDescriptor.java
> +                System.out.println("changeFolderType " + changeFolderType);
Already removed

2024-06-12 12:30 UTC, serge-rider requested changes

2024-06-12 12:30 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/meta/DBXTreeNode.java
> +    public void disposeChild(DBXTreeItem item) {
disposeChild -> removeChild

2024-06-12 12:30 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.registry/src/org/jkiss/dbeaver/registry/DataSourceProviderDescriptor.java
> +    private static final String ATTRIBUTE_DISPOSE = "dispose"; //$NON-NLS-1$
dispose->remove

2024-06-12 12:44 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.registry/src/org/jkiss/dbeaver/registry/DataSourceProviderDescriptor.java
> +    private static final String ATTRIBUTE_DISPOSE = "dispose"; //$NON-NLS-1$
fixed

2024-06-12 12:44 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/meta/DBXTreeNode.java
> +    public void disposeChild(DBXTreeItem item) {
fixed

2024-06-13 14:01 UTC, merged