#22795 Transaction status update fix
dbeaver/dbeaver pull request #34448
Opened 2024-06-24 16:39 UTC by ShadelessFox

2024-06-25 07:05 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditor.java
> +        partListener = new AbstractPartListener() {
Looks a bit over-complicated.
Maybe we'd better check that editor is currently active in the TransactionStatusUpdateJob ?

2024-06-25 21:57 UTC, E1izabeth approved these changes

2024-06-28 10:34 UTC, serge-rider requested changes

2024-06-28 10:34 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditor.java
> +        new TransactionStatusUpdateJob().schedule();
Let's create it in SQLEditor.createPartControl

2024-07-01 12:35 UTC, Matvey16 commented
Verified

2024-07-01 12:37 UTC, merged