Dbeaver/pro#2886 add bigquery dashboards
dbeaver/dbeaver pull request #34860
Opened 2024-07-17 13:50 UTC by HocKu7

2024-07-18 06:38 UTC, serjiokov commented on plugins/org.jkiss.dbeaver.ext.bigquery/plugin.xml
> +                   defaultView="browser"
Would be nice to have i18n here

2024-07-19 12:21 UTC, serge-rider requested changes

2024-07-19 12:21 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.bigquery/plugin.xml
> +        <dashboard id="bigquery-dash"
Please move it to PRO

2024-07-22 16:14 UTC, E1izabeth approved these changes

2024-07-23 09:06 UTC, serjiokov approved these changes

2024-07-30 17:10 UTC, serge-rider requested changes

2024-07-30 17:10 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model.dashboard/src/org/jkiss/dbeaver/model/dashboard/registry/DashboardRegistry.java
> +                //fixme after resolving macOs issue
Super-ugly hardcode.

If we want to disable some dashboard for certain OSes then we need to use OS mapping. 
See driver files mapping xml.

2024-07-31 12:01 UTC, ShadelessFox approved these changes

2024-08-06 05:07 UTC, merged