dbeaver/dbeaver#34796 Fix table alias for new autocompletion
dbeaver/dbeaver pull request #35362
Opened 2024-08-27 10:02 UTC by HocKu7

2024-08-27 13:02 UTC, E1izabeth requested changes

2024-08-27 13:02 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.model.lsm/src/org/jkiss/dbeaver/model/stm/LSMInspections.java
> +            expectingTableName || reachabilityTests.get(SQLStandardParser.RULE_nonjoinedTableReference),
```suggestion
            expectingTableName && (reachabilityTests.get(SQLStandardParser.RULE_nonjoinedTableReference) || presenceTests.get(SQLStandardParser.RULE_nonjoinedTableReference)),
```

2024-08-27 13:02 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/semantics/completion/SQLQueryCompletionContext.java
> +                        })
Let's move it to the caller, like it's done in `collectObjectRecursively` by adding `Function<T, SQLQueryCompletionItem> completionItemFabric` parameter.
```suggestion
                    return components.filter(a -> (componentType == null || componentType.isInstance(a))
                            && a.getName().toLowerCase().contains(componentNamePart))
                        .map(c -> completionItemFabric.apply((T) c))
```

2024-08-27 13:02 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/semantics/completion/SQLQueryCompletionContext.java
> +                                return SQLQueryCompletionItem.forRealTable(dbsEntity, true);
We can't just put true to the second argument. We need to check if it's a first usage of the table or not. Use `alreadyReferencedTables` set for that

2024-08-27 13:08 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.model.lsm/src/org/jkiss/dbeaver/model/stm/LSMInspections.java
> +            expectingTableName || reachabilityTests.get(SQLStandardParser.RULE_nonjoinedTableReference),
And add `SQLStandardParser.RULE_nonjoinedTableReference` to the `presenceTestRule`

2024-08-27 14:56 UTC, E1izabeth approved these changes

2024-08-27 17:39 UTC, ShadelessFox approved these changes
I have no idea what's going on there, but I trust Elizabeth.

2024-09-11 14:16 UTC, Matvey16 commented
Verified

2024-09-16 19:24 UTC, serge-rider approved these changes

2024-09-16 19:37 UTC, merged