Cb 5440 merge into internal db
dbeaver/dbeaver pull request #35594
Opened 2024-09-13 13:19 UTC by DenisSinelnikov

2024-09-16 08:05 UTC, LonwoLonwo commented on plugins/org.jkiss.dbeaver.db.internal/META-INF/MANIFEST.MF
> +Bundle-Vendor: Dbeaver database
```suggestion
Bundle-Vendor: DBeaver database
```

2024-09-16 11:46 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.db.internal/build.properties
> +# DBeaver - Universal Database Manager
Do we need the copyright in this file? 🤔

2024-09-16 11:46 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.db.internal/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
and this

2024-09-17 12:01 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.db.internal/src/org/jkiss/dbeaver/db.internal/InternalDB.java
> +    public InternalDB(InternalDatabaseConfig internalDatabaseConfig, DBPApplication dbpApplication) {
add notnull annotations

2024-09-17 12:01 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.db.internal/src/org/jkiss/dbeaver/db.internal/InternalDB.java
> +    protected DBPApplication getApplication() {
we have `private DBPApplication dbpApplication;`, just return it

2024-09-17 12:01 UTC, alexander-skoblikov commented on plugins/org.jkiss.dbeaver.db.internal/src/org/jkiss/dbeaver/db.internal/InternalDB.java
> +    protected String getCurrentInstanceId() throws IOException {
move back to CBDatabase, because it is not used anywhere else

2024-12-14 16:33 UTC, serge-rider requested changes

2024-12-14 16:33 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.db.internal/src/org/jkiss/dbeaver/db.internal/InternalDB.java
> +public abstract class InternalDB {
I don't really like idea to add apache dbcp dependency into dbeaver. I'd prefer to remove it from dbeaver-ee instead. We should use java.sql.DataSource wherever possible.

I don't like bundle name also. We can keep this code in o.j.d.model.jdbc

2025-03-05 10:19 UTC, closed without merging