#19972 Adjust comment color and font in grid for improved readability
dbeaver/dbeaver pull request #35610
Opened 2024-09-16 10:39 UTC by ivgag

Render comments in the same color as column names and apply an italic style for better differentiation.

![image](https://github.com/user-attachments/assets/8ecdc5a9-fceb-40ad-bc95-941ace58cfe8)
![image](https://github.com/user-attachments/assets/f5c0e6f6-783c-4f64-81ec-9adbe79f5c70)

2024-09-16 17:21 UTC, serge-rider requested changes

2024-09-16 17:21 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/lightgrid/LightGrid.java
> +import org.eclipse.swt.graphics.Color;
By codestyle import of >=5 classes must be grouped with *

2024-09-17 10:19 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/UIUtils.java
> +     * @throws IllegalArgumentException if {@code normalFont} is null.
No, it would be an NPE.

2024-09-17 10:19 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/UIUtils.java
> +     * @param normalFont the original font whose size needs to be modified. Must not be null.
It's already clear from the contract provided by annotations
```suggestion
     * @param normalFont the original font whose size needs to be modified.
```

2024-09-17 13:24 UTC, MashaKorax commented
verified

2024-09-17 14:00 UTC, ShadelessFox approved these changes

2024-09-17 16:26 UTC, merged