dbeaver/pro#3102 hostname could be a optional
dbeaver/dbeaver pull request #35769
Opened 2024-10-01 16:36 UTC by HocKu7

2024-10-02 11:15 UTC, ivgag commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/access/DBAAuthModel.java
> +    default boolean isModelRequireHost() {
```suggestion
    default boolean isHostRequired() {
```

2024-10-02 16:27 UTC, serge-rider requested changes

2024-10-02 16:27 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/access/DBAAuthModel.java
> +        return true;
Host is not required by many JDBC drivers. In Generic driver we can verify this by presence of {host} item in sample URL

2024-10-02 16:27 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.mysql.ui/src/org/jkiss/dbeaver/ext/mysql/ui/views/MySQLConnectionPage.java
> +            DBPAuthModelDescriptor selectedAuthModel = authModelSelector.getSelectedAuthModel();
Let's move this verification (isHostRequiredByAuthModel) to some utils class to avoid copy-paste.

2024-10-09 08:43 UTC, serge-rider requested changes

2024-10-09 08:43 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.connection/src/org/jkiss/dbeaver/ui/dialogs/connection/ConnectionPageWithAuth.java
> +    protected AuthModelSelector authModelSelector;
Let's use getter but direct access

2024-10-09 08:43 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/access/DBAuthUtils.java
> +    public static boolean isPageCompleteByAuthModel(
Let's rename it to isHostPresent.
Btw port is optional for almost all database driver. Why we check it as required?

2026-03-10 07:15 UTC, closed without merging