[CUBRID] Add Tab for Display FullText of Query Plan
dbeaver/dbeaver pull request #35941
Opened 2024-10-14 06:17 UTC by rathana-pvs

**Description**

- Add a tab that allow user to view FullText of Query Plan.

2024-10-16 20:16 UTC, E1izabeth requested changes

2024-10-16 20:16 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/editors/CubridSQLPlanViewProvider.java
> +package org.jkiss.dbeaver.ext.cubrid.ui.editors;
Please add copyright

2024-10-16 20:16 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/editors/CubridSQLPlanViewProvider.java
> +    }
Something is wrong with the formatting here. Could you fix it?

2024-10-22 11:58 UTC, E1izabeth approved these changes, later dismissed

2024-10-22 12:20 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/plan/CubridPlanAnalyser.java
>      public String getPlanQueryString() throws DBException {
```suggestion
    public String getPlanQueryString() {
```

2024-10-22 12:20 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/editors/CubridSQLPlanViewProvider.java
> +        }
You know that the plan is always an instance of `CubridPlanAnalyser`.
```suggestion
        query.setText(((CubridPlanAnalyser) plan).getPlanQueryString());
```

2024-10-22 12:20 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/editors/CubridSQLPlanViewProvider.java
> +    private static final Log log = Log.getLog(CubridSQLPlanViewProvider.class);
```suggestion
public class CubridSQLPlanViewProvider extends SQLPlanViewProviderSimple {
```

2024-10-22 12:20 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/editors/CubridSQLPlanViewProvider.java
> +import org.jkiss.dbeaver.Log;
```suggestion
```

2024-10-23 09:30 UTC, ShadelessFox approved these changes, later dismissed

2024-10-24 09:34 UTC, ShadelessFox commented
Thanks for the contribution! Passing the PR to our QA team now.

2024-11-05 10:56 UTC, uslss commented
@rathana-pvs could you please update devel from your side? thanks in advance

2024-11-12 09:53 UTC, uslss commented
@rathana-pvs and resolve conflicts, please

2024-11-19 09:34 UTC, uslss commented
@rathana-pvs , pr cannot be built due to the errors below:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.9:compile (default-compile) on project org.jkiss.dbeaver.ext.cubrid.ui: Compilation failure: Compilation failure: 
[ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/editors/CubridSQLPlanViewProvider.java:[21] 
[ERROR] 	import org.jkiss.dbeaver.ext.cubrid.model.plan.CubridPlanAnalyser;
[ERROR] 	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Access restriction: The type 'CubridPlanAnalyser' is not API (restriction on classpath entry '/var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/target/classes')
[ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/editors/CubridSQLPlanViewProvider.java:[30] 
[ERROR] 	query.setText(((CubridPlanAnalyser) plan).getPlanQueryString());
[ERROR] 	                ^^^^^^^^^^^^^^^^^^
[ERROR] Access restriction: The type 'CubridPlanAnalyser' is not API (restriction on classpath entry '/var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/target/classes')
[ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/editors/CubridSQLPlanViewProvider.java:[30] 
[ERROR] 	query.setText(((CubridPlanAnalyser) plan).getPlanQueryString());
[ERROR] 	                                          ^^^^^^^^^^^^^^^^^^
[ERROR] Access restriction: The method 'CubridPlanAnalyser.getPlanQueryString()' is not API (restriction on classpath entry '/var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/target/classes')
[ERROR] 3 problems (3 errors)
```

Could you fix it?

2024-11-19 10:47 UTC, rathana-pvs commented
> @rathana-pvs , pr cannot be built due to the errors below:
> 
> ```
> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.9:compile (default-compile) on project org.jkiss.dbeaver.ext.cubrid.ui: Compilation failure: Compilation failure: 
> [ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/editors/CubridSQLPlanViewProvider.java:[21] 
> [ERROR] 	import org.jkiss.dbeaver.ext.cubrid.model.plan.CubridPlanAnalyser;
> [ERROR] 	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [ERROR] Access restriction: The type 'CubridPlanAnalyser' is not API (restriction on classpath entry '/var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/target/classes')
> [ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/editors/CubridSQLPlanViewProvider.java:[30] 
> [ERROR] 	query.setText(((CubridPlanAnalyser) plan).getPlanQueryString());
> [ERROR] 	                ^^^^^^^^^^^^^^^^^^
> [ERROR] Access restriction: The type 'CubridPlanAnalyser' is not API (restriction on classpath entry '/var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/target/classes')
> [ERROR] /var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/editors/CubridSQLPlanViewProvider.java:[30] 
> [ERROR] 	query.setText(((CubridPlanAnalyser) plan).getPlanQueryString());
> [ERROR] 	                                          ^^^^^^^^^^^^^^^^^^
> [ERROR] Access restriction: The method 'CubridPlanAnalyser.getPlanQueryString()' is not API (restriction on classpath entry '/var/jenkins_home/jobs/DBeaverDesktop/jobs/dbeaver-ce/workspace/dbeaver/plugins/org.jkiss.dbeaver.ext.cubrid/target/classes')
> [ERROR] 3 problems (3 errors)
> ```
> 
> Could you fix it?

Okay, done.

2024-12-16 14:28 UTC, uslss commented
![image](https://github.com/user-attachments/assets/3b988f85-db9e-4e71-88c9-1e53df0d987c)

2024-12-17 06:20 UTC, rathana-pvs commented
Sorry, I could not find any issues on my PC. 
Please suggestion me, How could I fix it?

![Screenshot 2024-12-17 130730](https://github.com/user-attachments/assets/2a4f5c83-360e-4c3b-b022-38cfef3606d2)
![Screenshot 2024-12-17 130827](https://github.com/user-attachments/assets/5c6be8e3-b458-4fa1-b1e6-ff91d6795ef3)

2024-12-17 18:32 UTC, E1izabeth commented
I'll take a look

2024-12-18 12:57 UTC, E1izabeth commented
It's not reproducible in development environment, but is reproducible in maven build

2024-12-18 14:00 UTC, E1izabeth commented
@uslss fixed

2024-12-19 08:49 UTC, rathana-pvs commented
> @uslss fixed

I really appreciate your help!

2025-01-08 10:54 UTC, uslss commented
@rathana-pvs please resolve merge conflicts

2025-01-09 12:08 UTC, uslss commented
So now there are two tabs: Simple and FullText with identical data. Also fulltext tab is shown eg. for PostgreSQL and it is empty

https://github.com/user-attachments/assets/6baf5903-aba6-4385-80e3-ecd7d9fe4bb4

2025-01-11 07:36 UTC, rathana-pvs commented
> So now there are two tabs: Simple and FullText with identical data. Also fulltext tab is shown eg. for PostgreSQL and it is empty
> 
>  dbeaver_gSRsQNzLXM.mp4

Oh, I see. @uslss 
It is because of `org.jkiss.dbeaver.ui.editors.sql.plan.registry.SQLPlanViewRegistry.java`

![Screenshot 2025-01-11 142901](https://github.com/user-attachments/assets/a24a941c-fbbc-4781-8c9e-5afe289b4457)

It always add new tab without any filter. please correct me, if I am wrong!
Could you please suggest me, how can I add this tab only for Cubrid?

2025-01-13 20:58 UTC, E1izabeth commented
@rathana-pvs there is no simple solution, or I can't find it right now. We will add this issue to our working process and help you with that.

2025-01-16 03:54 UTC, rathana-pvs commented
> @rathana-pvs there is no simple solution, or I can't find it right now. We will add this issue to our working process and help you with that.

Thank you!

2025-07-01 14:57 UTC, IvanGorshechnikov submitted a review, later dismissed

2025-07-01 15:34 UTC, E1izabeth submitted a review, later dismissed

2025-07-28 09:34 UTC, uslss commented
verified

2025-07-28 12:46 UTC, merged