#35048 Add support for public schemas for semantic query analysis
dbeaver/dbeaver pull request #36060
Opened 2024-10-25 02:13 UTC by E1izabeth

2024-10-25 14:10 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/struct/DBSVisibilityScopeProvider.java
> +    }
Does it really need a default implementation? It seems all its current implementors have it implemented.

2024-11-12 13:11 UTC, serge-rider requested changes

2024-11-12 13:11 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.sqlite/src/org/jkiss/dbeaver/ext/sqlite/model/SQLiteTable.java
> +    public static DBDPseudoAttribute[] obtainAllPseudoAttributes(GenericDataSource dataSource, DBSTable table, @NotNull DBRProgressMonitor monitor) throws DBException {
Monitor must be the first parameter

2024-11-12 13:11 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.sqlite/src/org/jkiss/dbeaver/ext/sqlite/model/SQLiteTable.java
> +            Set<String> columnNames = table.getAttributes(monitor).stream()
Two new sets + case conversion, seems to be over-complicated.
Can you just return ALL_KNOWN_PSEUDO_ATTRS filtered with column presence check? Like table.getAttribute(monitor, name)?

2024-11-12 13:11 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.sqlite/src/org/jkiss/dbeaver/ext/sqlite/model/SQLiteTable.java
> +    public static boolean hasPrimaryKey(DBSTable table) throws DBException {
Also an over-complicated check. Do we really need it?
Can we just return pseudo attrs like they are always there?

2024-11-12 16:25 UTC, uslss commented
verified

2024-11-12 16:57 UTC, merged