#36080 Improve clarity in JSON values export options
dbeaver/dbeaver pull request #36081
Opened 2024-10-28 14:15 UTC by ivgag

![image](https://github.com/user-attachments/assets/619760e4-6e9e-4c89-8beb-ed577551c354)

2024-10-28 15:45 UTC, ShadelessFox requested changes
This PR breaks backward compatibility with the now-removed option. Every saved task that has this option previously enabled will now behave differently.

2024-10-29 09:49 UTC, arhayka commented
> This PR breaks backward compatibility with the now-removed option. Every saved task that has this option previously enabled will now behave differently.

This option was added during the current sprint in the following ticket: https://github.com/dbeaver/pro/issues/3111.
Since it didn’t exist before, no tasks were previously saved with it.

2024-10-29 10:39 UTC, ShadelessFox approved these changes

2024-10-29 11:05 UTC, arhayka approved these changes

2024-10-29 11:05 UTC, HocKu7 approved these changes

2024-10-29 11:10 UTC, serge-rider requested changes

2024-10-29 11:10 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/exporter/DataExporterJSON.java
> +    public static final String PROP_EXPORT_JSON_VALUES_AS_JSON = "embedded JSON";
let's make it just `json`. It is not good to have s[paces in property values

2024-10-29 11:18 UTC, ivgag commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/exporter/DataExporterJSON.java
> +    public static final String PROP_EXPORT_JSON_VALUES_AS_JSON = "embedded JSON";
<img width="392" alt="image" src="https://github.com/user-attachments/assets/0df6c8cf-2fb1-4018-9adb-a02a8008f4ea">

2024-10-29 13:47 UTC, kseniaguzeeva commented
Tested

2024-10-29 14:45 UTC, merged