dbeaver/pro#3301 Fix PostgreSQL role editor
dbeaver/dbeaver pull request #36119
Opened 2024-10-30 21:31 UTC by ivgag

- Save "Valid Until" date option
- Add date picker for easier selection

<img width="529" alt="image" src="https://github.com/user-attachments/assets/bb546c24-f935-4055-b90b-1194fb6f4292">
<img width="276" alt="image" src="https://github.com/user-attachments/assets/e8f77f7c-7797-426e-b4f5-88ca597d72cf">
<img width="1052" alt="image" src="https://github.com/user-attachments/assets/0ddc4a9a-1b1d-4bb5-b203-06df633988fb">

2024-10-30 22:36 UTC, ShadelessFox commented
Please provide a screenshot or a short video showing the new editor

2024-10-30 22:37 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/execute/SQLQueryJob.java
> +            //closeStatement();
Was this commented out intentionally?

2024-10-30 22:37 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/execute/SQLQueryJob.java
> +            log.info("=========== Fetched " + rowsFetched + " rows in " + (System.currentTimeMillis() - fetchStartTime) + "ms");
And this addition is intended? At least make it `debug`, not `info`

2024-10-31 14:15 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/controls/CustomTimestampCellEditor.java
> +        textEditor.addMouseListener(new MouseListener() {
Use `MouseListener#mouseDoubleClickAdapter`

2024-10-31 14:15 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/controls/CustomTimestampCellEditor.java
> +        textFocusListener = new FocusAdapter() {
Use `FocusListener#focusLostAdapter`

2024-10-31 19:01 UTC, ShadelessFox approved these changes

2024-11-04 16:18 UTC, serge-rider requested changes

2024-11-04 16:18 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/properties/PropertyEditorUtils.java
> +        } else if (Timestamp.class.isAssignableFrom(propertyType)) {
Not the best idea to use JDBC specific data type in generic control.
Can we use just Date or LocalDate?

2024-11-06 11:02 UTC, HocKu7 requested changes

2024-11-06 11:02 UTC, HocKu7 commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/controls/CustomLocalDateTimeCellEditor.java
> +            ErrorDialog.openError(
Please add a logging the exception here

2024-11-06 13:26 UTC, ivgag commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/controls/CustomLocalDateTimeCellEditor.java
> +            ErrorDialog.openError(
What is the point of adding logging here? This is a routine case where a user specifies data in an unexpected format, such as ‘yyyy-dd-MM.’

2024-11-07 09:47 UTC, HocKu7 commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/controls/CustomLocalDateTimeCellEditor.java
> +            ErrorDialog.openError(
I prefer to log an exception with warn level in that case. It helps a lot to you in case of searching bugs in the future

2024-11-07 18:32 UTC, ivgag commented on plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/controls/CustomLocalDateTimeCellEditor.java
> +            ErrorDialog.openError(
I see your point, but here, illegal input is common. Adding logging would clutter the logs, making it harder to find useful information.

2024-11-08 04:50 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/edit/PostgreRoleManager.java
> +            options.append(" VALID UNTIL ").append(SQLUtils.quoteString(role, timestamp.toString()));
We just convert timestamp to string. But is Timestamp conversion is compatible with PostgreSQL server format?

2024-11-08 11:02 UTC, ivgag commented on plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/edit/PostgreRoleManager.java
> +            options.append(" VALID UNTIL ").append(SQLUtils.quoteString(role, timestamp.toString()));
Yes, it is. Probably, it would be better to use `DateTimeFormatter`

2024-11-12 15:37 UTC, uslss commented
related issue, existing before https://github.com/dbeaver/dbeaver/issues/36185

verified

2024-11-12 16:58 UTC, merged