Dbeaver/dbeaver#35882 fix sql script execution
dbeaver/dbeaver pull request #36138
Opened 2024-11-01 15:48 UTC by HocKu7

2024-11-04 11:13 UTC, ivgag requested changes

2024-11-04 11:13 UTC, ivgag commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditorBase.java
> +    protected DBPDataSourceContainer getDataSourceContainerForSyntaxRuleReloading() {
```suggestion
    protected DBPDataSourceContainer getDataSourceContainer() {
```
Is it possible to use this container for something else?

2024-11-05 09:17 UTC, HocKu7 commented on plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditorBase.java
> +    protected DBPDataSourceContainer getDataSourceContainerForSyntaxRuleReloading() {
It is possible, but we got a bug with a simple 'get' name and decided to name it differently so it looks safe but awkward; I agree

2024-11-05 14:03 UTC, MashaKorax commented
verified

2024-11-05 14:13 UTC, merged