dbeaver/pro#2631 Fix xlsx import
dbeaver/dbeaver pull request #36163
Opened 2024-11-05 15:43 UTC by HocKu7

2024-11-19 02:32 UTC, ShadelessFox requested changes

2024-11-19 02:32 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/database/DatabaseMappingAttribute.java
> +//                }
This breaks the feature it was made for.

2024-11-19 17:09 UTC, ShadelessFox approved these changes

2024-11-25 12:00 UTC, E1izabeth approved these changes

2024-11-25 13:02 UTC, merged