dbeaver/dbeaver#35808 Rename driver properties to Default properties
dbeaver/dbeaver pull request #36195
Opened 2024-11-07 17:31 UTC by HocKu7

2024-11-08 05:02 UTC, serge-rider requested changes

2024-11-08 05:02 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.connection/src/org/jkiss/dbeaver/ui/internal/UIConnectionMessages.properties
> +dialog_setting_connection_driver_properties_title = Default properties
It looks like not what we wanted.
Default properties are on driver edit dialog. In the connection edit dialog we want to keep everything as is.

2024-11-12 07:55 UTC, MashaKorax commented
What about Cloudbeaver?
![chrome_ZwLjwyX8OF](https://github.com/user-attachments/assets/0c151c86-ad5a-4e71-9009-eb2a36e7c23e)

2024-11-12 08:31 UTC, MashaKorax commented
In Dbeaver  - > Connection configuration dialog - still named Driver properties

2024-11-12 08:31 UTC, MashaKorax commented
![dbeaver_uboPridUyz](https://github.com/user-attachments/assets/da0e8aa2-a5c2-4fc3-9597-455af9c8ab55)

2024-11-12 10:03 UTC, MashaKorax commented
verified

2024-11-12 11:52 UTC, merged