fix: #36413 Improve Chinese localization for org.jkiss.dbeaver.ui.edi…
dbeaver/dbeaver pull request #36414
Opened 2024-11-30 08:39 UTC by witt-bit

Please refer to #36413 as described in this issue. But I have a question. After I build locally and start dbeaver, my translation does not take effect. And when I search for untranslated text globally in IDEA, I cannot find other missing zh files. I confirm that I can find them. I have completed the supplement of zh.

![image](https://github.com/user-attachments/assets/54fd1cc3-06ec-476a-bfc6-fc04e9aef86d)

2024-12-13 16:10 UTC, HocKu7 requested changes

2024-12-13 16:10 UTC, HocKu7 commented on plugins/org.jkiss.dbeaver.ui.editors.sql/OSGI-INF/l10n/bundle.properties
> +sql.formatter.default.name = Standard
Why did you add English localization? Moreover, I bet that it isn't used

2024-12-14 11:30 UTC, witt-bit commented
Sorry, I have corrected it

2024-12-23 18:06 UTC, serge-rider commented
We recoded all properties from charset 8859-1 into UTF-8.
It was a huge update and now it is much easier to work with all localizations. However all existing PRs were broken. You need to update from `devel` branch and then recode your localization into UTF-8.

Sorry for the inconvenience.

2025-01-21 08:29 UTC, witt-bit commented
> We recoded all properties from charset 8859-1 into UTF-8. It was a huge update and now it is much easier to work with all localizations. However all existing PRs were broken. You need to update from `devel` branch and then recode your localization into UTF-8.
> 
> Sorry for the inconvenience.

This method cannot accurately cover keys that have not been localized. In most cases, it may be invalid and bring extra work. I choose to turn it off.

2025-01-21 08:29 UTC, closed without merging