#36124 Truncate History entries
dbeaver/dbeaver pull request #36501
Opened 2024-12-09 16:51 UTC by IvanGorshechnikov

![image](https://github.com/user-attachments/assets/8e5ac860-834d-4f9e-bb3e-40b35406343b)

2024-12-09 17:25 UTC, serge-rider requested changes

2024-12-09 17:25 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetViewer.java
> +            if (desc != null && desc.length() > 50) {
Let's make constant for 50

2024-12-09 17:34 UTC, IvanGorshechnikov commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetViewer.java
> +            if (desc != null && desc.length() > 50) {
Fix it

2024-12-09 17:55 UTC, serge-rider requested changes

2024-12-09 17:55 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetViewer.java
> +    private static final int MAXIMAL_LENGTH_HISTORY_STATE_ITEM = 50;
Naming convention is ZZZ_MAX_LENGTH.
It is also better to declare constant in HistoryStateItem , it is not used anywhere else

2024-12-10 10:53 UTC, E1izabeth approved these changes

2024-12-11 07:10 UTC, MashaKorax commented
verified

2024-12-11 07:46 UTC, merged