#35445 Change table alias to first character of its name
dbeaver/dbeaver pull request #36560
Opened 2024-12-16 10:31 UTC by IvanGorshechnikov

![image](https://github.com/user-attachments/assets/a00a91ca-f3e1-41ad-bc01-abdb582c7136)

2024-12-17 11:04 UTC, E1izabeth commented on plugins/org.jkiss.dbeaver.model.jdbc/src/org/jkiss/dbeaver/model/impl/jdbc/struct/JDBCTable.java
> +            String[] parts = tableFullName.split("\\.");
Better use dialect.getStructSeparator() for dot. I have never seen a database where it's not a dot, but we have this in SQL Dialect (maybe for some reason)

2024-12-17 13:35 UTC, E1izabeth approved these changes

2024-12-17 15:14 UTC, ShadelessFox approved these changes

2024-12-17 19:28 UTC, uslss commented
verified

2024-12-17 19:41 UTC, serge-rider requested changes

2024-12-17 19:41 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.model.jdbc/src/org/jkiss/dbeaver/model/impl/jdbc/struct/JDBCTable.java
> +            List<String> parts = CommonUtils.splitString(tableFullName, (dataSource.getSQLDialect().getStructSeparator()));
Use SQLUtils.generateEntityAlias

2024-12-25 11:43 UTC, Matvey16 commented
Verified

2024-12-25 11:55 UTC, merged