#35995 Add Custom STATISTICS Info Tab and Driver setting.
dbeaver/dbeaver pull request #36630
Opened 2024-12-24 13:10 UTC by rathana-pvs

**Description**
- add info tab for display trace text and statistic table
- add pref page setting for statistic

2025-01-09 11:11 UTC, E1izabeth approved these changes, later dismissed

2025-01-15 21:35 UTC, ShadelessFox requested changes
Additionally, please fix the formatting.

2025-01-15 21:35 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/plugin.xml
> +                description="%controls.CubridInfoStistic.description"
Typos

2025-01-15 21:35 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/controls/CubridInfoStatistic.java
> +    DBPPreferenceStore store = DBWorkbench.getPlatform().getPreferenceStore();
A particular reason to be package-private?

2025-01-15 21:35 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/controls/CubridInfoStatistic.java
> +//      this.planPanel.setBackground(parent.getDisplay().getSystemColor(SWT.COLOR_WIDGET_BACKGROUND));
Please no commented-out code

2025-01-15 21:35 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/controls/CubridInfoStatistic.java
> +//        UIUtils.setControlContextMenu(table, manager -> UIUtils.fillDefaultTableContextMenu(manager, table));
Please no commented-out code

2025-01-15 21:35 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/views/PrefPageCubrid.java
> +            trace = UIUtils.createCheckbox(planGroup, CubridMessages.statistic_trace_info, false);
Use radio buttons if selection is exclusive

2025-01-15 21:35 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/views/PrefPageCubrid.java
> +		}
Could be a direct assignment.

```suggestion
		info.setSelection(store.getString(CubridConstants.STATISTIC).equals(CubridConstants.STATISTIC_INFO));
		allInfo.setSelection(store.getString(CubridConstants.STATISTIC).equals(CubridConstants.STATISTIC_ALL_INFO));
```

2025-01-15 21:35 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/CubridSQLDialect.java
> +		JDBCStatement st =  session.createStatement();
You must close the statement.

2025-01-15 21:35 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/controls/CubridInfoStatistic.java
> +    }
Please add comments that these methods are left empty intentionally

2025-01-15 21:36 UTC, ShadelessFox commented
Consider using the `org.jkiss.dbeaver.resultset.panel` extension point instead of creating a new whole presentation.

2025-01-24 05:13 UTC, rathana-pvs commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/controls/CubridInfoStatistic.java
> +    DBPPreferenceStore store = DBWorkbench.getPlatform().getPreferenceStore();
Did you refer to `private static final Log log = Log.getLog(CubridInfoStatistic.class);`? 
If so, this log is dedicated to CubridInfoStatistic only, it should not used by other. or I misunderstood your question, please let me know!

2025-01-24 11:57 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/controls/CubridInfoStatistic.java
> +    DBPPreferenceStore store = DBWorkbench.getPlatform().getPreferenceStore();
```java
DBPPreferenceStore store = DBWorkbench.getPlatform().getPreferenceStore();
```

2025-02-05 15:19 UTC, ShadelessFox requested changes

2025-02-05 15:19 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/CubridSQLDialect.java
> +
```suggestion
        try (JDBCStatement st = session.createStatement()) {
```

2025-02-05 15:19 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/CubridSQLDialect.java
> +            }
```suggestion
```

2025-02-05 15:19 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/CubridSQLDialect.java
> +    private void setTracking(@NotNull JDBCSession session) {
By the way, why is it here? It looks really out of place. It'd make much more sense to have this logic in `CubridDataSource`

2025-02-05 15:19 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/views/PrefPageCubrid.java
> +        super();
```suggestion
```

2025-02-05 15:19 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/controls/CubridInfoPanel.java
> +        JDBCResultSet resultSet = stm.executeQuery(queryInfo);
You must close the result set to avoid resource leaks

2025-02-05 15:19 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/controls/CubridInfoPanel.java
> +                                JDBCStatement stm = session.createStatement();
You must close the statement to avoid resource leaks

2025-02-05 15:19 UTC, ShadelessFox commented on plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/controls/CubridInfoPanel.java
> +                                    JDBCResultSet resultSet = stm.executeQuery("show trace;");
You must close the result set to avoid resource leaks

2025-03-05 11:22 UTC, ShadelessFox commented
@rathana-pvs please resolve conflicts

2025-03-24 14:40 UTC, uslss commented
verified

2025-03-24 14:58 UTC, ShadelessFox commented
@rathana-pvs please resolve merge conflicts

2025-03-25 07:00 UTC, merged