dbeaver/pro#3661 Add option to compact JSON/XML value
dbeaver/dbeaver pull request #36645
Opened 2024-12-27 10:23 UTC by IvanGorshechnikov

![image](https://github.com/user-attachments/assets/5a959d2e-90ba-49f5-a07e-02010e7326bd)

2024-12-27 13:23 UTC, serge-rider requested changes

2024-12-27 13:23 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.json/src/org/jkiss/dbeaver/ui/data/managers/stream/JSONPanelEditor.java
> +        Gson gson = new GsonBuilder()
Reuse gson from JSONFormattingStrategy, use some factory method to create formatted/non-formatted gson parser.

2024-12-27 13:23 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.xml/src/org/jkiss/dbeaver/ui/data/managers/stream/XMLPanelEditor.java
> +        return value.replaceAll(">\\s+<", "> <");
Very bad idea. It will corrupt xml in case of CDATA, for example.
You need to parse XML and then perform transformation to remove formatting.
E.g. https://stackoverflow.com/questions/8476318/how-to-unformat-xml-file , https://www.baeldung.com/java-pretty-print-xml

2024-12-30 14:49 UTC, serge-rider requested changes

2024-12-30 14:49 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.xml/src/org/jkiss/dbeaver/ui/data/managers/stream/XMLPanelEditor.java
> +                if (child.getNodeValue().trim().isEmpty()) {
Use isBlank instead

2024-12-30 14:49 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.xml/src/org/jkiss/dbeaver/ui/data/managers/stream/XMLPanelEditor.java
> +                child.setNodeValue(cdata.getNodeValue().trim());
No need to trim cdata

2024-12-30 16:05 UTC, Matvey16 commented
Verified

2024-12-30 16:22 UTC, serge-rider requested changes

2024-12-30 16:22 UTC, serge-rider commented on plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/data/managers/AbstractTextPanelEditor.java
> +            final Action msAction = new SaveMinifyValue();
Just realized that we need it only for JSON and XML.
For other formats we mustn't show this option.

2025-01-06 12:48 UTC, Matvey16 commented
Verified

2025-01-06 15:55 UTC, merged